### ISSUE TITLE
Map thumbnail is not visible from the Save panel

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10062]
## Description

By opening the save panel from the sidebar, the previously added thumbnail is no longer visible on the thumbnail box

https://github.com/geosolutions-it/MapStore2/assets/56537133/b6f81dc8-3c28-47fd-bdcd-098021737d08

## How to reproduce

-  Open a map with a thumbnail
-  Click o Save 

*Expected Result*

The thumbnail is visible on the thumbnail box

*Current Result*

The thumbnail is not visible on the thumbnail box

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

The issue is not present on PROD

**Comment by MV88** [comment]
@tdipisa a quick update:

this regression is due to this commit https://github.com/geosolutions-it/MapStore2/commit/bc136b9792ed579e428ee4627ff6f620d251979f

restoring attributes to true is enough to resolve it, but i need to better investigate if this breaks the fix for https://github.com/geosolutions-it/MapStore2/issues/9946

**Comment by MV88** [comment]
i have found a fix, tomorrow i'll prepare a PR after checking tests

**Comment by tdipisa** [comment]
Thank you @MV88 (FYI @Igi-ID)
