### ISSUE TITLE
Annotation click-right options in embedded mode

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#10125]
## Description

When a map is share in embedded mood, for the Annotation there is not click-right options.

https://github.com/geosolutions-it/MapStore2/assets/56537133/d63de460-81e7-4b86-b9bd-90449cf57e91

## How to reproduce

-  Open this [embedded  map](https://dev-mapstore.geosolutionsgroup.com/mapstore/embedded.html?forceDrawer=true#/49266)
-  Click-right on Annotation

*Expected Result*

The Zoom to extent and Remove buttons are visible on the settings popup

*Current Result*

There is not setting popup for the annotation

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by allyoucanmap** [comment]
> The Zoom to extent and Remove buttons are visible on the settings popup

@tdipisa @ElenaGallo 

I'm working on the fact that the the zoom to layer is not visible but the missing remove button is expected because the configuration in the localConfig is set to false for layers and groups

![image](https://github.com/geosolutions-it/MapStore2/assets/19175505/d1b72d69-fd0d-4417-adaf-6d07e14bff7d)

**Comment by tdipisa** [comment]
ok @allyoucanmap
