### ISSUE TITLE
Create a background switcher component

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#114]
Create a component to switch between available backgrounds. 
see #35 background layers (distinct component)

**Comment by offtherailz** [comment]
#### Current running mockup 

###### Desktop version : 
![mapstore 2 viewer](https://cloud.githubusercontent.com/assets/1279510/9995953/1d9e018a-6085-11e5-92c4-bd0cd00dfbc9.png)

###### Mobile version (vertical layout). 
![bssd](https://cloud.githubusercontent.com/assets/1279510/9996039/7255dce8-6085-11e5-8d96-8c4be2b6ea4f.png)

**Comment by simboss** [comment]
In the future we want to be able to change the CRS of the map. Most of these backgrounds are compatible only with certain gridsets (i.e. CRS, zoom levels, etc..).

The background level mechanism needs to be somehow configurable/extensible in order to account for a background which is in a different CRS and does not come from standard de facto tile services.

**Comment by mbarto** [comment]
The background switcher populates using all the configured layers in the background group. My only doubt is: how do you create the thumbnail for "unknown" backgrounds? Do you use a default one?

**Comment by offtherailz** [comment]
You can see there is a "Preview not available" icon, (in the mockup for MapQuest). I will provide icons for the common background (Google, OSM, Bing) and the possibility to add a "thumbURL" option for the layer to use. If even the thumb is not present, the "Preview not available" image will be shown.
