### ISSUE TITLE
Layer Style switcher

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1194]
Enable the "style" tab in the layers properties window

**Comment by offtherailz** [comment]
In order to avoid the getCapabilities when possible I suggest a procedure to retrieve the list of the styles.

If the layer is from a WMS, we already have these information. We will save the list in the layer's info inside the map.

If the layer is from a CSW, we don't have the styles list. In some application we provide the Capabilities URL in the CSWRecord, and if possible (from GeoServer's CSW) that is the layer's specific capabilities, so the lightest version possible. 

So the user will see this: 
![image](https://cloud.githubusercontent.com/assets/1279510/19961076/dd3ce584-a1b0-11e6-9330-f4ac11260316.png)

The user can type the style name inside the textbox to search in the list (if present) or to insert the style name.
If he clicks on the refresh button the list of the available styles will be refreshed using the capabilities url retrieved from the CSW (if present) or trying to generate it from the WMS URL. 
In case of error (via timeout or other) the user will be notified but he is allowed anyway to insert the style manually.

As a plus, If legend URL is available, also the legend should be visible in this window, when a style is selected.
