### ISSUE TITLE
ShapeFile in EPSG:3857 are not imported correctly

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1307]
This is an issue of shpjs itself. Try to import these 2 files. In the shpjs demo, on MapStore2 and in some other tool like QGIS.

[export1_(Correct).zip](https://github.com/geosolutions-it/MapStore2/files/621588/export1_.Correct.zip)
[export_1.zip](https://github.com/geosolutions-it/MapStore2/files/621589/export_1.zip)

Result: 
![image](https://cloud.githubusercontent.com/assets/1279510/20749939/bae74f98-b6f4-11e6-9d43-c8731758c613.png)

**Comment by saidaipparla** [comment]
added jsfiddle for this issue which is causing problems while importing using wkt and proj4 of EPSG:3857 
https://jsfiddle.net/saisoft00/c7vecefz/13/

![shape](https://cloud.githubusercontent.com/assets/22316694/21150424/3292500a-c15f-11e6-9efe-ceab0a8ac8d0.png)

**Comment by offtherailz** [comment]
Thanks for investigation, You should provide this example opening an issue on proj4js project, to get some clarification.

**Comment by saidaipparla** [comment]
yes created the issue here
https://github.com/proj4js/proj4js/issues/220

**Comment by offtherailz** [comment]
See this : https://github.com/proj4js/proj4js/issues/220

**Comment by Gnafu** [comment]
Maybe related to #2325

**Comment by MV88** [comment]
The problem is related to the projection definition as wkt string.
wkt-parser used by proj4 is misparsing the wkt string and that messes up the reprojection.

A solution is to change the prj definition from wkt to proj.
Another is to investigate the wkt parser and try to provide a solution there.

**Comment by mbarto** [comment]
A couple of things are wrong:
 * first of all the PRJ file is ambiguous: the declared EPSG is EPSG:3857, but the detail options are wrong, the DATUM in particular is not a sphere, but the WGS84 ellipsoid, so if we consider one or the other we get different results
 * there is a bug in the WKT parser, so a wrong result is given also if the PRJ is correct

Do we have other examples of shapefiles in EPSG:3857 that are not correctly positioned, so that I can do further testing in common use cases?

What we can do is trusting the authority if present and recognized by proj4 (EPSG:3857) and only fallback to detail params if not. This requires patching proj4.

**Comment by mbarto** [comment]
https://github.com/proj4js/proj4js/pull/274
