### ISSUE TITLE
PDF preview doesn't work without CORS headers on server

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#1331]
It looks like the final pdf file is loaded without a proper proxy, so it doesn't work if CORS headers are not enabled on geoserver.

**Comment by saidaipparla** [comment]
https://github.com/mozilla/pdf.js/issues/4530#issuecomment-188059771
**as it described here solution for this issue is as follows**
For the javascript viewer to display a remotely-hosted pdf document, the following configuration values are necessary:
Access-Control-Allow-Headers "range"
Access-Control-Expose-Headers "content-range, content-length, accept-ranges"

**Comment by mbarto** [comment]
We cannot assume we have CORS headers enabled (or change them) on a server.

What we can do is use our proxy to access the url (as we do for requests that we run through axios).

Basically, here (https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/print/index.js#L131) we should replace the original url with a url for the proxy. Look here: https://github.com/geosolutions-it/MapStore2/blob/master/web/client/libs/ajax.js#L156
