### ISSUE TITLE
Allow wfs searches without specifing filters

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#1441]
Allow the query panel to start a search without a filter

**Comment by simboss** [comment]
Rationale behind this is to allow users to query the WFS without specifying a filters. 

As a result we should load the first page of results to not kill both server and client. Depending on the version of the WFS we are querying paging might not be implemented (going by memory) hence it is worth to ask for confirmation since in that case we might be in troubles.
