### ISSUE TITLE
Support to include theme 2.0

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#1496]
Include and support theme 2.0.

After this step, we can imagine to allow inclusion and dynamic switching with proper loaders. see this: https://github.com/geosolutions-it/MapStore2-theme/pull/99

**Comment by allyoucanmap** [comment]
Some notes:

```html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<!--<link rel="stylesheet" href="https://rawgit.com/geosolutions-it/MapStore2-theme/master/theme/default/css/css.css">-->
<link rel="stylesheet/less" type="text/css" href="MapStore2-theme/theme/default/theme.less" />
<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
<link rel="stylesheet" href="MapStore2-theme/theme/default/css/ms2-theme.css">
<link rel="stylesheet" href="MapStore2-theme/theme/default/css/icons.css">
```
I included the theme2.0 with the above setup with the less CDN to test the variables.less.
I noticed that if i try to change the brand color (e.g. black) it changes only in few styles (e.g. background of icons) the others are still the same color because there are color/background-color in the ms2-theme.css.
In the image are highlighted in red all the color/backgroung color in the ms2-theme.css.

![eye5](https://cloud.githubusercontent.com/assets/19175505/23252637/d7573a76-f9b1-11e6-9e28-6b6b9664269c.png)

Some icons have a overflow problem, in the image below the eye is clipped the reason could be                                                               because the font is outside of the borders

![eye3](https://cloud.githubusercontent.com/assets/19175505/23252821/7329fc54-f9b2-11e6-8ec1-3643eed67520.png)

this is the theme2.0 eye font

![eye](https://cloud.githubusercontent.com/assets/19175505/23252798/67f20c8c-f9b2-11e6-9f36-4769eab2fb71.png)


this is the previous eye font

![eye2](https://cloud.githubusercontent.com/assets/19175505/23252859/9931ae4c-f9b2-11e6-8737-6f41fa597278.png)
