### ISSUE TITLE
Check all the TODOs and remove the completed ones

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1559]
There are a lot of opened TODO. 
We should: 
- [ ] remove the closed one
- [ ] add a deadline or a reference to any opened issue

**Comment by mbarto** [comment]
What do you mean by open TODO? Please, add a list here or close this one.

**Comment by MV88** [comment]
i meant in the comments // TODO ...

**Comment by offtherailz** [comment]
The confusion was because you provided a list of TODOs to remove TODOs :smile: 
I'm not fear about TODOs,
They are ~80 in all MS.
Most of them are only
 - some suggestions of possible improvements (e.g. TODO cache the response)
 - missing capability of a function that can be added easy (e.g. TODO check validity of the object)
 - Notify about some hacks due some issue on depending libraries. (e.g. TODO remove when <issue-ref> is fixed>

And always refer that line of code.
When you find one of them you can implement, update or remove them.
I think we can close this issue. @mbarto do you agree?

**Comment by mbarto** [comment]
Yes, I think we should remove reminders of remembering to remember
