### ISSUE TITLE
Leaflet Map cannot be zoomed after scale 1:2257

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#1639]
The bug can be replicated using the scalebar.
This works fine using openlayers.

**Comment by MV88** [comment]
I wanted to customize the scale list but I discovered some problems.
The fact is that the scales are defined in the connect method of the scalebox plugin. 
Thus they are not overridable from the config.

This is a general problem and should be opened a proper issue in order to fix this.

**Comment by MV88** [comment]
Overriding the scales is not a good solution, thus this issue need to be investigated more

**Comment by offtherailz** [comment]
The problem could be resolved setting maxZoom and maxNativeZoom for each TileLayer configuration and overriding them properly in the map components. 
[Reference](http://wesmapping.com/blog/zoom-past-maximum-tile-level-with-leaflet/)

**Comment by MV88** [comment]
This issue is more tricky than expected.
I can set maxZoom and maxNativeZoom with different defaults on Google and OSM with no problems.

some issues raise here:
- The Tileprovider layer can have different max native zoom (nasa 8, opentopomap around 16). in this case we should save also the maxNativeZoom for each of them. I accept suggestions.
- We also need to update the scalebar when the background is changed.
- Actually if we change the background from OSM with zoom level 21 to google layer, we need to change the zoom level to its max (19) if not available.

All of the above should be done only for leaflet though

**Comment by MV88** [comment]
see #394
