### ISSUE TITLE
Override properties used in connect methods from configuration

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#1645]
It is known that the properties used in connect method are not overridable from the config.
This can be achieved with some workaround ( set them in componentWillMount) but this is bad practice.

**Comment by offtherailz** [comment]
We could set the initialState in componentWillMount or use something like "initialActions" to run on Plugins add for connect .
A convention should help...
Otherwise every plugin does it by itself. @mbarto what do you think. Should we schedule this for this release?

**Comment by mbarto** [comment]
I would avoid using lifecycle methods. My idea:
 * define a connect wrapper using a custom mergeProps function
 * use the connect wrapper in plugins definition
 * the custom mergeProps will override connected props with props from the plugin cfg (instead of the opposite)

I am going to prepare a PR for this

**Comment by MV88** [comment]
👍
