### ISSUE TITLE
Add an option to query panel to filter by Layer

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#1920]
### Description
Like in MapStore1, the possibility to use the crosslayer filtering mechanisms in query tool.

### Please indicate if this issue is related to a bug or a new feature request
- [x] New Feature

### In case of New Feature

*Acceptance Criteria - AC*

- Add a new filter type in which the user can select a layer from the available layers in TOC and then use that layer to perform a search with a crossLayer filter
- Add the possibility to have the attribute filter for the crossing layer filter

### Other useful information:
**mockup**
http://demo.geo-solutions.it/mockups/mapstore2/#/query-builder

**Comment by chiaracurcio** [comment]
There is a problem with the crosslayer filtering in MS2: 
in Target layer only one layer is available despite more than one are available in TOC.

![layer_filter](https://user-images.githubusercontent.com/33256901/33672846-8fa54f0c-daab-11e7-8547-e949433a6df0.png)

**Comment by offtherailz** [comment]
To check what layers are available for crossLayer filter the application checks the url of the layers (they have to be the same). 
![image](https://user-images.githubusercontent.com/1279510/33674265-454bb19a-daaf-11e7-94bd-e89ecfab8a71.png)

As you see the urls are different : 
```
https://demo.geo-solutions.it:443/geoserver/wfs"
https://demo.geo-solutions.it/geoserver/wfs
```
This is probably because the US States map was saved a long time ago and in the meanwhile something changed search URL save procedure, so now you have also the port. 

It is not a problem of the crossLayer itself, anyway we can make it smarter and understand that if https is present, the 443 port is the same of no port, and the same for http and port 80.

**Comment by chiaracurcio** [comment]
A new issue has been open for this bug: https://github.com/geosolutions-it/MapStore2/issues/2465
