### ISSUE TITLE
Circle spatial filter shows different selections on high denominator scales

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2222]
tested on leaflet.
to reproduce:
- select a WMS layer
- open feature grid
- select advanced search
- select circle spatial filter and draw on map
- click on search
- back to advanced search
now the circle has a different geometry (high denominator scales)

while drawing the filter
![circle1](https://user-images.githubusercontent.com/19175505/30850229-1fd7d728-a2a5-11e7-9853-abc74d83bf9a.png)

back to advanced search
![circle2](https://user-images.githubusercontent.com/19175505/30850231-20ff4b40-a2a5-11e7-862c-ad9fb72ab123.png)

difference between above images
![circle](https://user-images.githubusercontent.com/19175505/30850182-fc9defcc-a2a4-11e7-815e-597cd2d94827.png)

**Comment by allyoucanmap** [comment]
Update: 
after back to advanced search and changed the selection details
circle geometry is a point on map (center)

![screenshot from 2017-09-28 14-51-50](https://user-images.githubusercontent.com/19175505/30967530-e10dc98a-a45c-11e7-8ffe-47adcca98f45.png)

**Comment by offtherailz** [comment]
About the main issue, The cause is mainly this:
https://github.com/geosolutions-it/MapStore2/blob/8a70613ff895e04742a565c726ec10250324a07a/web/client/utils/CoordinatesUtils.js#L476
That doesn't properly fit the leaflet case. 
Take a look at [this](https://github.com/w8r/L.Circle.toPolygon) maybe it can fix the leaflet case. 
About the update in comment, i opened a separate issue for that #2321

**Comment by MV88** [comment]
note: issue #2321 has been closed

**Comment by MV88** [comment]
I found a solution for this issue, but it remains the problem while switching from ol to leaflet and viceversa beacuse of the different radius calculated. I'm opening an issue for that
