### ISSUE TITLE
Unable to load public WMTS

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#2227]
I was trying to load layers from [this public WMTS](https://tiles.maps.eox.at/wmts/1.0.0/WMTSCapabilities.xml) without any luck.

Specifically the Sentinel 2 cloudless, we should investigate where the problem is.

**Comment by offtherailz** [comment]
From a first look, the error happens because the tileset for  `EPSG:3857` is not available. We should choose how to softly fail, when the SRS of the map is not available in the tileset:
 - show an error when you try to add the layer
 - disable the add layer button with a tooltip that explains why you can't add the error
 - do not show the button if the SRS of the map is not available

##### details
the error happens here in leaflet:
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/leaflet/WMTS.js#L81

because matrix is not an array but an object of this kind:
`Object {WGS84: Array(18), EPSG:4326: Array(18)}` (no EPSG:3857` published) 

With OpenLayers more or less the same:
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/WMTSUtils.js#L23
matrix[srs] doesn't exist because it is looking for `EPSG:3857`

**Comment by Gnafu** [comment]
Fixed in QA-2017.05.00
