### ISSUE TITLE
Strange behavior with LaMMa Services

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#2229]
I tried to load LaMMa WMS services from [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/leaflet/3125) GetCapabilities document and I have seen a number of problems:

- [ ] As per image below an empty search does not work but a search with "temperatura" works fine. Strange
- [ ] The data grid tool is eanbled but the query we send is wrong. I am not sure how we do configure this WFS client here since I issued a WMS GetCap so not sure how the links are inferred.

![lamma1](https://user-images.githubusercontent.com/693880/30914031-7c6ddea4-a392-11e7-8a6b-818203115264.jpg)

![lamma2](https://user-images.githubusercontent.com/693880/30914057-9242070a-a392-11e7-9bc7-54387b836e03.jpg)

**Comment by simboss** [comment]
When we get these reports it would be good to provide some feedback on what the problem was and how we intend to solve it.

As a user I find it very hard to understand if the fix is fixing the problem at large or not.

So... Can I get some feedback? :)

**Comment by mbarto** [comment]
The problem was handling Dimension entries in Capabilities. When a list of values was not present the parser crashed:

`<Dimension name="time" default="current" units="ISO8601"/>`

was crashing, while

`<Dimension name="time" default="current" units="ISO8601">
2017-10-01T00:04:29.000Z/2017-10-03T13:48:31.000Z/P2DT13H44M2S
</Dimension>`

was not.

This is the reason why searching worked (it was filtering out "bad" records)

**Comment by simboss** [comment]
thx
