### ISSUE TITLE
Custom Format on Get Feature Info

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#2542]
### Description
Add Markdown Template on Get Feature Info Plugin

- [x] Change layer/group settings from modal to panel
- [x] Add Markdown Template as response format

Due to changes on TOC Settings and Identify Plugins a complete reviews of functionality is needed

**Comment by chiaracurcio** [comment]
there are any points to improve and correct:  

1) when the settings tool (from the burger menù) is open and a GetFeature Info window response is open in the same time, changing the Feature Info format on the settings tool, the response not changes the format accordingly but it seems like he wants to try.
![immagine](https://user-images.githubusercontent.com/33256901/36541983-e44099d8-17df-11e8-8645-0013aa0feac0.png)

2) if you want open the settings tool when the FeatureInfo windows is open on the rigth you can't, because this window cover the burger menù (it should be enhanced) 

3) using Get FeatureInfo in embedded version (and also with APIs) the column headings scoll with the other feature information (it should be enhanced to improve the data viewing expecially when there are many feature in a same point)
