### ISSUE TITLE
Performance issues when layer loading indicator is active

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#266]
When the layer loading indicator is added to the application. The performances decrease. In OpenLayers version or on mobile devices this issue is more visible.  

This is probably caused by an event-bombing from that cause the high-rate invocation of the reconciliation algorithm.

**Comment by offtherailz** [comment]
OpenLayer problem has been resolved, still to solve the general problem of whole re-rendering.

**Comment by mbarto** [comment]
Whole rerendering is not a problem per se. It is the way reacts works, it
rerenders the whole page in the most efficient way each time the state
changes. The question is: is it still slow? If yes we can optimize further.
If not, it is simply not worth.
Il 30/ott/2015 15:15, "Lorenzo Natali" <notifications@github.com> ha
scritto:

**Comment by offtherailz** [comment]
On mobile devices, the viewer is slower than the other examples without layer loading information (both for leaflet and OpenLayers).

**Comment by mbarto** [comment]
We can probably try to batch events so that only one action is sent for the
whole set of loading layers in one shot and also  end of loading events are
batched if they arrive in a short amount of time. Basically we can create a
queue of events that is flushed and transformed into an action only when
the queue is stable for x milliseconds. We need to change actions and
reducers to accept a list of events.

We can think if this can be done through a redux middleware.
Il 30/ott/2015 16:39, "Lorenzo Natali" <notifications@github.com> ha
scritto:
