### ISSUE TITLE
RulesDataGrid

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/MapStore2#2772]
### Description
Talbe of rules with filtering and drag & drop capabilities, custom style, adjustable size, row selection and pagination
mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/#/geofence-rules-manager)

*Expected Result*
The grid shows geofence rules, the rules should be loaded with virtual scroll, should be possible to filter the rules, to change rules position with drag&drop and to select the rules.

A spinning loader should be shown while loading rules.

**Comment by offtherailz** [comment]
Some notes
 - [ ] When you start dragging, a black row appears between two rows hovered, so I expect the rule goes in the middle of them, instead it goes 1 row upper then expected
 - [ ] The black row should be more visible and good looking (thicker and maybe dashed, gray instead of black)
 - [ ] In rule editor the layer's list is not paginated
