### ISSUE TITLE
Wrong position of arrows in Tutorial

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3156]
### Description
![2018-08-09 14_59_08-window](https://user-images.githubusercontent.com/19175505/43900346-dc8ee080-9be4-11e8-8e86-d96d29d4c827.png)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Chrome v68

*Steps to reproduce*

- open a map
- open Tutorial from burger menu

*Expected Result*

- Arrows should indicate the right highlighted component

*Current Result*

- Sometimes arrows are placed on wrong position

**Comment by tdipisa** [comment]
@baloola, please check first if there is a trivial solution for this.

**Comment by baloola** [comment]
The positioning issue is caused from the [react-joyride](https://github.com/gilbarbara/react-joyride) dependency. according to this thread [#issue](https://github.com/gilbarbara/react-joyride/issues/217), it's planned to be fixed in the future.
Meanwhile, I have tested a forked [repo](https://github.com/ddeath/react-joyride/tree/fixed-positioning-and-overlay) that proposes a fix for the positioning issue and it appear to fix the tutorial issue.
