### ISSUE TITLE
WFS Download outputFormats do not work if logged in with authkey

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3214]
### Description
Download from feature grid doesn't work if the user is logged in **and** the authkey authentication system is set to work with geoserver.

This is because of this issue, already identified by the `FIXME`.

https://github.com/geosolutions-it/MapStore2/blob/1cce9a0224edd95616a3aec2aa11fe45d22c658e/web/client/libs/ajax.js#L21-L24

The issue happens because the `addParameterToAxiosConfig` (called to inject authkey) removes all the parameters in the URL (as you can see at line 24). The parameters should be added to the params object, overriding the current one.
 
This causes the 2 parameters added [here](https://github.com/geosolutions-it/MapStore2/blob/1cce9a0224edd95616a3aec2aa11fe45d22c658e/web/client/epics/wfsdownload.js#L53) are not forwarded to the server. 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
any

*Steps to reproduce*

- Use an instance of MS with geoserver auth integration (e.g. c028)
- Login
- Open a map and then select a vector layer to open the feature grid
- Try to export data using the download tool
 - Export in a format (different from gml, that is the default). For instance csv or shape-zip

*Expected Result*
- You download the data and you can open the file depending on the format

*Current Result*
- The file is corrupted . It is a GML text file, but renamed with .zip or .csv or whatever extension. If you try to open the file with a text editor (changing the extension to .txt) you can see the xml.

**Comment by offtherailz** [comment]
Debugging I noticed this is caused by a wfs url wuth `?` at the end.
wfsdownload causes double `??` and so the issue that removes the params is in getUrlWithoutParameters, that splits skip params re-assignment. 
e.g.: `test/wfs??service=WFS&outputFormat=something` --> `test/wfs?` + `` (empty string) + `service=WFS&outputFormat=something`

The empty string is skipped here:

https://github.com/geosolutions-it/MapStore2/blob/22bbfe82be2db71cd622d27bed457ccd41bb1332/web/client/utils/ConfigUtils.js#L61-L71

going to fix it

**Comment by MV88** [comment]
If you need to test it locally (for c028 project) this will not work because of the proxy. In order to replicate it locally you also need to replicate the environment on production where more services are on the same host:
steps are:
- use cors and in localConfig add `, "http://sit.comune.bolzano.it/geoserver"`
- enter a map `Cartografia` and change search url of the layer `Aree modificate 2015` by dispatching this action 
```
{
  type: 'CHANGE_LAYER_PROPERTIES',
  layer: 'Ambiente:aree_mod_2014__70', newProperties: {
    search: {
      url: '/geoserver/wfs?',
      type: 'wfs'
    }}
}
```
enable cors plugin for chrome
![image](https://user-images.githubusercontent.com/11991428/46949975-778fb500-d083-11e8-8fb0-391a0eb11b5c.png)

then you can open the Feature grid and trying to download to replicate the bug.
