### ISSUE TITLE
WFSDownloadPlugin Epic logic fail when FeatureGrid Plugin is not loaded

### ISSUE THREAD

**Issue by ndufrane** [geosolutions-it/MapStore2#3290]
### Description
When using WFSDownloadPlugin TOC integration without using FeatureGrid plugin the following test https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/wfsdownload.js#L104
produce a bug.

StackTrace :  
Uncaught TypeError: Cannot read property 'virtualScroll' of undefined
    at SwitchMapSubscriber.eval [as project] (wfsdownload.js:152)

### In case of Bug (otherwise remove this paragraph)

*Steps to reproduce*

- Activate WFSDownload Plugin
- Activate TOC Plugin
- Configure TOC with "activateDownloadTool": true,
- ..
- Click export button produce an error.

*Expected Result*

- WFS query issued

*Current Result*

Uncaught TypeError: Cannot read property 'virtualScroll' of undefined
    at SwitchMapSubscriber.eval [as project] (wfsdownload.js:152)

### Other useful information (optional):

Replacing the line 
`const {virtualScroll= false} = (store.getState()).featuregrid;`
by
`const virtualScroll = store.getState().featuregrid ? true : false;`
solve the issue.

If the proposed modification is valid, i can make a pull request.

**Comment by offtherailz** [comment]
If I understood correctly you didn't included the "FeatureEditor" plugin in your plugins, Isn't it?
This may be the cause of the issue because in this case featuregrid reducer is not included and so that piece of state is undefined. 

In this case a correct replacement of 
```
const {virtualScroll= false} = (store.getState()).featuregrid;
```
that does the fix is something like : 
```
const  {virtualScroll= false} = store.getState().featuregrid || {};
```
 (see [this](https://wesbos.com/destructuring-default-values/) as reference)
This maintains the needed behiviour (get virtualScroll value from the state, when exist, or use false) and skips the issue when `featuregrid` piece of state is undefined.

You can send a solution like this, but a unit test should be present, if possible...

It is hard to write a unit test in epic like this one to do a pull request, so, if you want, I suggest to extract that function in a selector to put here [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/selectors/featuregrid.js) calling it `isVirtualScrollEnabled`, that is easier to test.

For instance something like

```
isVirtualScrollEnabled: (state) => state && state.featuregrid && state.featuregrid.virtualScroll
```
then in the epic replace your line with

```
const virtualScroll = isVirtualScrollEnabled(store.getState())
```

And put a unit test for the `isVirtualScrollEnabled` selector. This should be perfect.

**Comment by tdipisa** [comment]
Closed for inactivity.
