### ISSUE TITLE
After login on public map you can not save

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3385]
### Description
If you open an existing map and login, you can not see the "Save" button, only "Save as". This because `mapInfo` are not reloaded. 

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
any

*Steps to reproduce*

- Open a map
- login as owner or admin
- Open burger menu

*Expected Result*

- I have save button

*Current Result*

- save button is missing (only save as). If you refresh or go back and than open again the map, the save button disappears. 

### Other useful information (optional):
This issue is related to #1993 , probably the same cause ( `mapInfo` not reloaded ).

**Comment by gioscarda** [comment]
The problem seems does not seem to have been solved (both on DEV and QA).
I tried the following steps:
- open a map without login --> neither 'SAVE' nor 'SAVE AS' displayed
  ![image.png](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/78b051fc-8644-4d29-aa2f-453f2a073e09)
- login as admin --> only the 'SAVE AS' button displayed
  ![image.png](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/8bb012eb-9ddd-4027-b230-1574539403f6)
- refresh --> 'SAVE' and 'SAVE AS' buttons all visible
  ![image.png](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/15e37238-18f5-4302-8efc-cbbfc2d9b863)

**Comment by kappu72** [comment]
The request is thrown but the Save plugin selector isn't updated if the user is admin.
I'll check
