### ISSUE TITLE
Timeline - More feedbacks on user actions

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3443]
### Description
1 Many times the tool is not so responsive, especially when the range or the tick element are moved.

![timeline1](https://user-images.githubusercontent.com/1280027/51035333-fd030280-15a9-11e9-9f79-f768e79aa5e4.gif)

 The range element should respond to the mouse movement synchronously or the timeline should be blocked showing a loading gif to make the user aware that something happen.
 
2. Some time the tick element freeze without snapping:

![timeline2](https://user-images.githubusercontent.com/1280027/51035555-a6e28f00-15aa-11e9-8d48-1db315dd22c8.gif)

Generally speaking there should be instant feedback to user actions.

### Other useful information (optional):

**Comment by offtherailz** [comment]
1 - Responsiveness
It is not a performance issue. It is due to the snap requires to request to the remote service to guess the point where to snap to. We can improve it by blocking or masking (with a loading spinner) the timeline while the request is performed
2-  Range Dragging
I', afraid it can not be done without changing core library itself. We may improve user experience by changing the mouse icon. 
3 - It seems to be a bug. I'll try to replicate it and investigate more.

**Comment by tdipisa** [comment]
>> 1 - Responsiveness
It is not a performance issue. It is due to the snap requires to request to the remote service to guess the point where to snap to. We can improve it by blocking or masking (with a loading spinner) the timeline while the request is performed
2- Range Dragging
I', afraid it can not be done without changing core library itself. We may improve user experience by changing the mouse icon.
3 - It seems to be a bug. I'll try to replicate it and investigate more.

**Comment by offtherailz** [comment]
Moved range drag and drop issue to #3463
