### ISSUE TITLE
Widgets collapse/pin/hide functionalities

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#3531]
### Acceitance Criteria
- [x] The user must be able to collapse/expand widgets: one by one or all together, in a tray
- [x] The admin should be able to pin widget: a pinned widget can not be moved, resized or collapsed. A normal user can not pin/unpin widgets.
- [x] when MapStore is configured accordingly in `localConfig.json`, certain users should be able hide widgets. An hidden user is not visible to other users. 
 - [x] All the properties and the visibility of these tools should be configurable by user role. 
 - [x] User should also be able to add images to the text widget content

**Comment by gioscarda** [comment]
A note on the "**collapse all**" functionality with **hidden widgets**.

From the Admin point of view (or other roles which can view hidden widgets), the problem is that if you hide some widgets the "collapse all" function collapses all the widgets, including the hidden ones.
In the widgets tray, hidden widgets are not manageable so you can't unhide them singly.
The only thing you can do to retrieve your hidden widgets is to use the "expand all widgets" function.

Moreover if you collapse all the widgets, except the hidden ones, the tooltip on the button is correctly 'Expand all widgets' but it collapses the hidden widgets.

![widgets_collapse_hidden](https://user-images.githubusercontent.com/43670920/54019998-fd281480-418c-11e9-884a-b14ac56f451a.gif)
