### ISSUE TITLE
Feature Grid is not working with layers in it.geosolutions workspace

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3532]
### Description
Feature Grid is not working with layers in **it.geosolutions** GeoServer workspace: all the records remain empty and the toolbar disabled.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Steps to reproduce*

- Open a map in MS 
- Load a layer with the mentioned workspace
- Open the Feature Grid

*Expected Result*

- The Feature Grid correclty load the content

*Current Result*

- The Feature Grid does not load the content correctly

**Comment by offtherailz** [comment]
I had a similar problem. 
I solved it setting off **strict CITE compliance** checkbox in the WFS page of GeoServer Services configurations. 

This is because MapStore uses by default WFS 1.1.0 with startIndex/maxFeatures. This is not strict compliant with WFS 1.1.0 (GeoServer supports it but the request in strict mode is invalid).

**Comment by tdipisa** [comment]
@offtherailz I think this has been already fixed by #3578. Can we close?

**Comment by offtherailz** [comment]
Yes I confirm.  I'm going to open another issue about my comment to document in troubleshooting the strict compliance problem.

**Comment by offtherailz** [comment]
Closed with #3578
