### ISSUE TITLE
Collapsed icons of widgets change order in Widgets Bar

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#3549]
### Description
![widgets_order](https://user-images.githubusercontent.com/19175505/53017033-5f73dc00-344f-11e9-8af8-9ae10e2b93b8.gif)

depends on geosolutions-it/MapStore2#3531

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- all

*Steps to reproduce*

- use following [map configuration](https://github.com/geosolutions-it/MapStore2/files/2880065/collapsed_widgets.txt) as new.json
- open the map #/viewer/openlayers/new
- save the map to geostore and refresh the page
- click on expand all widgets button (see GIF in the description)
- select the first icon on the right (sheet icon)

*Expected Result*

- sheet icon is still in its position

*Current Result*

- sheet icon shifts on the right

**Comment by offtherailz** [comment]
I : 

- saved the attached txt in new.json
- open http://localhost:8081/?#/viewer/openlayers/new
- click on expand and then on the first icon

Nothing happened: 

![i_3549_cannot](https://user-images.githubusercontent.com/1279510/53801405-5d297b80-3f3f-11e9-9104-f5e9ac7c7a7f.gif)
@allyoucanmap, Is there any other passage I should do?

**Comment by allyoucanmap** [comment]
@offtherailz  updated steps in description

**Comment by offtherailz** [comment]
Ok, I found out how to replicate and the cause of this issue:
 - loading new.json cause a trigger of CHANGE_LAYOUT action, so the `widgets.....layout` section is updated with current layout (saved in `layouts` object, that contain one layout for every screen size configured). 
 - Getting the widgets from the map instead do not trigger the CHANGE_LAYOUT, probably because of some difference in mounting/property change sequence due to the network lag, so the initial order does not take into account the current layout, that is not saved in the application state (even if correctly managed by react-grid-layout getting from layouts the right one). Moving one widget or collapsing a widget will trigger CHANGE_LAYOUT, restoring the correct application state. 

It should be enough to find out why it is not triggered and fix the issue, or force trigger of CHANGE_LAYOUT.

**Comment by tdipisa** [comment]
No longer an issue, fixed il latest releases.
