### ISSUE TITLE
Bug with attribute filter in Feature Grid

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#3778]
### Description
There is a bug in the OGC filter composition: the column filter goes in AND with the Query Panel attribute filter and not with all the entire filter defined in it.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [X] Internet Explorer
- [X] Chrome
- [X] Firefox
- [X] Safari

*Steps to reproduce*

- Open this [map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/4093)
- Select the 'USA Population' layer and open the Feature Grid
- Open the Query Panel and filter as reported below:

![issue_attr](https://user-images.githubusercontent.com/1280027/58084108-937bac00-7bba-11e9-9775-59eeb4d21bb1.jpg)

- Go into the STATE_FIPS colum and type something to filter (i.e. '04')

*Expected Result*

- The grid is filtered accodingly (i.e. showing only the "Arizona" state) 

*Current Result*

- The grid is empty

**Comment by kappu72** [comment]
Minutes  of the call with Simone.
When a user opens the advanced filter panel with  column filters set a warning is shown to alert the user that column filters will be deleted.
Otherwise when a user sets a column filter and an advanced filter is present the filters fields will be composed with  logic operator AND
