### ISSUE TITLE
Enhancement - Automatically launch the info panel for the location found by the search result

### ISSUE THREAD

**Issue by pgssimon** [geosolutions-it/MapStore2#3814]
### Description
Automatically launch the info panel for the location found by the search result.
* Configured with a simple checkbox "launch info panel" for each search in Configure search services.

**Comment by tdipisa** [comment]
Dear @pgssimon, can you please clarify a bit more the points below?

1 - You are talking about the [Configure Search Services](https://mapstore.readthedocs.io/en/latest/user-guide/menu-bar/#custom-wfs-searches) utility so I assume that your intention is to configure one or more custom search services (based on WFS) and enable the **_launch info panel_** option only on results involving them

2 - When the user click on a search result in the provided list, do you want to open the Info tool with only the details related to that search result in it? Since in that case a WFS request is performed, we are able to show the result of the selected feature in the Info panel instead of triggering a standard GetFeatureInfo request on a generic point belonging to the retrieved geometry: this may produce a non-significant result.

3 - If you need to use the selected search result to perform a standard GetFeatureinfo request instead (as usually happens when the user click on the map) you have to consider that we will need to select a generic point belonging to the retrieved feature geometry and use it for the GetFeatureInfo request. In that case:

- Only active layers in the map will be used for the request and results visible in the Info panel accordingly
-  If many layers are active in the map, the Info panel will report all the involved results for all the active layers as usual.
- Since we will use a generic point of the geometry retrieved by the search result, this geometry can easily correspond to a non-significant location

**Comment by pgssimon** [comment]
@tdipisa I can see situations where both options could be used....

1.  Option 1 - As for your point 1 above, custom search services (based on WFS) enables the launch info panel option only on results involving them

2.  Option 2 - Selected search result performs a standard GetFeatureinfo request

Ideally a configuration option like pictured below to allow either option (as well as the current option of not launching the info panel)...

![3814_Example_search_config](https://user-images.githubusercontent.com/40550145/60474912-cc826280-9cc8-11e9-9b11-c1cf5119c85d.png)

A generic point would be fine when performing a standard GetFeatureinfo request - I am assuming this would be for situations like this...

![3814_Non_Centroid_result](https://user-images.githubusercontent.com/40550145/60475230-7d3d3180-9cca-11e9-82dd-e9da47daeb1c.png)

**Comment by gioscarda** [comment]
@MV88 the DEV guide does not seem to have been updated. Is it needed?
