### ISSUE TITLE
Switching CRS, circle annotations change size

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3842]
### Description
When switching CRS using the CRS selector, **circle annotations** (if present) change their size.

![CRS_switching.gif](https://images.zenhubusercontent.com/5cda9c3818690954352b7b76/85b6b979-f4b2-424a-b0a5-4228e035bfd1)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

Last

*Steps to reproduce*

- Open a map
- Add some layer
- Add a circle annotation
- switch CRS through the CRS selector

*Expected Result*

The circle annotation doesn't change size.

*Current Result*

The circle annotation changes size.

**Comment by MV88** [comment]
So after a quick investigation i found out the problem is related to the radius that needs also to be updated and [has to be in the units of the crs](https://openlayers.org/en/v4.6.5/apidoc/ol.geom.Circle.html). in particular when it transforms the polygon in circle [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/DrawSupportUtils.jsx#L68)

a possible solution:
When it switches the crs all the circles in annotations should convert radius value in properties

**Comment by francoperversi** [comment]
@tdipisa is normal that the circle doesn't follow the deformation due to Projection changing?

![Cerchio](https://user-images.githubusercontent.com/54808782/64270789-6621f680-cf3c-11e9-8d73-8a9f0e136070.gif)

**Comment by francoperversi** [comment]
@vlt1 please add the projection possibility on circe annotation

**Comment by vlt1** [comment]
Circles added in one projection would become ellipses in another one. Is that the desired behaviour?

**Comment by offtherailz** [comment]
Correct @vlt1, that's the desired behavior. If I draw a circle in a projection and I change projection, I want the circle to be re-projected in that CRS.

**Comment by tdipisa** [comment]
@vlt1 after an internal discussion, we have decided to ignore at the moment the last three comments for this issue. The discussion will be moved to another issue. I'm going to close then PR #4167 for the moment until we have decided how to proceed.
