### ISSUE TITLE
Dashboard list does not update after save

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3914]
### Description
After saving a new dashboard with an empty map, if you go beck to hte home via the home button
you do not see the just added dashboard

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- all (not browser related)

*Steps to reproduce*

- login as admin
- start creating a new dashboard:
 - select map
 - select empty map
 - save the map
 - save the dashboard
- go home

*Expected Result*

- to see the new dashboard added

*Current Result*

- you see the old list of dashboards

**Comment by offtherailz** [comment]
I should proceed like this: 
Check if current production version has the bug. 
- If the bug was not present, take a look to recent chenges on that components/plugin ([this](https://github.com/geosolutions-it/MapStore2/pull/3733) PR might be one candidate).
 - if the bug is not present in production it could be a bug introduced in a previous version OR a bug that always existed. Try to find out some code, in the component or the epics involved, that tries to refresh the dashboards list. 
    - If there is something (e.g. some on mount or some epic), find out why it doesn't work
    - If there is nothing, maybe you may need to implement something
