### ISSUE TITLE
unable to find valid certification path

### ISSUE THREAD

**Issue by snuffer82** [geosolutions-it/MapStore2#3919]
Hi,
I have a problem with opening the attribute table in https.
I have debian, apache tomcat 9, geoserver, mapstore2.
If I connect via http://ip:port/mapstore I have no problem (with wms from geoserver).
If I connect in https://domain/mapstore I see everything correctly but it doesn't load the attribute table (but I can view feature info from map ).

In the apache configuration I have:
   `SSLProxyEngine on
         
    ProxyPass         /geoserver  https://domain:8443/geoserver

    ProxyPassReverse  /geoserver  https://domain:8443/geoserver

    ProxyPass         /mapstore  https:/domain:8443/mapstore

    ProxyPassReverse  /mapstore  https://domain:8443/mapstore`

From catalina.out logs:
`07-Jul-2019 17:44:50.633 SEVERE [https-jsse-nio-8443-exec-5] it.geosolutions.httpproxy.HTTPProxy.executeProxyRequest Error executing HTTP method
 javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

Do you have any suggestions? thanks a lot
paolo

**Comment by mbarto** [comment]
Hi Paolo,
could you please use the mailing list for these kind of questions in the future?

I presume you have a self-signed certificate for geoserver. In this case, you need to install the certificate in the JVM where you run MapStore, so that MapStore proxy can work with your GeoServer through https (some docs here: https://docs.oracle.com/cd/E79792_01/resa/pdf/160/html/security_guide/apps-chapter%207.htm)

**Comment by snuffer82** [comment]
thanks, 
I have installed the certificate following this post:
 [http://www.littlebigextra.com/how-to-fix-pkix-path-building-failed-sun-security-provider-certpath-suncertpathbuilderexception/](url)
now everything works fine!
thanks a lot
