### ISSUE TITLE
Tutorial suddenly ends if cannot select next steps

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#3925]
### Description
Tutorial stops after the full screen step by clicking forward
![image](https://user-images.githubusercontent.com/11991428/60881511-2c878480-a246-11e9-9468-d3bc7ffdff9e.png)

see [comment](https://github.com/geosolutions-it/MapStore2/issues/3925#issuecomment-510812038)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Indicate the browser version in which the issue has been found

*Steps to reproduce*

- open any map
- click on tutorial from burger menu
- con on "forward" on the various steps til lreaching full-screen

*Expected Result*

- to have a coherent behaviour.

for this i can see two solutions
solution1: restore GFI step (maybe by expanding and then collapsing the map toolbar)
solution2: change the label of step full screen from "forward" to "end"

*Current Result*

- Describe here the current behavior

**Comment by allyoucanmap** [comment]
This behaviour is due to missing DOM with selectors used in the next steps.
If you click on next and all the following steps are missing the Tutorial ends without displaying the right button in the latest step.
I propose a different solution, we could add a last step that will be always in the page (eg: selecting the #container) with a generic message 'Tutorial completed' or following the `solution1` we could fix current steps of tutorial

**Comment by ElenaGallo** [comment]
This issue is no longer valid, it can be closed.
