### ISSUE TITLE
When configuring the widget data, the 'Color' combo box shows wrong labels

### ISSUE THREAD

**Issue by gioscarda** [geosolutions-it/MapStore2#3928]
### Description
When creating new (chart) widgets, the 'Color' ('Color Ramp' in case of Pie Chart) combo box of the 'Configure data' panel shows wrong labels (see the picture).

![Menu_002](https://user-images.githubusercontent.com/43670920/60902852-9c126980-a270-11e9-8793-c579ec214321.png)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

- All

*Steps to reproduce*

- open a map with vector layers
- open the TOC and select a vector layer
- click on 'Create widget for the selected layer'
- choose Chart widgets >> Bar/Line/Pie Chart
- see the 'Color'/'Color Ramp' combo box values

*Expected Result*

- The combo box shows readable values

*Current Result*

- The combo box shows values like this `global.colors.global.colors.blue`

### Other useful information (optional):

Thematic layers should be tested also.

**Comment by MV88** [comment]
in [this](https://github.com/geosolutions-it/MapStore2/pull/3900/files#diff-246e1b22351f0942dcf5de24ad9526f1R16) PR i  was adding the "global.colors." to the ramp color because the name was coming with only red, green etc, for the thematic layer. 
with the widgets instead i suppose it comes with the full path "global.colors.red", so bv adding again the "global.colors" creates a problem.

try to understand why:
- in one case it comes with the prefix (widgets)
- in the other case it comes without (ThematicLayer)
