### ISSUE TITLE
Update ESLint

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4148]
### Description
Current ESLint version is very old. We should update to newer version (after we migrate to React 16.x), so that we can take advantage of new syntax introduced recently (e.g. dynamic imports, react fragments).
The work is boring, because with newer versions a lot of new warnings will appear, and we will need to reformat / fix our code to satisfy them. Also a review of the current rules will be needed.

**Comment by MV88** [comment]
"The work is boring" true.
I tried two or three months ago the migration and can confirm that there are a lot of breaking changes.
Some options are deprecated in favor of others and also the syntax is changes (as far as i remember).
I think we will need to change some of the current current behaviours due to incompatibility.

A side note: this will also fix a vulnerability issue. see more [here](https://github.com/geosolutions-it/MapStore2/network/alert/package.json/eslint/open)
