### ISSUE TITLE
Improve ScaleBox plugin documentation

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#4450]
### Description
Add how to customize scales in ScaleBox and consequences

### Other useful information (optional):
The Dev guide section to update is: https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/

**Comment by offtherailz** [comment]
If you try the procedure here: 
https://github.com/geosolutions-it/MapStore2/issues/2608

This works, and also OSM background seem to be scaled accordingly by Openlayers. Still to verify other layer types (backgrounds, WMTS ...) and leaflet.

Pay attention, in this case changing projection is seems to use the same resolutions, that is a little weird. This because the two features (CRS Selector and resolution customization) were developed independently. By default the resolutions switching projection are calculated automatically, following the same rules of default's GWC algorithm. They can be customized manually in this way.

Generally speaking, resolutions (or scales) are a configuration of the map.
It's is possible to customize resolutions for a single map by editing it's configuration manually, and it will work in only in it's reference system.

**Comment by tdipisa** [comment]
In MS configuration you can customize scales by providing custom resolutions values inside the map configuration, below an example (we are improving our doc for this too):

```
{
	"map": {
		"projection": "EPSG:3857",
		"units": "m",
		"center": {"x": 1560000.000000, "y": 6000000.000000, "crs": "EPSG:3857"},
    "zoom":7,
    "mapOptions": {
      "view": {
        "resolutions": [
          84666.66666666688,
          42333.33333333344,
          21166.66666666672,
          10583.33333333336,
          5291.66666666668,
          2645.83333333334,
          1322.91666666667,
          661.458333333335000,
          529.166666666668000,
          396.875000000001000,
          264.583333333334000,
          132.291666666667000,
          66.145833333333500,
          39.687500000000100,
          26.458333333333400,
          13.229166666666700,
          6.614583333333350,
          3.968750000000010,
          2.645833333333340,
          1.322916666666670,
          0.661458333333335
        ]
      }
    },
		"maxExtent": [
			-20037508.34, -20037508.34,
			20037508.34, 20037508.34
		],
```


This is what at the moment we can do in MS and, as you can see, custom resolutions values are global now and they are valid for one single CRS: if you need to manage multiple CRSs in the same map this configuration should not be used.
