### ISSUE TITLE
Change language problems

### ISSUE THREAD

**Issue by francoxyz** [geosolutions-it/MapStore2#4570]
### Description

If the user make some changes (for example add something to the viewer) and change the language, the changes are not mantained. This problematic behaviour happens for:

- Dashboards
- Stories
- Application contexts 

An example:

![saving](https://user-images.githubusercontent.com/54808782/69717993-7b5a8b80-110d-11ea-9fcd-3ff2468a52fb.gif)

In order to fix this issue, see as example what happens when you make some changes and after you change language in maps (correct behaviour). In this case the changes are mantained

![savingok](https://user-images.githubusercontent.com/54808782/69718203-0fc4ee00-110e-11ea-9b3d-7fc55bbcca7e.gif)

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [X] Chrome
- [ ] Firefox
- [ ] Safari

*Browser Version Affected*

- Not brower related

*Steps to reproduce*

- Open a dashboard/story/app contexts
- Make some changes
- Change the language 

*Expected Result*

- The changes are mantained

*Current Result*

- The changes are not mantained

**Comment by francoperversi** [comment]
@offtherailz the following issue were noticed:

- [ ] The problem is still present creating a new dashboard and sometimes editing an existing one

- [ ] The problem is still present also in application contexts

- [ ] For stories and dashboard as soon as you change language the page scroll to the top

**Comment by offtherailz** [comment]
I was able to replicate the problem only on new dashboard.
This is because of re-mount of the whole components to update the labels causes a reset dashboard action. 

But... 

I think this is a minor "bug", and fixing it means to risk to change the normal workflow of page switching and potentially introducing bugs. 

In addition **99% of sites in the world reload the whole page when you change language**.

So, instead of trying to do what **no-one does** for **no-reason in particular** fixing a thing that **no-one asked**, I should propose an alternative solution: 

When language switch a confirm window will appear, explaining that all the not-saved information will be lost.
please @tdipisa I want your opinion about this.

**Comment by tdipisa** [comment]
@offtherailz @francoperversi, I would like to avoid undetermined behaviors and on the fly modifications at this stage just for this small issue that can generate other unforeseen bugs. Therefore I'm asking to revert the @offtherailz PR if possible and move this issue to the next milestone to be properly planned and investigated (I've updated labels).

**Comment by offtherailz** [comment]
Here my revert PR https://github.com/geosolutions-it/MapStore2/pull/4596

**Comment by tdipisa** [comment]
closed for inactivity
