### ISSUE TITLE
Add icons for add geostory, edit map, preview and webpage section

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#4640]
### Description
- [x] ~~expand all~~  `not needed`
- [x] ~~collapse all~~ `not needed`
- [x] ~~expand single item~~ `not needed`
- [x] ~~collapse single item~~ `not needed`
- [x] add geostory
- [x] inline map edit
- [x] preview icon
- [x] webpage content

**Comment by ElenaGallo** [comment]
@allyoucanmap @tdipisa I noticed that the icons of Paragraph Section, Media Section and Web Page Section are the same on the  'edit story' modal.  
Are to be changed?
![test40](https://user-images.githubusercontent.com/56537133/70922106-d05f3280-2025-11ea-9592-e9a11998fc34.JPG)

**Comment by tdipisa** [comment]
@ElenaGallo yes because the same type of section is used here to host Media, Paragraphs and Web Page contents. For the moment we are ok with this.

We have just noticed that the WebPage content creation is not available after an immersive section, this must be reported notifying @kboczkowski-clurgo and the issue moved back in ready for a fix.
