### ISSUE TITLE
First version of user extensions

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#4720]
Create a minimal version of user extensions plugins (see [mockup](https://demo.geo-solutions.it/mockups/mapstore2/georchestra-templates-extensions/#/)) to try and refine.

**Comment by ElenaGallo** [comment]
@offtherailz  an observation:
The User Extensions plugin must always be enabled at startup otherwise it is not possible to use the command to enable/disable the other plugins.

**How to reproduce**
- new context

at the second step:
- add annotation plugin 
- enable plugin for user
- add UserExtencions
- enable plugin for user
![issue20](https://user-images.githubusercontent.com/56537133/72739754-9ba24600-3ba4-11ea-8c18-cc86affee922.JPG)
- save
- open the context

*Current Result*
the user cannot enable the annotations plugin

**Comment by tdipisa** [comment]
@offtherailz the ** User Extensions ** plugin must be hidden in this step of the wizard and must be automatically included as soon as the administrator has set up an extension for it to appear in the Extensions Library to be activated by the end user.

**Comment by francoperversi** [comment]
Last comment above are included in the new review list [here](https://github.com/geosolutions-it/MapStore2/issues/4774#issuecomment-579146181). Closing
