### ISSUE TITLE
Application Context Templates

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4746]
### Description
[mapstore2-georchestra/#130](https://github.com/georchestra/mapstore2-georchestra/issues/130)
[mapstore2-georchestra/#131](https://github.com/georchestra/mapstore2-georchestra/issues/131)

**Comment by francoperversi** [comment]
It seems that some translations need to be improved. In particular:

![trans_en](https://user-images.githubusercontent.com/54808782/73189823-51314400-4125-11ea-9fee-b5de4c48e07d.jpg)

That, for example, in italian and in franch is translated as:

![trans_ita](https://user-images.githubusercontent.com/54808782/73189832-555d6180-4125-11ea-9fe3-34e49e800ba1.jpg)
![trans_fr](https://user-images.githubusercontent.com/54808782/73189875-66a66e00-4125-11ea-82db-fc519006b2d0.jpg)

A possible solution could be:
- `Filter templates by name...` (same as `Filter plugins by name...` in plugins window) instead of `Filter templates...`
- `All available templates are enabled` instead of `Enabled all available templates`

**Comment by francoperversi** [comment]
@vlt @tdipisa I found the following:
- Translations described in previous comment still need to be fixed
- If you insert as name of the template the name of another resource (Map, Dashboard, Story or Context) the warning message appears in background, below the semi-transparent area

![wrn_mss](https://user-images.githubusercontent.com/54808782/74353455-395eee80-4dba-11ea-93d3-43c0bd5abfba.jpg)

- The default "Upload Map Template" window height should be a little resize in order to avid the scrollbar to appears

![scr](https://user-images.githubusercontent.com/54808782/74353631-7c20c680-4dba-11ea-9fac-eeca8a8664c5.jpg)

**Comment by tdipisa** [comment]
@francoperversi please open an new issue in georchestra for the above and put it in Phase 3 milestone

**Comment by francoperversi** [comment]
Problems related to previous comment were better described in [another issue](https://github.com/georchestra/mapstore2-georchestra/issues/164) (geOrchestra kanban)
