### ISSUE TITLE
Ability to save resource with thumbnail not allowed

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4758]
## Description

When the thumbnail with size (over 500Kb) or extensions (.gif) not allowed is added on save window, the warning message is displayed but the resource is saved anyway.
![issue56](https://user-images.githubusercontent.com/56537133/72820359-1fc10000-3c6f-11ea-8549-aa8a11f2c8bd.gif)

## How to reproduce

- click on new map
- click on save
- change the thumbnail with  over 500Kb or a .gif
- click on save
- go back to the homepage 
- search the map

*Expected Result*

The map cannot be saved if the thumbnail is not supported and the relative warning message appears

*Current Result*

The map is saved anyway and it is present on the homepage without any thumbnail

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
An updated status for this issue is described below.

## Description

If you save a map changing a thumbnail with a size over than the max allowed one (500kb) the map is saved anyway with a wrong thumbnail state.

## How to reproduce

-  Follow the steps in the animated gif 

*Expected Result*

The same bheavior of changing the thumbnail in home page should be respected 

*Current Result*

The thumbnail is in a wrong state, look at the animated gif. After saving the map the first time and reopening the map properties, the thumbnail is not changed in the UI. But, If I refresh the map and then I reopen the map properties the thumbnail is in a wrong state (it looks gray). If now I go back in the home page and I search for the map the thumbnail is in the same wrong state.

**Comment by ElenaGallo** [comment]
Now after a thumbnail of wrong size (over the 500 kb) is edded there are two different behaviors:

1)  for the map, after saving the thumbnail with an oversize image, from the homepage, the thumbnail is empty
![thmb from home2](https://user-images.githubusercontent.com/56537133/91162561-89553100-e6cc-11ea-889d-2c35e692dabc.gif)

2) for dashboard, story and map (only from the map viewer) saving the thumbnail with a oversize image the thumbnail remains the old one 
![thmb from viewer2](https://user-images.githubusercontent.com/56537133/91162573-8d814e80-e6cc-11ea-9c0a-57a4087a7d6b.gif)

@tdipisa which of the two is the one to keep?

**Comment by tdipisa** [comment]
@ElenaGallo in my opinion it should be the second one. @offtherailz what do you think?
