### ISSUE TITLE
Widgets tool is no longer available for TOC in DEV

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#4772]
## Description

The widgets tool is no longer available in TOC toolbar after selecting a layer.

## How to reproduce

- Open this [map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10254)
- Open the TOC and select the layer

*Expected Result*

The widget tool appears in TOC toolbar and can be used

![image](https://user-images.githubusercontent.com/1280027/72886828-d1613f00-3d0a-11ea-916f-63a71e57709f.png)

*Current Result*

The widget tool is not available in the toolbar

![image](https://user-images.githubusercontent.com/1280027/72886883-ec33b380-3d0a-11ea-85fb-ae25981f4e4a.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

This is a regression, in QA the issue does not exists.

**Comment by offtherailz** [comment]
Noticed the same yesterday during PR review.
Here my report:

Probably due to recent changes to this line:
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/TOC/Toolbar.jsx#L285

Maybe this commit:
https://github.com/geosolutions-it/MapStore2/commit/9db5b7266f24f0b6d70aa6d1302a45ca31440c8e
The button is not present to create new widgets

I noticed today that also @vlt1 reported the same information in comments for #4856

**Comment by tdipisa** [comment]
closed with #4856
