### ISSUE TITLE
Map -  Timeline tool problem

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#4878]
## Description

 Going back in time, in the timeline tool, the next step is not displayed immediately
![timeline](https://user-images.githubusercontent.com/56537133/74163016-041f9880-4c22-11ea-94ff-110749cd89ba.gif)

## How to reproduce

-  Open this [map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/21164)
-  Click on Step backward

*Expected Result*

The next step is displayed immediately

*Current Result*

There is a moment in which the previous step and an empty space appears  before the next step is displayed

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
This issue is very much related to https://github.com/geosolutions-it/MapStore2/issues/3871. Openlayer WMS cache glitch with updateParams. 

Could we fetch WMS layer with dimension as singleTile? As the blink issue due to source refresh, doesn't occur anymore or at least the issue reported seems to be fixed. But need some insight and recommendation on this approach or an alternate suggestion.

**Comment by tdipisa** [comment]
@dsuren1 you are right. The reason of this issue is properly explained by @offtherailz in #3871 (I think we can close this issue in favor of the old one that provides a better explanation of the problem, I will refer anyway this issue).  It would be good if you can spend some time to do an investigation and see if we can prevent the OL cache issue in a better way.

**Comment by tdipisa** [comment]
Closing in favor of #3871
