### ISSUE TITLE
Complete Openlayers WMTS usage of TileMatrixSet info

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#4922]
## Description

We don't use the following:
 * matrix width and height (to be used instead of layer extent)
 * tile width and height (to be used instead of static configured tile size)

**Comment by francoperversi** [comment]
@mbarto testing this issue I notice that adding almost all the layers (except precip30min) from WMTS service in catalog, an error in MS occours:

![error](https://user-images.githubusercontent.com/54808782/75162930-9f366900-571e-11ea-8665-08648d90ff35.jpg)

In console, adding those layers, it seems that the problem is related to the text/xml files:

![error2](https://user-images.githubusercontent.com/54808782/75163172-1409a300-571f-11ea-8b5a-c996e39bcce5.JPG)

**Comment by mbarto** [comment]
@francoperversi ok, I will do some testing, we probably need to set extent for layers when that is possible to prevent loading tiles out of the layer extent

**Comment by mbarto** [comment]
@francoperversi There is a new PR to fix this
