### ISSUE TITLE
Fix loading gear and the counter style

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#5110]
## Description

Problem on the counter bar when scrolling down the map in map widget
![dash1](https://user-images.githubusercontent.com/56537133/78162606-67ba8b00-7447-11ea-94bd-7f9c6b4ff475.gif)

## How to reproduce

- Open a new dashboard
- Click on Map Widget or Chart widget
- Open a context with mapcatalog plugin, e.g. http://localhost:8081/#/context/mapcatalog (http://dev.mapstore.geo-solutions.it/mapstore/#/context/mapcatalog)
- look at the footer while loading results

*Expected Result*

Please align the loader to the right, and proper center vertically both the text and the loader, with a little margin from the border.
The height of the footer should not change when loader appears.

Sample : 
![image](https://user-images.githubusercontent.com/1279510/112489175-7b5cb100-8d7e-11eb-8fed-6c858e16e7f0.png)

*Current Result*

The loading gear is not aligned whit the counter and the footer changes it's height.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MuhweziDeo** [comment]
Hey, @offtherailz I found this CSS style here https://github.com/geosolutions-it/MapStore2/blob/master/web/client/themes/default/less/loaders.less#L50 is causing the misalignment with the spinner. I found that replacing it with this style `margin: 8px 8px 0px 8px` will fix the issue else we would have to override the styles for the `<LoadingSpinner style={{margin: 8px 8px 0px 8px`}}/>` in the component to resolve it. Which would you be better since the last changes were made by you. : )

**Comment by offtherailz** [comment]
Hi @MuhweziDeo . I don't know exacly what you found. Probably you misunderstood the issue because it is not properly the same. I think you refer to the graphical glitch when loading spinner appear, anyway your fix doesn't seem to have a real benefit on it. 
I see that 
 - [ ] first of all the bug is not anymore in the form reported, Instead I see something like this below, loading all the maps until the end, without any scroll from the user. The number is updating.
![Peek 18-03-2021 12-10](https://user-images.githubusercontent.com/1279510/111617399-577bf700-87e3-11eb-994a-26a02b70dc2e.gif)
 - [ ] I tryed to apply your fix to `components/maps/MapCatalog.jsx` but it dosn't fix the problem and removing the loading spinner doesn't remove the problem too. 

I think that the problem is similar to the one in the one in the other scroll issue. The only thing more difficult is that the map catalog is used in two different points. MapCatalog plugin (you can create a context like [this](http://localhost:8081/#/context/mapcatalog) and in widgets selector. So you have 2 different scroll spy options. Doing some tests looks like the version here in widget builder need a different scroll options, while the one in the plugin needs the previous option. So I modified the scroll options only of this one. 
this time has an empty map at the beginning so it has a customization.
```diff
diff --git a/web/client/components/maps/enhancers/enhancers.js b/web/client/components/maps/enhancers/enhancers.js
index 50d65f9f9..8412409f7 100644
--- a/web/client/components/maps/enhancers/enhancers.js
+++ b/web/client/components/maps/enhancers/enhancers.js
@@ -53,7 +53,7 @@ const loadPage = ({ text = "*", options = {} }, page = 0) => getResources({
         items: [],
         total: 0
     }));
-const scrollSpyOptions = { querySelector: ".ms2-border-layout-body", pageSize: PAGE_SIZE };
+const scrollSpyOptions = { querySelector: ".ms2-border-layout-body .ms2-border-layout-content", pageSize: PAGE_SIZE };
 
 /**
  * transforms loadPage to add the empty map item on top
@@ -102,7 +102,7 @@ export const withEmptyMapVirtualScrollProperties = ({ loadPage: lp, scrollSpyOpt
  * To remove the the empty map you should use simply withVirtualScroll instead of `withEmptyVirtualScrollProperties` transformation and withProps enhancer
  */
 export const withEmptyMapVirtualScroll = compose(
-    withVirtualScrollEnhancer(withEmptyMapVirtualScrollProperties({ loadPage: loadPage, scrollSpyOptions, hasMore: ({ total, items = [] } = {}) => total > items.length })),
+    withVirtualScrollEnhancer(withEmptyMapVirtualScrollProperties({ loadPage: loadPage, scrollSpyOptions: { ...scrollSpyOptions, querySelector: ".ms2-border-layout-body .ms2-border-layout-content"}, hasMore: ({ total, items = [] } = {}) => total > items.length })),
     withProps(({ items }) => ({ skip: items && items[0] && items[0].id === "EMPTY_MAP" ? 1 : 0}))
 );
 ```

About the layout of the footer, we can do a separate issue, because we should uniform look and feel of this footer with the others, like MapCatalog plugin and layer catalog.

Please test this fix and do a PR, if you don't have other questions

**Comment by tdipisa** [comment]
@MuhweziDeo @offtherailz just a side note for this. At the moment it is not possible to easily reproduce the issue in DEV because of #6635, but if you look at the loading spinner in the bottom bar during the first loading of the catalog list, you can see the problem.

![image](https://user-images.githubusercontent.com/1280027/111623738-0ff96900-87eb-11eb-9663-c9d7ca087459.png)

**Comment by offtherailz** [comment]
@tdipisa this is the problem about "layout of the footer" I mention in the comment.

**Comment by MuhweziDeo** [comment]
> ```diff
> querySelector: ".ms2-border-layout-body .ms2-border-layout-content"
> ```

Hey @offtherailz I tested this but it seems the map selector does not work with this fix

**Comment by offtherailz** [comment]
@ElenaGallo I changed this issue (the problems on the tools changed in the meanwhile) and I'll change also the #6635 in order to divide better the tasks. Please keep it into account for your tests.
