### ISSUE TITLE
Search Service - show GFI 

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#5386]
## Description

When searching for features there shall be a possibility to directly show the GFI for this feature.
Preferably there shall be a button available for each search result that zooms to the feature and directly opens the GFI.
Clicking the whole bar shall still have the same effect as it has right now.

The latest MapStore already has a similar functionality described in the [User Guide](https://mapstore.readthedocs.io/en/latest/user-guide/menu-bar/#custom-wfs-searches) (see **Launch Info Panel** configuration options). 

![image](https://user-images.githubusercontent.com/1280027/77440773-f9435080-6de8-11ea-941f-04eaf04395cc.png)

There are only some additional features to include as agreed during the meeting in November:

* When _Search layer_ is enabled in **Launch info panel**, two new checkboxes should be added:
  - **Use button to open feature info**: to add a button to each result in the list to explicitly open GFI for it  

![image](https://user-images.githubusercontent.com/1280027/77440982-3a3b6500-6de9-11ea-8107-58bea2d6262a.png)

  - **Force search layer visibility**:  the layer (if present in the map) will be made visible automatically to always perform GFI operation on it too

**Comment by MV88** [comment]
refers to [austrocontrol-C125/#169](https://github.com/geosolutions-it/austrocontrol-C125/issues/169)

**Comment by ElenaGallo** [comment]
@vlt1 By enabling only the "Use to open feature information", no GFI buttons appear on the result in the list.

*How to reproduce*
- Open [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/25924) map
- Search  'Wall St' on the searching bar

*Current Result*
no GFI buttons appears on the result in the list

**Comment by tdipisa** [comment]
@vlt1 this issue is still not working properly.

Please look at the steps described by @ElenaGallo in the above comment. The above description is not complete anyway, see also my comment below.

The GFI button should be showed when the option "Use button to open feature info" is enabled. In the map linked above this option is selected but the button doesn't appear: it appears only if both options are enabled. 

![image](https://user-images.githubusercontent.com/1280027/90253859-2351e980-de42-11ea-9e45-03c01e7ba081.png)

At the moment there is anyway confusion in the logic related to the two new checkboxes and associated functionalities. See the video below and check/compare again the requirements in the issue description. The implemented functinalities are not in line with the requirements and we have wrong behaviors.

![search_info](https://user-images.githubusercontent.com/1280027/90255062-074f4780-de44-11ea-83b8-01042c3abc1b.gif)

**Comment by vlt1** [comment]
@tdipisa The button is not present because the layer is invisible so GFI says no queryable layer hence the button is hidden. The layer must be active in order to perform GFI.

**Comment by tdipisa** [comment]
@vlt1 ok I understood, but the GFI operation should not be triggered at all after clicking on a search result in this case since the Identify button is missing. If the layer in map is hidden and the "Use button to open feature info" option activated, we should have a disabled Identify button instead of a missing one. In addition, now the GFI opeartion is performed also if you click on the whole result record instead of only by clicking on the Identify button. The requirements are enough clear for this point:

>Preferably there shall be a button available for each search result that zooms to the feature and directly opens the GFI.

If the related layer is hidden in TOC, the button should be present but disabled and hovering over that button a tooltip should appear to inform the user that the layer is hidden.

>Clicking the whole bar shall still have the same effect as it has right now.

This means that only by clicking on the Identify button the GFI operation must be performed along with the zoom, the feature highlight etc. If I click somewhere else in the result record only the usual zoom to + feature highlight is performed.

**Comment by ElenaGallo** [comment]
@vlt1 The tooltip that appears to inform the user that the layer is hidden (describe [here](https://github.com/geosolutions-it/MapStore2/issues/5386#issuecomment-688834085) ) appears only occasionally.
