### ISSUE TITLE
Upload shapefile should zoom on imported shapefile

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#546]
Currently when you import a shapefile if this is "out of screen" it's not immediately clear that the operation was succesful. We can either:
 * zoom automatically on shapefile extents
 * show an option to the user to zoom or not (The shapefile has been succesfully imported. Would you like to zoom on it (Yes/No) )

**Comment by MV88** [comment]
Hi mbarto, I'm taking care of this issue.

I suggest instead to put a checkbox with the label "Zoom on shapefile" or similar.
![image](https://cloud.githubusercontent.com/assets/11991428/16589404/4eeeb3c0-42d3-11e6-8ff0-cd04879c7240.png)
If the checkbox is checked, it will zoom into the shapefile otherwise no visible action will be called.

What do you think about it?
MV

**Comment by mbarto** [comment]
I agree, just I would check it by default.
