### ISSUE TITLE
Default hyperlinks color for stories

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5572]
## Description

Evaluate the possibility to set up a default color for hyperlinks in rich text editor components.
For the moment the color of an hyperlink can be set in the text editor only through the following tool that can be used for all texts in general.

![image](https://user-images.githubusercontent.com/1280027/89646783-b926cb00-d8bc-11ea-82d4-856877de0a1c.png)

We need to enhance the story settings to have the possibility to configure which color all hyperlinks in the story should have: obviously it will always be possible to customize the hyperlink color at rich text editor level using the tool showed in the image above.

The new item in the story setting should be the one illustrated in the image below.

![story_settings_3](https://user-images.githubusercontent.com/1280027/89647093-3eaa7b00-d8bd-11ea-8d70-130666414173.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by alperr** [comment]
Default hyperlink colors for rich text editor can be changed by changing
the related CSS rule.

Since we are using, `quill.js` with `snow` theme we can override the globally
registered CSS rule for an example color red like this to change the
default hyperlinks color.

`.ql-snow a{ color: red !important; }`

This CSS change will also do not intervene in manual color change on the editor.

@tdipisa Is this issue requires more work other than **evaluating**

If yes what color should I set the default color of hyperlinks

**Comment by tdipisa** [comment]
> Default hyperlink colors for rich text editor can be changed by changing
> the related CSS rule.
> 
> Since we are using, `quill.js` with `snow` theme we can override the globally
> registered CSS rule for an example color red like this to change the
> default hyperlinks color.
> 
> `.ql-snow a{ color: red !important; }`
> 
> This CSS change will also do not intervene in manual color change on the editor.
> 
> @tdipisa Is this issue requires more work other than **evaluating**
> 
> If yes what color should I set the default color of hyperlinks

I've updated the issue description some days ago to better define the requirements
