### ISSUE TITLE
Sync to map button state not retained when toggling editing on / off inside the featuregrid

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#5657]
## Description
On mapstore demo however I change the sync map button and activate editing it is always reverted to the default value (toggled) when I deactivate editing.

## How to reproduce
-  open the feature grid for a vector layer
- untoggle sync to map
- activate editing
- deactivate editing
- the button is reverted to default

*Expected Result*
The sync to map button state should be retained (and probably should also apply to the "editing mode", but as far as I can see it doesn't) when switching editing.

*Current Result*
The state od the sync button is reverted

![featuregird_editing](https://user-images.githubusercontent.com/571129/87653636-157f4a80-c756-11ea-917d-52ed9402e605.gif)

**Comment by AGMETEOR** [comment]
The issue is caused by one of the epics in `web/client/epics/featuregrid.js`. In particular [this one](https://github.com/geosolutions-it/MapStore2/blob/6b08484549a06ace962cbd628f86fa8f3455b153/web/client/epics/featuregrid.js#L329). 

This epic listens to the `TOGGLE MODE` event that's triggered when editing is activated. Two scenarios arise from this 
-  One similar to that observed on this issue where if `sync with map filter` is `off`, the it'll be eventually toggled on at the end of this epic by this line `action$.ofType(TOGGLE_MODE, CLOSE_FEATURE_GRID, LOCATION_CHANGE).take(1).flatMap(() => Rx.Observable.of(toggleSyncWms()))`
- In the case where the `sync with map filter` is instead `on` this line will toggle `Rx.Observable.of(...(isSyncWmsActive(store.getState()) ? [toggleSyncWms()] : [])),` and then it i'll eventually be toggled on again by the last line.

## Solution 1
--------
- Remove this epic
## Solution 2
--------
- Remove listening to `TOGGLE_MODE`in this line `action$.ofType(TOGGLE_MODE, CLOSE_FEATURE_GRID, LOCATION_CHANGE).take(1).flatMap(() => Rx.Observable.of(toggleSyncWms()))`
