### ISSUE TITLE
Highlight of annotation geometries

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#5985]
With this PR https://github.com/geosolutions-it/MapStore2/pull/5942 (for measurement annotations)
we loose the possibility to highlight geometries on map by clicking on a geometry in the annotation list in case the Coordinates tab is not available.

![image](https://user-images.githubusercontent.com/1280027/95445434-51920800-095f-11eb-985e-c6797e43fa0d.png)

We should improve the behavior by:

1. If the user hovers the mouse over a geometry in the list, the corresponding annotation is highlighted in the map. In case of coordinates tab available the annotation in map is highlighted also by clicking on the geometry itself

2. As soon as the style tab is activated (with or without the coordinates tab) the annotation corresponding to the selected geometry in the list loose the highlight in order to show the current style but, if the user hovers the mouse over another geometry in the list, the corresponding annotation(feature) is highlighted

**Comment by ElenaGallo** [comment]
@dsuren1 

- [ ] When you go back to the list from coordinate/style tab the selected gemetry does not return highlighted in the map.
![highlighted](https://user-images.githubusercontent.com/56537133/95963021-6ced8f00-0e07-11eb-9188-76a69324279d.gif)

*How to reproduce*
- Open a measurement annotation
- Hovers the mouse over a geometry in the list
- Select it
- Deselect it 

*Current result* 
The mouse is over a geometry in the list but the geometry is not highlighted on map

**Comment by dsuren1** [comment]
@ElenaGallo 
This is because a click event is already triggered on the card which took over the precedence of the mouseEnter event, which is the reason the highlight doesn't happen, as there can be only one event on a element at a time. After deselecting move away from that card and perform a hover on the same card should trigger the mouseEnter(hover) event, as this is the first event on the element and then the geometry will get highlighted.

**Comment by tdipisa** [comment]
@ElenaGallo this is a feature moved again in test
