### ISSUE TITLE
Feature Info do not correctly calculate coordinates

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#599]
To replicate click on honolulu zooming at resolutions of 18489335.
At resolution 9244667 it works instead.

**Comment by MV88** [comment]
The problem is the minx that is not calculated correctly on leaflet. It appears that when the bbox passes through the IDL it is misscalculated the projected minx.
bbox wrong:
minx 8990626.80339547       miny 978393.9620502548
maxx -11691807.846500559 maxy 5669793.010081234
bbox correct:
minx -19856505.459809944  miny 1306155.9393370934
maxx -10463923.424127487 maxy 5997554.987368068

Possible solutions are:
1) Shifting the bbox depending on where the point is
2) Reducing the bbox dimensions to a 101x101 pixels (not good for point ner the IDL)
3) I'm open to new proposal.

**Comment by offtherailz** [comment]
It seems a good compromise. Please check it works even at low zoom levels (like 0, 1...)

**Comment by MV88** [comment]
The 3rd point, listed in the previous comment, seems not required in order to fix this issue.
