### ISSUE TITLE
Installed extensions with issue fail silently

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#6053]
## Description
I noticed with some previous installation and it has been notified also here:

https://groups.google.com/g/mapstore-users/c/sG7W0s-Jupc/m/EPHz8bMoAgAJ

The  extension that have some issues (e.g. wrong imports, multiple entries, when only one is supported) fail silently when rendered.
- We should do a check when loading, to log the errors that made the extension do not work
- document more the current limits of extensions (1 export)

## How to reproduce
-  Try to install an extension ( in GeOrchestra or MapStore) that fails for some reason (e.g. you have multiple entries in webpack compiled tool) and then open it

*Expected Result*
- You have some error in console, when trying to use it
*Current Result*
- The plugin fails silently. Error is not logged anywhere

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information
Samples (for GeOrchstra)
[notWorkingExtension.zip](https://github.com/geosolutions-it/MapStore2/files/5402420/notWorkingExtension.zip)
[signalement.zip](https://github.com/geosolutions-it/MapStore2/files/5402435/signalement.zip)

**Comment by mgogh** [comment]
We think that this issue comes due to the webpack compilation of extension. When there is a lot of requirements or the extension is big, the command "_build-extension_" will create as expected a folder "extensions" with the "extensionComponent.js" but also a "vendors~extensions" which contains the rest of requirements.

In this case, a step is missing in the extension tutorial.
When there is a "vendors~extension" folder, it should be associated to the "extensionComponent.js" before the compression in zip. Without it, the "extensionComponent.zip" will be loaded in the context correctly but will failed silently (cause it miss a lot of requirements contained in the vendors~extension).

**Comment by offtherailz** [comment]
Hi @mgogh. For the release 2021.01.00 we fixed the "fail silently bug", notifying an error, and we completely renew the build system in a more light and predictable one. Please take a look at the updated documentation on master and the https://github.com/geosolutions-it/MapStoreExtension repository.
Thank you for the update.
