### ISSUE TITLE
Issue with the opacity option in the Visual Style Editor

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6313]
Icon opacity set to 0.00 is actually like 1.00
![2_style](https://user-images.githubusercontent.com/56537133/100440407-21383180-30a5-11eb-9b4e-829548a074f4.gif)

**How to Reproduce**
- open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/31145)
- select *Unesco Items* leyer
- open the layer settings and select the style tab
- select *prova* style
- click on edit
- Change the opacity to 0.00

*Expected Result*
The opacity set to 0.00 is actually 0.00

*Current Result*
The opacity set to 0.00 is like 1.00

**Comment by alexander-fedorenko** [comment]
@ElenaGallo is there a way to reproduce it in a most recent version of mapstore? Styles editor looks different right now and there is no "prova" style in the list.

**Comment by MV88** [comment]
this requires some fix to geostyler-sld-parser

i spoke with @allyoucanmap 
- since they use typescript opacity should be a number, so casting it to "0" is a workaround
- push the fix to our forked version
- the fix should include also this
- to a branch which starts from tag 2.0.1 
- and then use tarball instead of direct version
- we test it
- then we should propose a PR to their repo

plus
- we then publish it in our scope @geosolutions
- we test the fix and the usage of visual style editor also for master branch (that needs to be updated)

@alexander-fedorenko 
until the plus you can work
