### ISSUE TITLE
Edit features problem when two layers are selected on map

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6363]
## Description

Opening the edit feature from the GFI panel, the attribute table was not showing the selected feature
![riga7](https://user-images.githubusercontent.com/56537133/104033346-adbf2f00-51cf-11eb-9f56-137c1bae99ea.gif)

## How to reproduce

- Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/32214) or [this](http://localhost:8081/?debug=true#/viewer/openlayers/32524) one
- Click a point on map with state and observatories feature
- Click on edit 

*Expected Result*

The clicked observatories feature is visible on the attribute table

*Current Result*

The clicked observatories feature is not visible on the attribute table

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
Currently there are various issues:
- the pencil button in the GFI does not appear for [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/32214) map for states (click only on a state), it appears only for observatories (click only on an observatory)
- when clicking on both the pencil is activated for both, but the wfs request is wrong: because it contains <wfs:Query typeName="undefined", it works only if the layer you have in the GFI panel is selected in the toc, but it should work also without


- if you open instead [this](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358) map the pencil does not appear for the layer states, while it should
