### ISSUE TITLE
Filter feature on map when advanced search is closed

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6366]
## Description

The **Filter on the map** is no longer active when closing the advanced search
![riga6](https://user-images.githubusercontent.com/56537133/104035999-283d7e00-51d3-11eb-9425-bdc54535a45f.gif)

## How to reproduce

- Open  [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/32214)
- Click a states layer on TOC
- Click on Attribute table 
-  Click on Filter on map
- Click a layer feature on map ( or multiple features via the box section (alt+click) )
- Click on Advanced search 
- Click on back (left arrow) 

*Expected Result*

The Filter on the map is still active and you can filter other features

*Current Result*
The Filter on the map is no longer enabled 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
@offtherailz this is caused by this line [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/featuregrid.js#L433) and is never restoring previous status of enabled for the geom fitler.

a solutions is to have ti enabled by default
and the first solution that worked is to add these 2 new epics to the sea of epics already present.

```js
export const featureGridRestoreGeomFilterFirstTime = (action$, store) =>
    action$.ofType(OPEN_FEATURE_GRID).switchMap(() => {
        return action$.ofType(QUERY_CREATE).switchMap(() => {
            console.log("attribute", findGeometryProperty(describeSelector(store.getState()))?.name);
            const enableFilter = updateFilter({
                attribute: findGeometryProperty(describeSelector(store.getState()))?.name,
                enabled: true,
                type: "geometry"
            });
            // if closed for other causes, need to restore anyway the pagination
            return Rx.Observable.of(enableFilter);
        });
    });


export const featureGridRestoreGeomFilter = (action$, store) =>
    action$.ofType(OPEN_FEATURE_GRID).switchMap(() => {
        const enableFilter = updateFilter({
            attribute: findGeometryProperty(describeSelector(store.getState()))?.name,
            enabled: true,
            type: "geometry"
        });
        return Rx.Observable.of(enableFilter);
    });
```
only using featureGridRestoreGeomFilter does not work the first time you open the becasue the feature type is availabel after QUERY_CREATE, 

and using only "featureGridRestoreGeomFilterFirstTime" when the user clicks back on the advanced query form the QUERY_CREATE is not triggered.

@offtherailz can we discuss about possible improvements?

@tdipisa  i think is tricky to remember the status of geom filter, can we have it enabled from the starting and every time a feature grid is opened?

**Comment by offtherailz** [comment]
@MV88 please, fixing this take care of this comment
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/featuregrid.js#L431

The reset of the filter has been applied in order to avoid some inconsistencies on UI (so this disable is intended). If you want to find a way to restore the filter somehow, to see that everything is still working I suggest to select many features (more than page size) and apply additional quick filters to try if it is still working.
