### ISSUE TITLE
List of Formats in Catalog tool

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6522]
## Description

The Catalog tool needs to be improved to autometically retrieve the list of supported formats by the server when/where possible.

1. Add the the format **image/vnd.jpeg-png8** to the default list of formats (it is currently missing)

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/5bc0cec2-2a7d-4300-be93-b4d191dc7145)

2. In case of a Catalog of type **WMS** the list of supported formats is reported in the GetCapabilities response. We should use that list of formats for the related advanced option. We can use the default fixed list as fallback if needed (like in case of a CSW source type)

3. Also the list of formats in Layer Settings should be aligned to this behavior in case of WMS layers

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6eeddf1f-93e0-4278-9115-2919fbf6f748)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
Draft task list:
- [ ] If type is WMS and URL is valid, on list open, (re-)do a request to the GetCapabilities to get the formats. If not available, use defaults. 1pt
- [ ] When the record is created, the list of available formats should be added to the layer when adding, so it can be used in layer settings. 1pt
- [ ] Use the available formats in layer settings. If not present use defaults. 1pt

- [ ] Optional - I suggest to include also the available formats for GetFeatureInfo, to be used in the layers settings as well, to identify the possible allowed formats, if present. 1-2pt more.
- [ ] Optional - Possibility to refresh info from capabilities. 1pt more.

**Comment by ElenaGallo** [comment]
@dsuren1 a note after testing this issue:

- If the **image/png8** is selected on cotalog options the layers added to the TOC is on _image/png_ instead of **image/png8**
![png8_prob](https://user-images.githubusercontent.com/56537133/116221530-ff270600-a74d-11eb-8826-25b02ff17aa3.gif)


*How to reproduce*

- Open a map
- Click on Catalog from Burger Menu
- Click on edit from WMS service
- Select image/png8 on Format dropdown menu
- Click on Save
- Add a layer on TOC
- Select the layer
- CLick on Settings
- CLick on Display tab

*Current Result*
The layer Format is on _image/png_

*Expected Result*
The layer Format is on **image/png8**
