### ISSUE TITLE
Hide layers in time slider not visible in TOC

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6523]
## Description

Temporal layers hidden in TOC should not be present in the Time Slider list and the Timeline hidden if all time layers are not visible. 

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/1b248ee5-128b-40ba-8926-55b779a24e1a)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
Show only a sub-set of layer should be only a problem of filtering.
At the moment the list takes all the layers with time dimension, but we can filter more.
https://github.com/geosolutions-it/MapStore2/blob/8c6490c4ddd110ef5846fb0b9b9b5e509b6c3825/web/client/selectors/timeline.js#L169

We will probably need to properly check the updates if the data and time dimension parameter on show/hide layer events as well as we do adding/removing layers. Another thing to check is to possibly avoid to download time dimension data for hidden layers ( It should work this way, but not sure this operation is done by the timeline or the time dimension ).

Notes:
- If no layer is present, the timeline do not show, and this conflicts with the guide layer exception proposal, because guide layer is optional. So if you disable the "snap" option, you have no layer anymore (and technically the timeline should disappear, if we don't include other checks).

**Comment by offtherailz** [comment]
As for discussion, I suggest to 
- ignore the guide layer for the moment and check the possible issues if the guide layer is not visible. Maybe you could try to switch to another guide layer, if some guide layer is turned off, as it happens when you remove the guide layer, you may follow the same approach, the functionality should be in `epics/timeline` --> `setupTimelineExistingSettings`
- Make this filtering optional, active by default, but that can be disabled with `"showHiddenLayers": true` in plugin configuration.
