### ISSUE TITLE
Minor improvements to homepage + URL

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#6578]
## Description
There are a few things to do:
- [x] The upper GeoSolutions left-icon now points to the old website. It should point to the [new one](http://www.geosolutionsgroup.com/).
- [x] Replace the upper left GeoSolutions Icon with the [MapStore logo](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/product/assets/img/mapstorelogo.png)!
![image](https://user-images.githubusercontent.com/693880/109010648-53f7c300-76b0-11eb-9b0a-176b96e4c020.png)
- [x] The footer should be updated to use the following sentence --> **GeoSolutions** info@geosolutionsgroup.com **US** +1 (301) 337-7055 -  **Italy**: +39 0584 962313
- [ ] We shall start using the **geosolutionsgroup.com** rather than **geo-solutions.it** as soon as possible, possibly from next release. It is important that the old URLs keep working though since we will have many link around pointing to those addresses. This is devops work, most probably.

**Comment by tdipisa** [comment]
@simboss regarding the the 3rd point

>We shall start using the geosolutionsgroup.com rather than geo-solutions.it as soon as possible, possibly from next release. It is important that the old URLs keep working though since we will have many link around pointing to those addresses. This is devops work, most probably.

MapStore is using the old URL but a redirect to the new one is already in place, therefore I suppose this point has already benn done by devops, isn't it @randomorder?

**Comment by tdipisa** [comment]
@luorlandini Can you please proceed with the first two points please?

**Comment by simboss** [comment]
> @simboss regarding the the 3rd point:
> 
> > We shall start using the geosolutionsgroup.com rather than geo-solutions.it as soon as possible, possibly from next release. It is important that the old URLs keep working though since we will have many link around pointing to those addresses. This is devops work, most probably.
> 
> MapStore is using the old URL but a redirect to the new one is already in place, therefore I suppose this point has already benn done by devops, isn't it @randomorder?

can yo paste the new URLs?

**Comment by randomorder** [comment]
> > MapStore is using the old URL but a redirect to the new one is already in place, therefore I suppose this point has already benn done by devops, isn't it @randomorder?

I guess @simboss is referring to the mapstore app URL. That's not in place yet:
![image](https://user-images.githubusercontent.com/5264230/109014777-beaafd80-76b4-11eb-856f-fbb471a0b09b.png)

**Comment by simboss** [comment]
@randomorder that URL is wrong.

I would expect [mapstore.geosolutionsgroup.com](https://mapstore.geosolutionsgroup.com) to work.

**Comment by allyoucanmap** [comment]
I just reviewed the PR https://github.com/geosolutions-it/MapStore2/pull/6581 and the homepage changes are fine.

>  We shall start using the geosolutionsgroup.com rather than geo-solutions.it as soon as possible, possibly from next release. It is important that the old URLs keep working though since we will have many link around pointing to those addresses. This is devops work, most probably.

@simboss @tdipisa @randomorder 

I searched in the whole repository and geo-solutions.it is still used for these endpoints:

- http[s]://www.geo-solutions.it
- http[s]://dev.mapstore.geo-solutions.it
- http://qa.mapstore.geo-solutions.it
- http[s]://mapstore.geo-solutions.it
- https://mapstore2.geo-solutions.it
- https://cdn.jslibs.mapstore2.geo-solutions.it/leaflet/favicon.ico
- https://maven.geo-solutions.it
- http[s]://gs-stable.geo-solutions.it
- https://1maps.geo-solutions.it/geoserver/wms
- https://2maps.geo-solutions.it/geoserver/wms
- https://3maps.geo-solutions.it/geoserver/wms
- https://4maps.geo-solutions.it/geoserver/wms
- https://5maps.geo-solutions.it/geoserver/wms
- https://6maps.geo-solutions.it/geoserver/wms

probably I missed something because there are 482 results in the repo that match geo-solutions.it.
Note: saved maps created by mapstore contains also the https://[1-6]maps.geo-solutions.it/geoserver/wms endpoints

Are all these endpoints replaceble?
@tdipisa @simboss should we open a different issue and in the meanwhile merge the PR with the updates on the homepage?

**Comment by simboss** [comment]
@tdipisa @allyoucanmap let's factor our this as a separate issue.

We might do a minor release just for that.

**Comment by tdipisa** [comment]
@simboss @allyoucanmap the PR on master has been merged. I've opened a new issue for the above comment [here](https://github.com/geosolutions-it/MapStore2/issues/6587) (scheduled for next milestone, if we can).
