### ISSUE TITLE
Issue with '0' values for coordinate in input fields in Measurement and Annotation tools

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6606]
## Description

There are problems when using the digit "0" in decimal places of a coordinate. MapStore will ignore all entered 0 values for decimal places at the end.

First of all we have to further investigate the problem to properly evaluate the better solution.

## How to reproduce

-  Go to distance measuring tool. 
- Try to measure distance from lat: 47.242902 lon: 10.403016 to lat: 48.222 lon: 14.301 by entering the values manually

*Expected Result*

It should be possible to type '0' values everywhere.

*Current Result*

It is not possible to type '0' values for decimal places at the end.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

From a recent investigation:

>This is because the coordinates field being used is not a native input field but custom one modified with the implementation of the react-numeric-input library, to act as a localized input field. Due to this reason, as we type/input, it parses the input value, formats it with the localization data (EN, DE, ..etc) followed by conversion of data to be displayed in the field, we lose the trailing zero only that comes after the decimal place.

**Comment by dsuren1** [comment]
Giving 8pts as it need investigation on the library used (unless the issue can be fixed in our code). Based on the investigation the estimate can be adjusted

**Comment by dsuren1** [comment]
The fix has to be given directly in the [library](https://github.com/vlad-ignatov/react-numeric-input) used. Since the library is not actively maintained we need to fork it to Geosolutions to provide the fix and use the same in our Mapstore app

Incomplete number scope need modification to support for following user inputs
Ex: **9.10**, **9.1023303**, **-9.02**, **-9.10**
https://github.com/vlad-ignatov/react-numeric-input/blob/master/index.js#L76

Also, the issue affects only default/**en-US** locale, input for other locale works fine. 
Ex: For _de-DE_:  **9,10**  - _Work fine in the existing version_

**Comment by tdipisa** [comment]
Closed in favor of #6689
