### ISSUE TITLE
Review of layer Identify behavior from Search tool

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6609]
## Description

Currently if you perform an Indentify request from the Search tool configuring it as reported below

![image](https://user-images.githubusercontent.com/1280027/110106697-47f3bb80-7daa-11eb-84be-715553a528a0.png)

 'application/json' ('PROPERTIES') is always used as GetFeatureInfo output format so that MS is able to filter GFI results and show in the Identify panel only the one selected in Seach tool results (this means the filtering is made client side). 

![search_info](https://user-images.githubusercontent.com/1280027/110106754-5b9f2200-7daa-11eb-8d61-1fec9f82d7ea.gif)

However, the Identify response should be provided in the format choosen by the user for the layer (through Layer Settings or in General Options). It is anyway useful, at the same time, to show in Identify panel only the information related to the selected item in Search tool. We should improve the current functionality to:

- Consider to have the current behavior configurable for retro compatibility (active or not with a new true/false property). To discuss.
- If the current behavior is disabled, always use the Identify format configured for the layer and not always 'application/json'
- Include the support for [GeoServer vendor params](https://docs.geoserver.org/stable/en/user/services/wms/reference.html#getfeatureinfo) like [filter](https://docs.geoserver.org/latest/en/user/services/wms/vendor.html#cql-filter) or [featureid](https://docs.geoserver.org/latest/en/user/services/wms/vendor.html#featureid) so that it is possible to filter the Identify result directly server side instead of client side (WMS servers that don't support the GeoServer vendor param will simply ignore it)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
Draft of the work is available in a custom branch of MS [here](https://github.com/geosolutions-it/MapStore2/commit/16b7ea04936cd967cf414c10fee3c3112133996b) where the Identify format set for the layer is always used.

**Comment by offtherailz** [comment]
About this
> Consider to have the current behavior configurable for retro compatibility (active or not with a new true/false property). To discuss.

In case we do not use `json`, we may have many results, that can not be filtered. This is not what I expect when I select a single result. To make it simpler I should not add a flag.

We may have many results, but we can anyway mitigate the problem in case of GeoServer. I suggest to send anyway the additional parmeter `featureId` that should be ignored by other servers, but can be used by GeoServer to select the specific feature instead to showing all the results.

 I should document (in user guide) that if you are not using GeoServer, the results can be multiple, and to trying to set "properties" format in the layer can allow to have single results.

So in the code, if format is json and the id is present, we try to filter by Id anyway (if only one result, because GeoServer already filtered, this filtering has no effect).

**Comment by dsuren1** [comment]
Currently with `single layer` set in _search config_ and selecting the search results to **GetFeatureInfo**, only one result is returned in the GFI panel (with default info_format as `application/json`), because we perform `GFI` only when the output of **GetFeature** has valid response.

So modifying the info_format for **GetFeatureInfo** request to use the format selected in the layer alone is needed here.

@offtherailz @tdipisa Your thoughts. Kindly let me know if I'm missing something
