### ISSUE TITLE
Catalog service selector for dashboards

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6664]
## Description

This issue follows the initial investigation and analysis done in #2797. Currently the catalog tool available for [dashboards](https://mapstore.readthedocs.io/en/latest/user-guide/adding-widgets/) is limited compared to the one present for the [map viewer](https://mapstore.readthedocs.io/en/latest/user-guide/catalog/). 

In particular it is not possible to configure multiple sources. There is only one catalog service to retrieve layers for geodashboard and it is [pre-configured in localconfig.json ](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/localConfig.json#L670): it cannot be configured from the user interface and it is not possible to add other sources as well as it is possible for the Catalog tool in the map viewer.

Within this issue it is required to enhance the Catalog tool of dashboards to allow adding multiple sources and configure them from the UI. The one available now in localConfig will be the default one for each new dashboard.

## Acceptance criteria

The aim is to have also for geodashboards the same fundamental catalog capabilities available for the map viewer to allow the user to configure one of the [catalog source types MS supports](https://mapstore.readthedocs.io/en/latest/user-guide/catalog/#catalog-types) along with their advanced options

![111140687-ed651700-8582-11eb-949c-348c32ce7a7f](https://user-images.githubusercontent.com/1280027/111603580-c867e280-87d4-11eb-80d6-fdd48df3779a.png)

- [ ] User must be able to select a catalog from the UI. The initial list is configured in localConfig.json as for the map's catalog

![image](https://user-images.githubusercontent.com/1280027/111604191-6065cc00-87d5-11eb-819a-130fe6b157e9.png)

- [ ] User must be able to add his own source, as for the map's catalog

![image](https://user-images.githubusercontent.com/1280027/111604427-9d31c300-87d5-11eb-839d-5f7d1dd6a151.png)

- [ ] It is possible to configure new and existing catalog sources along with advanced options, the same one of the Catalog tool in the viewer but with some exceptions listed below:

   -  **Search on service selection**: this option can be excluded for all catalog types
   -  **Show metadata template**: this option can be excluded for CSW catalog types

![image](https://user-images.githubusercontent.com/1280027/111604621-ce11f800-87d5-11eb-85bb-84885937cf54.png)

Below a picture that illustrate the configiration panel.

![image](https://user-images.githubusercontent.com/1280027/111510515-24d3ef00-874e-11eb-8e4b-6d908c9825b6.png)

- [ ] When the user save the dashboard, if the list of sources has been modified, the sources must be saved in the dashboard resource, for a future re-use. When a user load an existing dashboard, the list of catalog should contain the ones added by the user when he saved it the last time. If there was no sources list saved, the list will be the one configured in localConfig.json

## Other useful information
Some useful information for the development have been reported in the investigation issue [here](https://github.com/geosolutions-it/MapStore2/issues/2797#issuecomment-799317299).

**Comment by ElenaGallo** [comment]
@MuhweziDeo here some notes after thesing this issue:
1- By opening a new dashboard in the service list there are also services added in other dashboards instead of only those configured in localConfig.json

**How to reproduce**
- Open a new dashboard
- Click on +
- Click on Map
- Click on Empty map
- Click on +
- Follow the steps on the gif below:
![1](https://user-images.githubusercontent.com/56537133/117167202-5587ea80-adc7-11eb-8db5-50805804d117.gif)

*Expected Result*
The services visible on a new dash are:
`https://gs-stable.geo-solutions.it/geoserver/csw`
`https://gs-stable.geo-solutions.it/geoserver/wms`
`https://gs-stable.geo-solutions.it/geoserver/gwc/service/wmts`

2- When Show preview buttons is not enabled, the preview is still visible

**How to reproduce**
- Follow the steps on the gif below:
![2](https://user-images.githubusercontent.com/56537133/117167273-659fca00-adc7-11eb-8ba3-0a05d0666e6b.gif)

*Expected Result*
The previews are not visible on the layers list

3- Once a service has been saved, the panel returns to the previous page (Configure Map Options page) instead of opening the list of layers of the service just saved

**How to reproduce**
- Follow the steps on the gif below:
![3](https://user-images.githubusercontent.com/56537133/117167332-72bcb900-adc7-11eb-94e3-301eb5adfef7.gif)

*Expected Result*
You are redirected to the list of layers of the service you just saved

4- In Advanced options of a service the **image/vnd.jpeg-png8** option is missing for the Format option and **512x512** option is missing for Layer tile size option

**How to reproduce**
- Open a dashboard
- Click on +
- Click on Map
- Click on Empty map
- Click on +
- Click on Edit a service
- Open the Advanced options

*Expected Result*
See the Advanced options on a map viewer:
**Layer tile size option**
![4 1](https://user-images.githubusercontent.com/56537133/117167376-7d774e00-adc7-11eb-86c0-9697b67f7194.png)

**Format option**
![4 2](https://user-images.githubusercontent.com/56537133/117167410-8405c580-adc7-11eb-85c3-5b85d6575c38.png)

5- **Show metadata template** is present as an option in CSW service advanced settings even though the problem says not to show these options for CSW services
![5](https://user-images.githubusercontent.com/56537133/117167462-8ec05a80-adc7-11eb-9374-83fbd04ebaf5.png)

**How to reproduce**
- Open a dashboard
- Click on +
- Click on Map
- Click on Empty map
- Click on +
- Click on Edit a CWS service
- Open the Advanced options

*Expected Result*
**Show metadata template** option is not present on CSW sevices

**Comment by MuhweziDeo** [comment]
> @MuhweziDeo here some notes after thesing this issue:
> 1- By opening a new dashboard in the service list there are also services added in other dashboards instead of only those configured in localConfig.json
> 
> **How to reproduce**
> 
> * Open a new dashboard
> * Click on +
> * Click on Map
> * Click on Empty map
> * Click on +
> * Follow the steps on the gif below:
>   ![1](https://user-images.githubusercontent.com/56537133/117167202-5587ea80-adc7-11eb-8db5-50805804d117.gif)
> 
> _Expected Result_
> The services visible on a new dash are:
> `https://gs-stable.geo-solutions.it/geoserver/csw`
> `https://gs-stable.geo-solutions.it/geoserver/wms`
> `https://gs-stable.geo-solutions.it/geoserver/gwc/service/wmts`
> 
> 2- When Show preview buttons is not enabled, the preview is still visible
> 
> **How to reproduce**
> 
> * Follow the steps on the gif below:
>   ![2](https://user-images.githubusercontent.com/56537133/117167273-659fca00-adc7-11eb-8ba3-0a05d0666e6b.gif)
> 
> _Expected Result_
> The previews are not visible on the layers list
> 
> 3- Once a service has been saved, the panel returns to the previous page (Configure Map Options page) instead of opening the list of layers of the service just saved
> 
> **How to reproduce**
> 
> * Follow the steps on the gif below:
>   ![3](https://user-images.githubusercontent.com/56537133/117167332-72bcb900-adc7-11eb-94e3-301eb5adfef7.gif)
> 
> _Expected Result_
> You are redirected to the list of layers of the service you just saved
> 
> 4- In Advanced options of a service the **image/vnd.jpeg-png8** option is missing for the Format option and **512x512** option is missing for Layer tile size option
> 
> **How to reproduce**
> 
> * Open a dashboard
> * Click on +
> * Click on Map
> * Click on Empty map
> * Click on +
> * Click on Edit a service
> * Open the Advanced options
> 
> _Expected Result_
> See the Advanced options on a map viewer:
> **Layer tile size option**
> ![4 1](https://user-images.githubusercontent.com/56537133/117167376-7d774e00-adc7-11eb-86c0-9697b67f7194.png)
> 
> **Format option**
> ![4 2](https://user-images.githubusercontent.com/56537133/117167410-8405c580-adc7-11eb-85c3-5b85d6575c38.png)
> 
> 5- **Show metadata template** is present as an option in CSW service advanced settings even though the problem says not to show these options for CSW services
> ![5](https://user-images.githubusercontent.com/56537133/117167462-8ec05a80-adc7-11eb-9374-83fbd04ebaf5.png)
> 
> **How to reproduce**
> 
> * Open a dashboard
> * Click on +
> * Click on Map
> * Click on Empty map
> * Click on +
> * Click on Edit a CWS service
> * Open the Advanced options
> 
> _Expected Result_
> **Show metadata template** option is not present on CSW sevices

Thanks
