### ISSUE TITLE
Improving default embedded maps configuration

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#6687]
## Description

This issue collects some enhancements reported in #6643. What is needed for this issue is listed below:

- [ ]  Disable mouse scrolling for embedded maps and add zoom in/zoom buttons in navigation toolbar. We can consider to have smaller buttons for the nav toolbar (see also comment [here](https://github.com/geosolutions-it/MapStore2/issues/6643#issuecomment-801253967))
- [ ] Include the full screen button and make it working also for embedded maps (see also comment [here](https://github.com/geosolutions-it/MapStore2/issues/6643#issuecomment-801253967)). Highlight blockers before, if any
- [ ] Always display the button to hide the search toolbar: now it is possible only after a certain size of the iframe

![2021_03_23_12_37_53_MapStore](https://user-images.githubusercontent.com/1280027/112140708-a73c3300-8bd4-11eb-826e-50ddcd25453a.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
We can consider to review the logic to automatically have the best size of nav toolbar buttons in relation of the embed size (see #6688)

**Comment by allyoucanmap** [comment]
@tdipisa I would avoid to have multiple themes based on the size of the screen instead I would propose to work on the theme improvements and reduce button size for all type of screen.

**Comment by ElenaGallo** [comment]
@MuhweziDeo, some notes after testing this issue:
1_ The full screen does not work as expected

**How to Reproduce**
- Open the Share panel of a map on the smbed section
- Copy the embedded map to a notes
- Open the embedded map
- Click on Full screen button

*Current Result*
The map does not become full screen

2_ By adding the TOC to the embedded map the zoom in/out button on the left is no longer usable because it is covered by the TOC button
![toc](https://user-images.githubusercontent.com/56537133/114057608-fe0f6100-9892-11eb-965b-710ecd0350b3.png)

**How to Reproduce**
- Open the Share panel of a map on the embed section
- Click on Show TOC
- Copy the embedded map to a notes
- Open the embedded map

*Current Result*
The TOC button cover the zoom in/out button

**Comment by MuhweziDeo** [comment]
@ElenaGallo thanks for discovering this. I did not know of this scenario while implementing my solution. I will take it into account now. thanks

**Comment by offtherailz** [comment]
I think you ca use CSS to move zoom buttons below the TOC button. I suggest to limit this to the embedded context (verify that geostory maps will not be influenced by this). Possibly find a CSS selector that is valid when TOC is present, or always move it down 50px in embedded mode.

@allyoucanmap any suggestion?

**Comment by ElenaGallo** [comment]
@MuhweziDeo the second point of [this comment](https://github.com/geosolutions-it/MapStore2/issues/6687#issuecomment-815938671) still doesn't work, see this [embed map](https://github.com/geosolutions-it/MapStore2/files/6356526/sese.zip).
