### ISSUE TITLE
Some properties of Feature Editor are obscured from the one in the state

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#6758]
## Description

Given the current connect method (react-redux) used to connect the FeatureEditor to the state,
some properties that are both in the state and in the initial cfg are conflicting with the
one in the state winning at the end.

for example customEditorsOptions

@offtherailz 
we need find a way to initialize the state with the cfg or maybe with an onMount action?

## How to reproduce

-  this is reproducable in C040 project
-  see [here](https://github.com/geosolutions-it/MapStore2-C040/issues/424)

*Expected Result*

to be able to see the address editor in the feature editor for specific fields

*Current Result*

the config is not passed to the plugin

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
Yes, good Idea, in this case we can configure it programmatically (e.g. in custom projects or extensions) or by configuration.

**Comment by offtherailz** [comment]
There are 2 more issues that do not allow customEditorOptions: 
1. Default custom editors (dropdown, Number ...) are not available anymore. Regression should be caused by https://github.com/geosolutions-it/MapStore2/pull/6198 ( a `require` without `default` needing an `export default`)  The issue https://github.com/geosolutions-it/MapStore2/issues/6758 was solved and tested in a custom project with custom registers, added aside from the default ones. For this reason this issue has not been found, but present for default custom editors
2. The onmount method is not enough for setting up the props, because the plugin renders once with the default props, before to switch to the context settings.
