### ISSUE TITLE
The different decimal separator between FeatureGrid and Chart causes an error in the charts 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#6772]
When the feature grid uses the Anglo-Saxon decimal separator the charts report a wrong value

**Attribute Table value**
![chart2.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/de6422ed-6ab8-4f25-a5c7-0c5dee91313c)
**Wrong Bar Chart value**
![chart.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/343d8e45-34d8-474b-8827-424d7ef0ef53)

**How to reproduce**
- Open [this map](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/33689)
- Hover over the Arizona bar in the Bar Chart

*Current Result*
The value is 294,3335k but in the FeatureGrid is reported the follows value 294,333.46

*Expected Result*
The value in the Bar Chart is the same as that in the FeatureGrid

**Comment by offtherailz** [comment]
The data received from the server is correct. 

I think it is a rounding problem, not sure if proper of chart lib or configuration. It is rounding 294333.462 to 295,3335 K (so 295K +  333462 --> 0,333.462 K, a fraction of 1K, rounded to the first decimal). It is correct but confusing.
It looks a default for plotly, for a first inspection. Need to check more.

**Comment by MuhweziDeo** [comment]
Yes, @offtherailz your investigation is correct. Polty somehow does its own rounding off internally. Still trying to figure out the part and see if there is a way to override it

**Comment by offtherailz** [comment]
mmm... honestly, because this is correct (even if confusing) I should leave to the user using the UI the possibility to customize format, if the default doesn't satisfy him. 
I apreciate the attempt to solve the specific issue, but if the format is already allowed, I should not override it. I think we should change nothing. 

For instance the user can use `.4f` or whatever he wants to change the format.

![image](https://user-images.githubusercontent.com/1279510/115518025-0babea00-a288-11eb-9093-ebd7ffeb9818.png)

@tdipisa I should close this issue and the pending PR with no action.

**Comment by tdipisa** [comment]
@offtherailz it is confusing right now since we have a different formatting of values between attribute table and charts: it should be at least the same by default in all MS, then yes, the user can also customize it using the UI for charts. Now it seems we are in a default condition where where values displayed to the user are confusing.

**Comment by offtherailz** [comment]
IMHO the user is not confused that much. The approximation (due to the chart limited space) is quite visible and understandable.
If not satisfied from this default, he can customize the format. Any formatting default we can imagine may has it's limits. We can  use a different default showing the whole numbers, even if bigger, only sacrificing the good looking charts (with compact strings) as default. I prefer good looking as default, but is my opinion.

**Comment by tdipisa** [comment]
@offtherailz I think you haven't properly catched my point: formatting should be the same by default. If I display a number using a certain format in the attribute table, it should be the same also for charts. The advanced options are, as they say, advanced: a common user will never open them probably.

**Comment by offtherailz** [comment]
Sorry if I didn't reply for a long time. I was checking old PRs and so I found this again. Due to a small investigation about how to customize that value, I should have found a partial solution.
![image](https://user-images.githubusercontent.com/1279510/117289156-91c15680-ae6c-11eb-982c-697e460e62d9.png)
```diff
diff --git a/web/client/components/charts/WidgetChart.jsx b/web/client/components/charts/WidgetChart.jsx
index 8d9adf27d..392797bc0 100644
--- a/web/client/components/charts/WidgetChart.jsx
+++ b/web/client/components/charts/WidgetChart.jsx
@@ -24,7 +24,7 @@ export const defaultColorGenerator = (total, colorOptions) => {
     return (sameToneRangeColors(base, range, total + 1, opts) || [0]).slice(1);
 };
 
-function getData({ type, xDataKey, yDataKey, data, formula}) {
+function getData({ type, xDataKey, yDataKey, data, formula, yAxisOpts }) {
     const x = data.map(d => d[xDataKey]);
     let y = data.map(d => d[yDataKey]);
     switch (type) {
@@ -51,6 +51,7 @@ function getData({ type, xDataKey, yDataKey, data, formula}) {
 
         }
         return {
+            hovertemplate: `${yAxisOpts?.tickPrefix ?? ""}%{y:${yAxisOpts?.format ?? '.2f'}}${yAxisOpts?.tickSuffix ?? ""}<extra></extra>`, // uses the format if passed, otherwise shows the full number.
             x,
             y
         };
```

The only thing that is missing is the format `.2f` is always two decimal number. @MuhweziDeo we have to find only a format, in d3, to show the number without S.I. unit (basically the plain number in js). It's a plus if we have the number format localized.

**Comment by offtherailz** [comment]
Created PR just to keep track of the current proposed solution
https://github.com/geosolutions-it/MapStore2/pull/6834
