### ISSUE TITLE
Style Editor doesn't set the format for external graphic sometimes

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/MapStore2#6819]
From what I see the Style Editor includes the `Format` element when an SLD style with an [External Graphic](https://docs.geoserver.org/latest/en/user/styling/sld/extensions/pointsymbols.html#external-graphics) element is submitted to Geoserver.
I suppose it implements some logic to obtain the format for the image set by the user.

Apparently MapStore isn't able to parse the format for this [image](https://master.demo.geonode.org/documents/1623/link), which is coming from this [GeoNode document](https://master.demo.geonode.org/documents/1623). The missing format makes the SLD style invalid, and Geoserver complains of course. 

Two questions:

 - why is not the format parsed / set for this image?
 - do you confirm MapStore deduces the format from the image? Whatever the answer it shouldn't post the style body if the Format element can be set. An error should be raised and reported to the user instead. Otherwise a new selection box should be provded with a list of standard MIME types to be selected

**Comment by dsuren1** [comment]
> Two questions:
> 
> * why is not the format parsed / set for this image?

_The SLDParser (geostyler-sld-parser) style writer, implements logic of finding the format by looking for a extension in the url. Since the above url doesn't have any extension explicitly mentioned. It writer fails to add a <Format> element in the SLD style._

> * do you confirm MapStore deduces the format from the image? Whatever the answer it shouldn't post the style body if the Format element can be set. An error should be raised and reported to the user instead. Otherwise a new selection box should be provded with a list of standard MIME types to be selected

_Mapstore deduces the image but doesn't explicitly sets the format to SLDParser, as it is directly dealt from the image url by the parser (as mentioned above)_

@tdipisa @allyoucanmap 
1. Should we add the <Format> element to the parsed style if missing, be deducing the format of the image?
2. Or display error message and stop the post call?

**Comment by giohappy** [comment]
@dsuren1 the <Format> element is mandatory for a valid style, so we can't omit it. 
The best solution to me is to provide a format selector. The parser will try setting it (from the extension), and if it fails it should warn the user ("the image format couldn't be parsed. Please select the format" or something like this.
