### ISSUE TITLE
Timeline functionalities crash after Mapstore reload

### ISSUE THREAD

**Issue by MaelREBOUX** [geosolutions-it/MapStore2#6990]
## Description

We have set up a map template with time dimension layers.
All works well but :
- if the user go to an other webpage then go back to mapstore
- or refresh mapstore (F5)

this leads to a non fonctionnal mapstore state :
- groups and/or layers are renamed with their uid instead of their names
- thumbnail of the current background is erased / blank
- the timeline plugin is not working anymore

![ms2_bug_timeline_f5](https://user-images.githubusercontent.com/6370443/122375331-6b123780-cf63-11eb-8039-b965e93caeaa.gif)

*Expected Result*

Restore a correct mapstore state from the localstore / user session.
For @EtienneROUVIN

- [x] Not browser related

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| 91.0 |
|Firefox| 78.10.0esr |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@MaelREBOUX thank you for reporting this. I think probably the title of the issue shoudl be changed to better refletcs what you put in description (eg. it is not only related to Timeline it seems)

**Comment by tdipisa** [comment]
@MaelREBOUX can you provide the link to the context you are referring to for a quick look. It seems there is a notification message on top-right of your GIF but it is not readable.

**Comment by tdipisa** [comment]
@MaelREBOUX I'm not currently able to reproduce the issue in our DEV. It would be probably better if you can provide most accurate steps to reproduce. Thank you so much.

**Comment by MaelREBOUX** [comment]
Hello Tobia.

Change the title at your conveniance.

For testing, you should connect to our private portal, then load the map template named "comptages routiers".
Because these layers are not yet available in open data.

**Comment by MaelREBOUX** [comment]
The error message :

![image](https://user-images.githubusercontent.com/6370443/122401342-c997df80-cf7c-11eb-9c2c-5fdcfa467c91.png)

And I note a 400 error on `/geoserver/gwc/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=trp_rout:v_comptage_station_stats&tileMatrixSet=EPSG:4326&expandLimit=10`

with the answer `Service is disabled`

I don't have this while loadng the map template in the "normal" way.

**Comment by tdipisa** [comment]
Dear @MaelREBOUX I've created a new context in your test environment named **issue_6990** and I've tested it on both browser versions you have indicated in the issue description.

There are two different things here to consider:

1 - Wrong groups names in TOC after refreshing the application: this effectively happens **only** when you add a template by clicking on "Add this template to the map". In this case all template contents are added in a main group in TOC and probably there is a small fix to do for this. Thank you for reporting

2 - What you reported for the Timeline is not related to point 1 and it can only depends on some networking issues you have experienced: if the DescribeDomain request fails, it is not possible for MapStore to initialize the Timeline tool; the notification in red inform you about that

I'm going to open a new issue for point 1 so that we can provide a fix as soon as possible.
