### ISSUE TITLE
MapStore should not regenerate layer IDs for background layers

### ISSUE THREAD

**Issue by MaelREBOUX** [geosolutions-it/MapStore2#7082]
Hello. I don't know if it woud be suitable to post on the user mailing list but, in a way, it is maybe a future enhancement.

## Description

We have a georchestra MapStore2 version 1.2.x

We set up a context with a json file for the source of the map. This JSON contains :
- only one thematic layer (in the _default_ group)
- 5 backgrounds

![image](https://user-images.githubusercontent.com/6370443/124884693-cff50680-dfd2-11eb-8bf5-935c219dbc8d.png)

We have set up too a map template with a JSON which only contains the same backgrounds.

![image](https://user-images.githubusercontent.com/6370443/124884978-1480a200-dfd3-11eb-85bc-e4d213590e0c.png)

The JSON code for the declaration of these backgrounds is strictly the main. Note that the have manually recoded the id oth the layers

Example :

```json
{
  "version": 2,
  "map": {
    "center": {
      "x": -1.779345809648175,
      "y": 48.12802244563291,
      "crs": "EPSG:4326"
    },
    "maxExtent": [-20037508.34, -20037508.34, 20037508.34, 20037508.34],
    "projection": "EPSG:3857",
    "units": "m",
    "zoom": 10,
    "mapOptions": {},
    "layers": [{
        "id": "bg-pvci-couleur",
        "format": "image/png",
        "group": "background",
        "name": "ref_fonds:pvci",
        "description": "a description",
        "style": "",
        "title": "Plan de ville couleur",
        "type": "wmts",
        "url": "https://portail-test.sig.rennesmetropole.fr/geowebcache/service/wmts",
        "bbox": {
          "crs": "EPSG:4326",
          "bounds": {
            "minx": "-180.0",
            "miny": "-90.0",
            "maxx": "180.0",
            "maxy": "90.0"
          }
        },
        "visibility": true,
        "singleTile": false,
        "allowedSRS": {
          "EPSG:3948": true,
          "EPSG:3857": true,
          "EPSG:900913": true,
          "EPSG:2154": true
        },
        "matrixIds": ["EPSG:3948", "EPSG:3857", "EPSG:2154"],
        "tileMatrixSet": true,
        "requestEncoding": "KVP",
        "dimensions": [],
        "hideLoading": false,
        "handleClickOnLayer": false,
        "queryable": true,
        "capabilitiesURL": "/geowebcache/service/wmts",
        "useForElevation": false,
        "hidden": false,
        "params": {}
      }, {
        ....
      }
    ],
    "groups": [],
    "backgrounds": [{
        "id": "bg-pvci-couleur",
        "thumbnail": "data:image/png;base64,
        ....
}
    ],
    "bookmark_search_config": {},
    "sources": {
    .....
```

So we have a context with a map content and a map template with the same map content for backgrounds : same IDs.

Now **when we add the map template to the current map : the backgrounds are fully duplicated.**

![image](https://user-images.githubusercontent.com/6370443/124886068-30d10e80-dfd4-11eb-8f08-d655cf539e7d.png)

We export the map as JSON and we can see that **the id of the layers of the map template are regenerated.**

```json
    "layers": [{
        "id": "109f0790-dfbe-11eb-a04f-673ea4c85c0f",
        "format": "image/png",
        "group": "background",
        "name": "ref_fonds:pvci",
....
      }, {
        "id": "bg-pvci-couleur",
        "format": "image/png",
        "group": "background",
        "name": "ref_fonds:pvci",
....
      }
    ],
    "groups": [{
        "id": "Default",
        "title": "Default",
        "expanded": true
      }
    ],
    "backgrounds": [{
        "id": "bg-pvci-couleur",
....
      }, {
        "id": "109f0790-dfbe-11eb-a04f-673ea4c85c0f",
...
      }
    ],
....
```

## Expected behaviour

While the special backgroud layers ID are the same in the current map and in the map template which is added to the map, it should not regenerate the ID anf thus, duplicate the backgrounds.

We understand that que cannot ask for this behaviour for the thematic layers but layers backgrounds are special and should be treated in a different way.

The intend is to NOT have duplicate backgrounds after loading several map templates.

(Note : let me knwo if I should post this in the MapStore main repo)

- [x] Not browser related

**Comment by tdipisa** [comment]
@MaelREBOUX thank you for this. It can be a good enhancement so I'm ok to have an issue here in github. 

I don't understand this question anyway, that I think it is out of scope here:
>We have a georchestra MapStore2 version ????

geOrchestra is using a latest stable version of MS; not the last one since we have released the new version [2021.01.04](https://github.com/geosolutions-it/MapStore2/releases/tag/v2021.01.04) just last week.

**Comment by MaelREBOUX** [comment]
I just completed -> v 1.2.x
It is for have a precise opinion about our environnement.

**Comment by offtherailz** [comment]
Because backgrounds are very different  and not always have the ID, i propose that "add" functionality just skips the backgrounds.
Otherwise recognizing the backgrounds could be difficult.
We can compare them to verify if they are exactly the same, but it could be confusing and not always easy to understand and to apply. 

Replace button will continue to replace also the background, as it does now. 
@tdipisa what do you think?

**Comment by tdipisa** [comment]
@offtherailz @dsuren1 the options are two in my opinion.
1. We leave it as it is know. 
2. We compare all relevant properties in bg config object for different bg types (I think some kind of tolerance can be acceptable for some bg types like)

Option 2 is better in my opinion if it isn't too expensive. I don't think so, but let me know. It doesn't makes sense to exclude also different backgrounds since backgrounds are layer like the other ones :)

**Comment by offtherailz** [comment]
we can try to compare backgrounds if they are exaclty the same. 
IDs are not mandatory, so using them can cause confusion.

**Comment by MaelREBOUX** [comment]
> We can try to compare backgrounds if they are exaclty the same.

We are ok with this option. We understand that OGC properties like layer name will be tested.
