### ISSUE TITLE
Catalog / add a CSW data from GeoNetwork : impossible to get layer with the word "vitesse"

### ISSUE THREAD

**Issue by MaelREBOUX** [geosolutions-it/MapStore2#7084]
## Description

![ms2_bug_catalog_vitesse](https://user-images.githubusercontent.com/6370443/124922756-1dd13500-dffa-11eb-9826-71f32ee78de3.gif)

Funny but we have layers with the word "vitesse" and we cannot load them actually.

Note that GeoNetwork answers normally with datasets.

*Step to reproduce*

1. Go to the demo site (on any else mapstore instance) https://mapstore.geosolutionsgroup.com/
2. add https://geobretagne.fr/geonetwork/srv/fre/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities as new CSW catalog
3. save
4. type "vitesse" on the keyboard or copy-paste
5. boum -> error

- [ ] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| X |
|Firefox| X |
|Safari| |
</details>

**Comment by tdipisa** [comment]
Thank you so much for reporting this. There is probably a small bug to investigate since I saw the CSW is returing anyway some results: this is affecting the current release and our [QA instance](https://qa-mapstore.geosolutionsgroup.com/).
In [DEV instance](https://dev-mapstore.geosolutionsgroup.com/), where we have some other updates, it is working probably because the filtering behavior is a bit different and it is excluding some result due to #6813. A further improvement is anyway in plan with #6886. We will keep track of this too.

**Comment by dsuren1** [comment]
This issue should be fixed in this [PR](https://github.com/geosolutions-it/MapStore2/pull/7220)
