### ISSUE TITLE
Remove font awesome as a general notification

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#7086]
## Description

In case of font-awesome are not loaded (eg. due internet connection problems) MapStore shows the following notifications 

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/250d448d-9f09-419c-9ba0-3d84aecf7e23)

This notification should be visualized only for tools that need font-awesome to work otherwise it should be completely removed at all.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by offtherailz** [comment]
This advise is general for the map, so it can not be called only when used. 
I suggest to remove this advise completely, because :
- It is annoying
- I'm not able to reproduce the original problem

**Comment by tdipisa** [comment]
@offtherailz 

>I'm not able to reproduce the original problem

It happens in case of internet connection problems when it is not possible to load [this](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/index.html#L89)

**Comment by offtherailz** [comment]
If the some files was not loaded correctly, many other things may fail. Normally, all the files in index should be loaded before the JS to be executed.

That notification was present because, in certain cases, the font was loaded after the rendering of the map, and so the icons was not visible on the map (because they are rendered in a canvas).

I can not reroduce this use case. So I should the notification that is meanful.

**Comment by offtherailz** [comment]
We have an issue in case of error, not notified by the linter because of a disable rule

**Comment by offtherailz** [comment]
This still need to be backported
