### ISSUE TITLE
Identify tool result should show urls as hyperlink

### ISSUE THREAD

**Issue by MaelREBOUX** [geosolutions-it/MapStore2#7096]
## Description

Some datas has url in specific attributes. A user should be able to click on it to go to the resource : web page, document...
It will be so much easier for non specialist users.

![image](https://user-images.githubusercontent.com/6370443/125310340-c6e99980-e332-11eb-9b32-9ff6314f1329.png)

My proposition : if value of an attribute begins with "http" then transform the whole string in an hyperlink.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Comment by landryb** [comment]
and in the attribute table too ? in the feature popup ?

**Comment by MaelREBOUX** [comment]
Good question. I think yes ?

**Comment by MV88** [comment]
@MaelREBOUX 
Hi, i guess this depends on the info_format chosen, which i can see is TEXT i.e. text/plain
Have you tried using HTML if it is any better?

My 2 cents: I think this is the correct behaviour for this format

For the attribute table i think is possible to develop a custom cell renderer, based on the value of the attribute
@offtherailz  what do you think?

**Comment by landryb** [comment]
not sure what geoserver does for HTML output templating, but i'm pretty sure by default it doesnt render urls as proper HTML links.

**Comment by offtherailz** [comment]
You can do it on GeoServer using [FTL template](https://docs.geoserver.org/stable/en/user/tutorials/freemarker.html), then setting HTML format,  or using the MapStore template format, putting the variables in the URL of a link like this
![image](https://user-images.githubusercontent.com/1279510/126300197-6956c702-e4db-44ed-9505-5482da867b6d.png)

**Comment by MaelREBOUX** [comment]
Yes : we know that we can do customizations (such FTL templates) but it has to be done for specific needs / projets.

Here I talk of a default behaviour. For any layers added through the catalogs services.

@MV88 The HTML default format is not suitable because it is all horizontal. 

BUT, if the default HTML template would be vertical 
and url rendered as hyperlinks 
and the HTML output set as default output for the GFI... 

... maybe it could be a good idea ?

**Comment by tdipisa** [comment]
@MaelREBOUX 

>BUT, if the default HTML template would be vertical

I think the only way you have is to provide a [custom FTL template](https://docs.geoserver.org/latest/en/user/tutorials/GetFeatureInfo/html.html) for this. 

>and url rendered as hyperlinks

GeoServer doesn't renders URLs as links in the default HTML template for GFI requests. Also in this case, if you don't want to use the [MS templating system for GFI](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/#templates), I think the only way you have is to provide a [custom FTL template](https://docs.geoserver.org/latest/en/user/tutorials/GetFeatureInfo/html.html).

>and the HTML output set as default output for the GFI...

[The default in GeoServer is text/plain](https://docs.geoserver.org/master/en/user/services/wms/reference.html#getfeatureinfo) but in MapStore you can choose a different default format for your maps.

For all three points above, if you want to change something GeoServer side, this is not the right repository anyway :)

**Comment by offtherailz** [comment]
I think the default HTML template for GeoServer is made to satisfy the generic use case. 
A table with one row for each feature (feature info can return many features as once), with the attributes as columns. 
If you prefer to create many tables, one for each feature, you can customize even the default FTL template for all the layers on your own GeoServer (see documentation),
Recognizing URLs, if you want to create links, is up to you 
When you configure these custom templates, you can create links for strings that  have to be interpreted as URLs (or using regex to automatically transform them in links, if you prefer).

**Comment by landryb** [comment]
after thinking a bit, i'm a bit uncomfortable with this issue. 

On one hand i fully agree with @tdipisa & @offtherailz  that 'the way to go' is to use HTML format for the layer and modify the default geoserver ftl in https://github.com/geoserver/geoserver/blob/main/src/wms/src/main/resources/org/geoserver/wms/featureinfo/content.ftl#L28 (maybe even something to contribute upstream ? or local modification to georchestra's geoserver (yuck!) ?) so that it detects URLs/links in attributes, and renders them as html links by default.

But on the second hand, my understanding is what @MaelREBOUX wants is that mapstore should 'parse' the default `text/plain` returned content, detect URLs/links in attributes, and renders them as html links too. That makes me feel uncomfortable (as it would imo be a hack), but that would be a middle ground...

and as @mv88 said, rendering links in the attribute table could definitely be a mapstore-specific improvement (that would be welcome !).

**Comment by MaelREBOUX** [comment]
One other point : GeoServer rocks but *impov* it is the server data. If we give him too much things to do it is not good.
What we talk here is data vizualisation which is, for me, the role of MapStore2.

store the data ==> treat / expose the data ==> vizualize the data

and for the plain/text uase case, I believe it could only be done by MapStore.

**Comment by tdipisa** [comment]
@MaelREBOUX 

>One other point : GeoServer rocks but impov it is the server data. If we give him too much things to do it is not good.

As I said this is not a plus :-), this is a core feature of GeoServer and it is something that GeoServer can usually manage through Freemarker templates (that requires text/html as a format for GFI requests)

>What we talk here is data vizualisation which is, for me, the role of MapStore2.

Of course, other ways are also available like using the [MS templating system for GFI](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/#templates) as I said before (that requires application/json as a format for GFI in order to be able to parse the response to apply the template client side)

>store the data ==> treat / expose the data ==> vizualize the data
>and for the plain/text uase case, I believe it could only be done by MapStore.

as also mentioned by @landryb text/plain is not a format that can be parsed in a good and stable way, therefore that kind of format must be excluded in this case.

@catmorales 
>I put *. ftl (header, footer and content) in the /geoserver-datadir/template/ directory to manage links to urls for all the layers published by geoserver.
Specific parameters (content.ftl in the good directory) can be applied on a specific layer and will be prioritary

Ok. I think anyway it is better use the **starts_with** function of freemarker instead using **contains** such as:

```
	  <#if attribute.value?starts_with("http") || attribute.value?starts_with("https")>
		<li><a href="${attribute.value}"target="_blank">Cliquer sur le lien</a></li>
	  <#else>
		<li>${attribute.name}: ${attribute.value}</li>
	  </#if>
```

>It works but i didn't see how to force the html setting by default in the localConfig.json to complete the test.

If you remember it is possible in localConfig by using **defaultState.initialState.mapInfo.configuration.infoFormat** set to text/html as documented [here](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.Identify). Below is a sample.

```
    "initialState": {
      "defaultState": {
		"mapInfo": {
		  "enabled": true, 
		  "disabledAlwaysOn": false, 
		  "configuration": {
			"showEmptyMessageGFI": false, 
			"infoFormat": "text/html"			
		  }
		}
```

**Comment by landryb** [comment]
> > It works but i didn't see how to force the html setting by default in the localConfig.json to complete the test.
> 
> If you remember it is possible in localConfig by using **defaultState.initialState.mapInfo.configuration.infoFormat** set to text/html as documented [here](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.Identify). Below is a sample.
> 
> ```
>     "initialState": {
>       "defaultState": {
> 		"mapInfo": {
> 		  "enabled": true, 
> 		  "disabledAlwaysOn": false, 
> 		  "configuration": {
> 			"showEmptyMessageGFI": false, 
> 			"infoFormat": "text/html"			
> 		  }
> 		}
> ```

we've had a debugging session over irc with @catmorales last week and failed to find the right incantation/way to put that in `localConfig.json`, but i've tested this chunk here locally and yes, this works fine, all GFI queries now default to `text/html`.

How about having that by default, both in https://github.com/georchestra/mapstore2-georchestra/blob/master/localConfig.json#L107 and https://github.com/georchestra/datadir/blob/master/mapstore/localConfig.json#L107 ? the default `text/plain` is a bit ... not that user-friendly :)

**Comment by tdipisa** [comment]
@landryb 

>How about having that by default, both in https://github.com/georchestra/mapstore2-georchestra/blob/master/localConfig.json#L107 and https://github.com/georchestra/datadir/blob/master/mapstore/localConfig.json#L107 ? the default text/plain is a bit ... not that user-friendly

This is not a problem for us, of course.

**Comment by catmorales** [comment]
> Ok. I think anyway it is better use the starts_with function 

done, thank you.

> If you remember it is possible in localConfig
I will try newly in localConfig.json but i I had already added it it in the config.json and new.son before the section 'dimensionData" and it works :

	"mapInfoConfiguration": {
		"showEmptyMessageGFI": false,
    		"infoFormat": "text/html",
		"maxItems": 1000
	},
	"dimensionData": {},
	"timelineData": {}

**Comment by tdipisa** [comment]
@catmorales thank you for the feedback
Can we close then this issue and open a new one dedicated for links in attribute table?

**Comment by catmorales** [comment]
Yes i agree

**Comment by tdipisa** [comment]
@catmorales will you do it?

**Comment by catmorales** [comment]
done !
