### ISSUE TITLE
When the Identify plugin is not present in main viewer, the marker is still shown

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7111]
## Description

If you remove the Identify plugin from `localConfig.json`, and you click on the map, the maker is shown anyway. This doesn't happen when you work on contexts.

## How to reproduce
-  Remove the `Identify` plugin from the main viewer
- Open new map
- Click on the map

*Expected Result*
Nothing should happen 

*Current Result*
You see a marker on the map

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by offtherailz** [comment]
**note**: tested on stable, not on master

**Comment by tonym3nsa** [comment]
Hello @offtherailz. The task mentions that we should reproduce the issue by removing the plugin from the main viewer. Should we also cater to mobile view?

**Comment by MV88** [comment]
@offtherailz 
especially because how do we get the mode from the epic? 
should we store this info in the application store when a page is mounted?

**Comment by offtherailz** [comment]
> Hello @offtherailz. The task mentions that we should reproduce the issue by removing the plugin from the main viewer. Should we also cater to mobile view?

Good question @tonym3nsa . Please check if this issue is present also on mobile. If present anyway, I guess it will be solved once for all.


> @offtherailz
> especially because how do we get the mode from the epic?
> should we store this info in the application store when a page is mounted?

I didn't get your point @MV88 . Did you already investigated and found the point? if so, please clarify to me

**Comment by MV88** [comment]
@tonym3nsa 
i have discussed with lorenzo and come up with this solution:

instead of looking at the configuration we want to give more power to the Identify plugin itself, in this way this should be solved generally (also for mobile)

What we can do is to:
- when Identify plugin mounts we dispatch a new action that sets in controls.info a new prop called available to true
- when it unmounts it set it to false

then you can change this selector 
https://github.com/geosolutions-it/MapStore2/blob/b5fdd30b1d5354fd741ff0e0564e266c80e884fa/web/client/selectors/mapInfo.js#L79-L91
by changing isPluginInContext into a check to the new available prop set in state.controls.info

in this way no change should be required in the identify epics, please double check this

**Comment by offtherailz** [comment]
to set the state.controls.info.available, there is an action creator already available in `actions/controls`
