### ISSUE TITLE
Attribute table should show urls as hyperlink

### ISSUE THREAD

**Issue by catmorales** [geosolutions-it/MapStore2#7256]
## Description
 In the attribute table,  if a field contains URLS as http:// ... or https://..., value should  appear as a clickable link.
A  click on this hyperlink open a new -browser tab with the hyperlink's page. 

Test in 

Application context : https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/testfichehtml
Layer : Sondages pour diagnostic de la présence d'amiante dans les enrobés de voirie sur Rennes Métropole
Clic on a red point : identify tool open an html page with a clickable link on the field "lien_rapport"
![image](https://user-images.githubusercontent.com/4659829/131514137-3954d316-d29e-4151-b8d8-fb2189f4def3.png)

Open the attribute table of the same layer , the link  present in th efield "lien-rapport"https://... is not clickable

![image](https://user-images.githubusercontent.com/4659829/131513920-cd0c2140-c5fb-4ad8-be8c-c678cbbdaa3f.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information

It should be activated by default and the desactivation of this function should be configurable at the level of each layer and at a more global level (configuration in the localConfig, in the plugin).

cf #7096

**Comment by tdipisa** [comment]
Just one note about the following before starting the development:

>It should be activated by default and the desactivation of this function should be configurable at the level of each layer and at a more global level (configuration in the localConfig, in the plugin).

This can be considered as a general enhancement of the Attribute Table in case of URL contents. Therefore we can only consider to enable or not hyperlinks at plugin level. Having the possibility to enable it at layer level doesn't make any sense as far as I can envisage for MS also because a FeatureType can have different kind of URLs for different attributes (a fine tuning for this detailed aspect could be too confusing in LayerSetting). **The logic will be then true/false only at plugin level.**

**Comment by catmorales** [comment]
I think it can be managed at plugin level. We will activate it for all layers.
Which plugin ? TOCItemsSettings ? Toc ?

@landryb , @MaelREBOUX , what do you think about that ?

**Comment by landryb** [comment]
i don't see a real valid reason for having it configurable... what's the point of showing/displaying an url if its not clickable ?
