### ISSUE TITLE
Add a map layer in MapStore2 from a third-party application

### ISSUE THREAD

**Issue by jahow** [geosolutions-it/MapStore2#7262]
## Description
In a SDI it is commonplace to have several applications interacting with each other. One example is having a data catalogue such as GeoNetwork where users can select datasets to then visualize in MapStore2.

In that case, GeoNetwork offers an option for taking users to a dedicated map viewer using an URL template, as documented [here](https://github.com/geonetwork/core-geonetwork/pull/2833).

Having the possibility for third-party applications to add layers in MapStore2, e.g. from WMS and WMTS services, would be an interesting feature IMO. I have looked in the documentation and issues/PR and have not found any mention of such a feature, hence this proposal.

This could be done through ad hoc URL parameters, something like:

```url
https://my.server/mapstore/openlayers/1234?addLayerType=wms&addLayerUrl=/geoserver/wms&addLayerName=mylayer
```

Another possibility would be to somehow provide a patch to the map configuration, similar to what exists [here](https://mapstore.readthedocs.io/en/latest/developer-guide/externalized-configuration/#patching-front-end-configuration).

There may be other ways more suited to the MapStore2 architecture; please note that I don't have a very strong opinion regarding *how* this could be achieved, as long as it is supported.

Also adding several layers at once should be possible as well.

## Acceptance criteria

- [ ] Support for programmatically opening a map in MapStore2 with one or several added layers in that map
- [ ] New layers should *not* be persisted in the map
- [ ] New layers should be defined using the following properties: type (WMS and WMTS at least), service URL, layer name, layer title, and optionally attribution of the data

## Other useful information

This feature is a requirement of the geOrchestra project, and inspired by [a similar feature that exists in Mapfishapp](https://github.com/georchestra/georchestra/blob/master/mapfishapp/README.md#parameters).

Thanks for taking the time to look into this!

**Comment by jahow** [comment]
I have stumbled upon [this page](https://github.com/geosolutions-it/MapStore2/blob/master/docs/developer-guide/map-query-parameters.md) which states that actions can be dispatched to the application state. Unfortunately this is apparently not enough to add random layers to the map as they need to be referenced in a catalog.

Would it make sense to expand this system e.g. to allow adding new catalogs, instead of creating a new, parallel system to overload a map configuration? Thanks

**Comment by tdipisa** [comment]
@jahow yes, the good way would be to extend the current capabilities documented [here](https://mapstore.readthedocs.io/en/latest/developer-guide/map-query-parameters/).

**Comment by jahow** [comment]
Thanks for the feedback, we'll start working on a pull request towards that goal.

**Comment by fgravin** [comment]
1. Here would be the easiest implementation (which is acceptable IMO):

ATM, the action `ADD_LAYERS_FROM_CATALOGS` takes

- layers (layerId) `string[]`
- sources (catalogIds) `string[]`

The epic fetches the catalog from the given Id, which is defined by

- `type` (WMS)
- `url`
- `name`

I would extend the `ADD_LAYERS_FROM_CATALOGS` to take either a `string` (the id of an existing catalog), or a `catalog object` 
```js
{
  type: 'WMS',
  url: 'https://geoserver/wms
}

```
If it's a string, we get the catalog from the config
If it's an object, we already have the catalog, defined by the object

The impact of the code would be very low and we would keep the simplicity of the actual system.

2. Another option would be to create another action for that like ADD_LAYERS_FROM_SERVICES, which would take

- layers (layerId) `string[]`
- sources (catalogIds) `catalog object[]`

and would behave the same as explained above, but will introduce a lot of duplicated code IMO.

3. Last solution would be to add a new catalog, and use `ADD_LAYERS_FROM_CATALOGS` by referencing the created catalog... It sounds complex because

- `ADD_CATALOG` action does not exist
- we need to be sure the actions are executed in the correct order `ADD_CATALOG`, then `ADD_LAYERS_FROM_CATALOGS` from the url params.
- we may not want to have the created catalog in the Catalog panel...

What do you think @tdipisa ?
Thanks for your inputs.

We will start the implementation asap from your recommandation. ping @tkohr
Cheers
