### ISSUE TITLE
Layer feature info format selector is not working

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#7361]
## Description

The layer feature info format selector inside the TOCItemsSettings component is not allowing the user to change format and it throws an error in console referring this line https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/TOC/TOCItemsSettings.jsx#L126

## How to reproduce

- open a map and add a wms layer from catalog
- open the TOC and select the layer
- click on the setting button (wrench)
- select the feature info tab, the last one
- select a format (eg: Properties)

*Expected Result*

- the selected card is highlighted and the feature info will use that format for the layer

*Current Result*

- the selected card is not highlight and there is this error in console

![image](https://user-images.githubusercontent.com/19175505/134896538-7a13a940-7ab9-429e-ac61-0b86303b7224.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@tonym3nsa this is a regression. This means that as part of the work on this issue we have also to identify the reasong of that regression: please report it in a issue comment.

**Comment by MV88** [comment]
@tonym3nsa 
using git bisect i noticed that this issue has been caused by [this](https://github.com/geosolutions-it/MapStore2/commit/26b881810c9970f1b8386844b33f2a969f805514) PR when 7090 was fixed

@tdipisa 
So I think we need to block [this](https://github.com/geosolutions-it/MapStore2/pull/7419) PR
revert the previous mentioned PR because it is causing #7379

and evaluate a different solution for #7090
