### ISSUE TITLE
Login as admin on QA localy

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7362]
## Description

It is not possible login as admin locally on 2021.02.xx branch

## How to reproduce

-  Open mapstore on branch 2021.02.xx
- Run npm start
- Click on Login 
- Enter admin credentials
- Click on Login

*Expected Result*

It is possible login as admin
*Current Result*

Login as admin is not possible. 
Error on console: GET http://localhost:8081/rest/geostore/users/user/details?includeattributes=true 403 (403)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by tdipisa** [comment]
@offtherailz can you please do a quick check on this to provide a feedback?

**Comment by offtherailz** [comment]
I didn't  tested it, but I remember this:

By default webpack points to dev server, that has changed a little the access_token service response. 

https://github.com/geosolutions-it/MapStore2/pull/7267/files#diff-f4016e27a47149f930a382f2694d87c601d481f4d2600e6231b3bb42dc24e555R161

The changes on client provide backward compatibility, but we don't have forward compatibility.

Maybe we should change buildConfig.js to point to `qa-mapstore.geosolutionsgroup.com` instead of dev.

(Maybe the code above is also related to #7371 ??)

**Comment by offtherailz** [comment]
It's only a file that developers edit to point to a server. I can do it but we never version it in the past (by qa-dev and so on) and we are going to configure it to point to localhost:8080 (local running back-end very soon).
If you prefer I can do a PR on stable branch in few minutes.

**Comment by offtherailz** [comment]
here it is https://github.com/geosolutions-it/MapStore2/pull/7407

**Comment by tdipisa** [comment]
@offtherailz it is in draft
