### ISSUE TITLE
Improve Identify panel on mobile

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#768]
![2016-06-29_1453](https://cloud.githubusercontent.com/assets/3932165/16452527/458cda7e-3e09-11e6-831d-f0ac5ed08a65.png)

The navigation buttons are not styled

The results panel cannot be scrolled, it is "swipeable" but not scrollable

**Comment by offtherailz** [comment]
Unfortunately there is no way to allow both with React-Swipe because of this: 
https://dlinau.wordpress.com/2015/09/16/avoid-mixing-reacts-event-system-with-native-dom-event-handling/

Dom events are called before all react events and React-Swipe uses a lib ([this one](https://github.com/voronianski/swipe-js-iso)) uses Dom Events. The way suggested in this article seems to be old and not good (accessing to the dom).

We should instead integrate a lib like this: 
https://github.com/oliviertassinari/react-swipeable-views

That doesn't have dependencies and uses native react elements, also supports nested swipes.
