### ISSUE TITLE
Error in import when storeIndex is not defined

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/MapStore2#7720]
## Description
Trying to import certain maps, MapStore fails. This is probably because some map layers do not contain `storeIndex`. We need to check if this attribute is exported, and if it exports correctly, and maybe support layers without this attribute.
Also documenting `storeIndex` in the code or in the layer documentation (if it is exported) may help future investigations. 

See mailing list: https://groups.google.com/g/mapstore-users/c/J8Xh189vVVc/m/f9WbwZ2aEQAJ?utm_medium=email&utm_source=footer

## How to reproduce

-  Try to import this file(unzip JSON): [prueba.zip](https://github.com/geosolutions-it/MapStore2/files/7853039/prueba.zip)

*Expected Result*
Map is imported

*Current Result*
You have an error. Using `?.storeIndex` in the point of failure fix the issue.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by alexander-fedorenko** [comment]
This issue is connected to the #7265 and changes introduced by related PR.
The main idea behind that PR was to use exported flat order of layers to restore group position among other layers. As noted in this bug report - this logic fails in one scenario: if group has no layers (empty group or group with groups only).

As stated in description of the bug report - issue can be fixed by adding optional chaining operator.
Though, order of groups without layers cannot be preserved without introducing additional logic to export layers and groups order explicitly.
