### ISSUE TITLE
adding a map with a WMTS layer in a geostory fails

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#7832]
## Description

cf georchestra/mapstore2-georchestra#484

## How to reproduce

- create a new geostory  
- adding a media of type 'map'
-  import attached map.json (with a WMTS background) [new.json.txt](https://github.com/geosolutions-it/MapStore2/files/8003897/new.json.txt)
- validate the map media
*Expected Result*

- the map should be displayed in the geostory
*Current Result*

- ms2 crashes with a js traceback basically boiling down to `TypeError: e.tileMatrixSet.filter is not a function`

- [x] Not browser related

**Comment by tdipisa** [comment]
The use case that you are currently adopting is currently unsupported by the GeoStory Map Editor: GeoStory imports the map configuration incorrectly without assigning the tilematrix sets to the layer while using it's own internal map editor.

It is possible to review the ways tilematrix sets are stored in the GeoStory configuration output in order to fix the current behavior.

Anyway, there are multiple ways to include a map with WMTS layers in GeoStory:
1. Create a new map from the map editor of GeoStory with a new.json that contain a WMTS layer: this need to be fixed
2. Create a new map from the map editor of GeoStory and add a WMTS layer (as a background or not): same as previous point, this requires a fix too
3. Create a new map from the map editor of GeoStory importing a map previously exported in mapstore format that contains a WMTS layer in it: this need to be fixed too
4. Use an existing map with a WMTS layer: It is working well. The standard MapStore viewer currently manages tilematrix sets of WMTS layers, therefore you could create a map through the standard viewer and then use it in GeoStory using the Media Editor. In the Media Editor of GeoStory (tab "Maps") you have by default two items: "Story Resources", provides the list of maps already used for the geostory while "MapStore Maps" provides the list of maps currently present in your MapStore catalog. If you select this in the Media Editor, you are able to browse all existing maps created in MapStore (according to the user permissions) and select one of them to be used in the geostory. Therefore, as I mentioned in the previous message, you can create a map that include tilematrix sets using the standard MapStore viewer (where these are supported) and then include that map in your geostory.

**Comment by landryb** [comment]
i can confirm that the last way works for me, that's a viable workaround (to remember.. and carefully explain to coworkers who would want to create/edit geostories) until the other ways are fixed.

**Comment by tdipisa** [comment]
Closed in favor of #7983
