### ISSUE TITLE
FeatureInfo window has wrong position wrt to LayerTree

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/MapStore2#796]
See image below.

I believe the position should be different. I would at least place the feature info on top of the LayerTree not beyond; in any case we need to place it somewhere else, probably on the side of the lower right corner of the LayerTree like in the second image below?

![clipboard01](https://cloud.githubusercontent.com/assets/693880/16564522/2c45d7ac-4208-11e6-80c6-43df2bcebf21.jpg)

![clipboard02](https://cloud.githubusercontent.com/assets/693880/16564586/8e18be40-4208-11e6-8655-b4cae0d96883.jpg)

**Comment by MV88** [comment]
As discussed, i will update the Z-index in order to position the GetFeatureInfo box over the drawer menu. This, although, I think does not resolve all the problems because in some cases the window is smaller than the GetFeatureInfo box as described in the following image. 
![image](https://cloud.githubusercontent.com/assets/11991428/17145370/29719af8-535a-11e6-8b4f-8ba341d195fd.png) 

As a result, the GetFeatureInfo box in desktop mode is often not fully visible as you can see here:
![image](https://cloud.githubusercontent.com/assets/11991428/17145725/a9082646-535b-11e6-96fa-5573dbb54e81.png)
