### ISSUE TITLE
3D Zoom for embedded map

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#7966]
Now the Cesium plugin is not enable for the embedded map but, when the user enable the 3D viewer parameters, the embedded code report the heading, pitch and roll parameters, see in the image below:

![parametri](https://user-images.githubusercontent.com/56537133/158405120-d90c168b-1517-49e2-b403-76daa6e59cee.png)

The **solutions** can be:
**1_** Add a Cesium plugin for the embedded map
**2_** Remove the heading, pitch and rol parameters on the embedded code

**How to Reproduce**
- Open a map
- Click on 3D 
- Click on Options > Share
- Click on Embed tab
- Enable the Advanced options
- Enable the Add center and zoom

**Comment by ale-cristofori** [comment]
@tdipisa From what I can see in the code about the options @ElenaGallo suggested

1. This is the implementation of an enhancement, which has partially be implemented, there is the UI part to do it but nothing happens when the map link to embed it is made.

2. Removing the the cesium parameters `heading` `pitch` and `rol` is ok but is reverting the (small piece) of work that has been done.

On a side note, I see that exporting a map in Cesium has no effects, if the map is open again it defaults to a 2d viewer (either OL or Leaflet) I am not sure if it is related to this work but I imagine that we would want to store some sort of additional parameter in the embed url to tell MapStore to visualise the map in 3d mode. 

@tdipisa Could these assumptions be discussed before starting the development please?

**Comment by tdipisa** [comment]
> @tdipisa From what I can see in the code about the options @ElenaGallo suggested
> 
> 1. This is the implementation of an enhancement, which has partially be implemented, there is the UI part to do it but nothing happens when the map link to embed it is made.
> 2. Removing the the cesium parameters `heading` `pitch` and `rol` is ok but this is  basically reverting the (small piece) of work that has been done on the UI.
> 
> On a side note, I see that exporting a map in Cesium has no effects, if the map is open again it defaults to a 2d viewer (either OL or Leaflet) I am not sure if it is related to this work but I imagine that we would want to store some sort of additional parameter in the embed url to tell MapStore to visualise the map in 3d mode.

The fact is that by default the 3D plugin is not present in the embedded map configuration. For this reason the Share URL for the embed part is normally pointing to the 2D map. This is not so correct as you can imaging: if I'm sharing a map in 3D mode the share URL should be in 3D mode. 
 
> @tdipisa Could these assumptions be discussed before starting the development please?

Yes, if you need it.

**Comment by ale-cristofori** [comment]
@ElenaGallo, as explained and agreed with @tdipisa, the test for this issue is to verify the embedded map is actually represented in Cesium when the 3d params are included in the URL (`heading`, `pitch`, `roll`). I noticed that `roll` is overlooked in the embedded map (the map will display with `roll=0` even if a value is expressed. I am going to open an issue and reference this when this one passes test, please @ElenaGallo put a reminder here after successful testing is completed.
