### ISSUE TITLE
Mapstore directlink share issue

### ISSUE THREAD

**Issue by niranjannit** [geosolutions-it/MapStore2#7989]
Hi All,
I have created a map using the localhost URL from GeoServer. The shared direct link of the mapstore doesn't open on other devices.
Can anyone help me with this issue?

Thanks in advance

**Comment by MV88** [comment]
@niranjannit hello when you have questions like this 
I suggest you to open a new thread in the mailing lists, 
if it's not present (try to do a little search before opening it)

We have one for [developers](https://groups.google.com/g/mapstore-developers) and one for [users](https://groups.google.com/g/mapstore-users), 
up to you to choose which is more appropriate

Anyway if you want to open your develop instance with different devices connected to your local intranet, 
I suggest you to start it by specifying the host
and you can do that by opening package.json and search for the "start" script and add  --host 192.168.1.XXX
where XXX is the your local ip 

then when you start the application you have to type http://192.168.1.XXX:8081/#/ instead of http://localhost:8081/#/
in this way you can use any real device you like

or you can use dev tools to simulate it
- press F12, toggle this button on, (on Chrome)
![image](https://user-images.githubusercontent.com/11991428/159228971-dafaa29c-ff83-407d-b1f2-194794d1eee5.png)
- reload mapstore

with this tool you can mimic different screen size and mapstore will run as it is on a mobile app

let me know if this was helpful
