### ISSUE TITLE
Print plugin useFixedScales regression

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/MapStore2#8000]
## Description

The Print plugin useFixedScales flag does not work anymore
 - 
## How to reproduce

-  add useFixedScales: true in the Print plugin configuration in localConfig.json
- open MapStore and print a map
- a weird scale will be used, neither the current map one, nor one of the fixed scales from the mapfish-print configuration

*Expected Result*

When useFixedScales is set, maps should be printed in one of the configured scales (the nearest one to the current map scale)

*Current Result*

A weird scale is calculated and used

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by MV88** [comment]
@mbarto i thought that a context with this configuration in place would be good and allow to test easier things

here it is
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/useFixedScales

the problem is that it crashes
![image](https://user-images.githubusercontent.com/11991428/159465632-f92b009c-4eeb-439e-af01-71667908b1ef.png)

**Comment by MV88** [comment]
ignore my previous comment, you nee to have fixed scales in config.yaml to test this
