### ISSUE TITLE
disable 3dtiles layer visibility/greying out layer when switching back to 2d mode

### ISSUE THREAD

**Issue by landryb** [geosolutions-it/MapStore2#8054]
## Description

testing the 3dtiles support added in #8009 which works nicely so far, seen a little annoyance UI-wise:

When switching back to 2d mode, the 3dtiles layer is still shown "enabled" in the layer tree pane, while i think it should either be greyed out (so that the user understands that the layer is "active but not displayed", akin to layer visibility depending on wms scales) - or either be disabled/hidden (and enabled again when switching back to 3d mode)

**Comment by weberjavi** [comment]
After agreeing with @allyoucanmap the approach on this issue would be to display the 3D layer card with a `invalid`(grayed out) state/style whenever the map is not on 3D mode.
An info tooltip would need to be added informing the user the reason of the layer being disabled (this same behaviour happens when a layer is out of its visibility range).

**Comment by landryb** [comment]
> After agreeing with @allyoucanmap the approach on this issue would be to display the 3D layer card with a `invalid`(grayed out) state/style whenever the map is not on 3D mode. An info tooltip would need to be added informing the user the reason of the layer being disabled (this same behaviour happens when a layer is out of its visibility range).

yes, that totally makes sense.
