### ISSUE TITLE
Vector Layers Style Review

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8103]
## Description

The current styler for vector layers (for both 2D and 3D maps) should be review to be inline with the recent evolutions made so far for the Visual Style Editor and 3D Tiles styler: UI design and underlying logic.
This work involve both WFS and imported vector layers but not Annotations for which the logic is different (this will be part of a future work).

As for labeling the styling needs to be separated in two different categories: 

- Styling for 3D tiles: already done with #8010
- Styling for vector data (3d lines or 3d points)

Vector data styling for cesium referring to 3d lines and points will need a different encoding so as part of the issue we need to:

- Evaluate the additional style properties that could be supported by vector data in cesium
- Perform an analysis of what needs to be done to extend annotations to work in 3D and we will try to implement basic support for point based annotations with labels and marks.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: vector layer styling logic review for 3D

**Comment by allyoucanmap** [comment]
## Cesium Styling

The base support of style should cover these improvements:

- [x] conversion of current style to the geostyler json structure. Limitation of styling applying per features where only the features with properties.id will be taken into account (eg annotation)
- [x] support of Mark, Icon, Line, Fill symbolizers with filtering option based on the attributes available


Current limitations:

- It's possible to apply only one type of symbolizer at the time so it the rule editor shows multiple rule with the same filter only the first one is used
- Fill: outline width does not change in fill sybolizer due to env limitations (see https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html?classFilter=Polygon#outlineWidth)
- Line: line cap and join are not available as properties
- Conversion from legacy style does not support geometry transformations because are missing as concept in the geostyler spec and they could be limitation in the cesium style itself (eg start/end point of a line). We could extend the geostyler spec and investigate on a possible approach

Additional interesting properties that could be added to UI but available only for Cesium. This task will need also an extension of the geostyler spec (at some point we will need a fork for this):

- [ ] **To investigate**  Mark, Icon: use [BillboardGraphics](https://cesium.com/learn/cesiumjs/ref-doc/BillboardGraphics.html)
  - pixelOffset Property specifying the pixel offset.
  - eyeOffset  Property specifying the eye offset.
  - horizontalOrigin
  - verticalOrigin
  - alignedAxis A [Cartesian3](https://cesium.com/learn/cesiumjs/ref-doc/Cartesian3.html) Property specifying the unit vector axis of rotation.
  - height A numeric Property specifying the height of the billboard in pixels, overriding the native size.
  - disableDepthTestDistance A Property specifying the distance from the camera at which to disable the depth test to.
- [ ] **To investigate** Line: use [PolylineGraphics](https://cesium.com/learn/cesiumjs/ref-doc/PolylineGraphics.html)
  - arcType specifying whether the line segments should be great arcs, rhumb lines or linearly connected.. default GEODESIC
  - clampToGround specifying whether the polyline should be clamped to the ground.

- [ ] **To investigate** Fill: use [PolygonGraphics](https://cesium.com/learn/cesiumjs/ref-doc/PolygonGraphics.html)
  - height constant altitude of the polygon.
  - extrudedHeight  altitude of the polygon extrusion
  - arcType type of lines the polygon edges use. default GEODESIC

- [ ] **To investigate** Inclusion of fill pattern style (it's possible to apply custom material)

Screenshot

Mark:

![image](https://user-images.githubusercontent.com/19175505/166210741-fa59b514-fea7-43b0-8286-1df2b2a7fef6.png)

Icon:

![image](https://user-images.githubusercontent.com/19175505/166210925-639996b0-d22f-4d90-b58a-5df76c2a4f41.png)

Line:

![image](https://user-images.githubusercontent.com/19175505/166211125-7f4bc0a4-dc54-4b9b-9b4a-a9bab7f6b2ad.png)

Fill:

![image](https://user-images.githubusercontent.com/19175505/166211475-32943499-2ed2-42d2-b746-e69e918ce1d2.png)


Conversion legacy style to current for annotation:

OpenLayers

![image](https://user-images.githubusercontent.com/19175505/166212772-b498c453-6461-40c6-b485-2d28192a3919.png)

Cesium

![image](https://user-images.githubusercontent.com/19175505/166212830-e48c576e-3880-43a9-b505-a58e7bed6906.png)

## UI/Component Improvements Proposal

 - [ ] Shapefile import Plugin: Remove style step and apply one random color by default then a user can change style from the visual editor
 - [ ] Remove the legacy styling from Leaflet feature (TBD, it would be nice also for OpenLayers)
 - [ ] Visual Style Editor: Remove slider from symbolizer property that need a more granular value selection an use a number input: radius, size
- [ ] Visual Style Editor: Improve the slider property to include a small inline number input to apply a specific value
- [ ] Visual Style Editor: Improve the dashed line to disable scaling based on stroke
- [ ] Visual Style Editor: Classification rule client side

**Comment by ElenaGallo** [comment]
Hi @allyoucanmap here what I found after testing [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/39593) on 3D mode:

1) For Point layer (ex: V_INTERVENTI), when you change the color of the halo, the width of the halo and the rotation, in the Text rule, the changes are not visible on the map
![1](https://user-images.githubusercontent.com/56537133/170230487-46260c77-708c-4a8f-90a0-6d0284991dc4.gif)


2) For polygonal and linear layers (ex: V_PIANO_BACINO, PROT.CIV: RIVI and TORRENTI MINORI), the Mark, Icon, Line and Text rules are not visible on the map

https://user-images.githubusercontent.com/56537133/170230638-8a48850f-c39d-4373-8a2a-0793b03266de.mov


**Possible Component Improvements**

a) In in Cesium, the widget button is available for layers but then the widgets are not visible in the viewer
b) In the attribute table: Zoom to feature does not zoom correctly on the feature and the Filter clicking on the map does not work.
c) The Filter layer with Area of Interest does not work (it is not possible to draw a rectangle, circle, etc. on the map)

**Comment by allyoucanmap** [comment]
@tdipisa @ElenaGallo 

> 1) For Point layer (ex: V_INTERVENTI), when you change the color of the halo, the width of the halo and the rotation, in the Text rule, the changes are not visible on the map

If you agree I'll move this fix to the issue related to labels (https://github.com/geosolutions-it/MapStore2/issues/8102) so we can verify how this could be improved. The PR associated to this issue has only introduced a base support of label symbolizer.

> 2) For polygonal and linear layers (ex: V_PIANO_BACINO, PROT.CIV: RIVI and TORRENTI MINORI), the Mark, Icon, Line and Text rules are not visible on the map

The style editor is enabling the style symbolizers based on the geometry type returned by the DescribeFeatureType request and in this specific case is defined as Geometry without specifying if it's a point, line or polygon. It the geometry is generic all the symbolizers are enabled and they will be applied only to the matching geometry:

- fill -> polygon
- line -> line
- icon -> point
- mark -> point
- label -> point

so in this situation is not possible to apply an icon to polygon. We could try to support symbolizers to not matching geometry but this will need some geometry transformation, for example get the centroid of the polygon to apply an icon. In my opinion this need a separated task

eg V_PIANO_BACINO response
![image](https://user-images.githubusercontent.com/19175505/171170771-74a2372d-7066-43b5-b019-9ffba9415a54.png)
