### ISSUE TITLE
Timeline - Disable Time interval for a layer with 'instants' 

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8206]
Related to this https://github.com/geosolutions-it/MapStore2/issues/7958#issue-1168680480 when the timeline of the layer with 'instants' (ex: Meteorite_Landings_from_NASA_Open_Data_Portal) the Time interval snap point should
be disabled because selecting the End, the animation option does not work.

**How to Reproduce**
- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/39497)
- Follows the steps in the gif below:
![connseerioni_unmiss.gif](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/9e960439-32df-486b-b8e4-6162a0672e56)

**Current Result**
The animation does not work

**Comment by tdipisa** [comment]
@ale-cristofori  according to what we saw together it is needed to review how the End radio is managed across different layers with different time domain type (range/instants) because not only the animation is not working (something that could be also acceptable as a short term functionality to be reviewed later) but also the snapping when the End radio is selected has problems (and this need to be fixed somehow)

**Comment by ale-cristofori** [comment]
Double checking with @taba90 there might be something not quite right BE side.

An example with `time_vlaanderen` dataset and this request

http://localhost:8081/proxy/?url=https%3A%2F%2Fvlaanderen-dev-mapstore.geosolutionsgroup.com%2Fgeoserver%2Fvlaanderen%2Fgwc%2Fservice%2Fwmts%3Fservice%3DWMTS%26version%3D1.0.0%26request%3DGetDomainValues%26tileMatrixSet%3DEPSG%253A4326%26layer%3Dtimeline_vlaanderen%26domain%3Dtime%26fromValue%3D2020-12-31T23%253A00%253A00.000Z%26sort%3Dasc%26limit%3D1%26fromEnd%3Dfalse

Should at least return 1 result since we have at least 1 interval starting on 31/12/2020. No domains are returned instead, this made the enabling/disabling of the radio button not consistent and that's why we decided to remove the conditional disabling.

@taba90 is having a look, hopefully the solution is BE and we will be able to re-implement the conditional disabling of the radio button.

**Comment by ale-cristofori** [comment]
The main issue for the inconsistent behaviour here is the need to implement a logic to enable/disable the radio button (start/end) when a layer made of just instants time occurrences is selected. 



The logic as is as:
Whenever we select a layer and the snapping cursor is set to a date two `getDomainValues` requests are made to detect which is the closest date to the cursor date (submitted as parameter with to the request). The FE works out which date or date interval start or end point are the closest to the cursor date (`epics/playback.js` line 352 and 355). There is a check function in the `playbackCacheNextPreviousTimes` epic that checks whether the results are returned in this format `2021-12-31-00:00:00` (indicates an instant) of this other format `2021-12-31-00:00:00/2022-04-02-00:00:00` (indicates an interval), according to the result returned we enable or disable the radio button.

**Comment by ale-cristofori** [comment]
@tdipisa FYI @alexander-fedorenko is taking this ticket and create a new branch to develop some unfinished tests still to implement.
