### ISSUE TITLE
Persist viewer type in the map configuration

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8334]
## Description

**Use Case**

Some map could contain layer only visible in a specific viewer, for example the 3D tiles layers that could be available only in a 3D scene (Cesium). In this specific case it would be nice to be able to save the map with the information related to the current map type in use to visualize the map in 3D at the next reload.

---

The switch mechanism between 2D/3D in the map viewer is related to the mapType path inside the viewer url and stored in the redux state. This information is not persisted in the map config.

- [ ] Find a solution to store this property in the map config. Should we store it as 2D/3D flag or be explicit with the map type in use (openlayers, leaflet, cesium)? In some case we switch the 2d library based on device
~~- [ ] Evaluate if it makes sense to deprecate the /viewer/:mapType/:mapId in favor of /viewer/:mapId where the mapType is managed only via config or internal state~~
~~- [ ] Review if query params needs some adjustment based on previous improvement. In particular if we need to be explicit with a map_type param or guess the map type based on the query content~~

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

## Other useful information

see https://github.com/geosolutions-it/MapStore2/pull/8320#pullrequestreview-1007647980

**Comment by weberjavi** [comment]
As discussed with @allyoucanmap It seems that there are (at least) two possible ways to persist matype (viewer) on map configuration.

One would be by storing the active map viewer type when the user saves the map; that is if the viewer is doing updates to the map and has the 3d (Cesium) viewer activated that would be the maptype stored in the config and hence the one that will be active next time the user opens the map. This implementation would be somehow _implicit_ in the sense that there's no explicit action from the user to set the maptype and it is given by the last viewer in which changes have been stored.

Another way would be to have a section on the map settings for the user to set the default maptype (viewer) that would be used when the map loads. This option would be more _explicit_ since the user would need to trigger a specific action in order to define this attribute of the map.

**Comment by tdipisa** [comment]
@weberjavi moving in blocked column for now, waiting for a decision from the core team.

**Comment by ElenaGallo** [comment]
@allyoucanmap some notes after my tests:

1_ On dashboard, the zoom of the 2D map and 3D map is different if the two map are connected. Use [this example](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/43187).

![zoom](https://user-images.githubusercontent.com/56537133/224980289-95957c3e-db77-4161-8679-500d7b9d04f9.png)

2_ On dashboard, if a map is connected to a 3D map, it is no longer possible to zoom in/out the map independently.

*Expected Result*

https://user-images.githubusercontent.com/56537133/224984287-bd7511a9-a8fd-4860-8beb-0347d9c42d2c.mov

*Current Result*

https://user-images.githubusercontent.com/56537133/224984310-0783a65a-5395-4bbb-9fca-ed6821fc1ce1.mov

3_ In the Geocarousel section of Geostory it is not possible to add a marker if the map is in 3D. Use [this example](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/geostory/43205).

https://user-images.githubusercontent.com/56537133/224990770-1bf60d93-dd47-4b51-9050-6ea83f12f643.mov

4_ On dashboard and geostory, MS crashes if user tries to change style of 3D tiles or WFS layer.

https://user-images.githubusercontent.com/56537133/224991777-efe0b18a-bdab-4d47-a953-fe3d5997fc4f.mov

**Comment by tdipisa** [comment]
@ElenaGallo thank you so much for reporting the above. Please create a dedicated issue for each point. @allyoucanmap I think at least some them should be fixed. Let's review together, in the meantime @ElenaGallo you can proceed with the creation of issues using the same project label and assigning issues to me and @allyoucanmap.

**Comment by tdipisa** [comment]
@ElenaGallo is this tested/accepted? Please mention about newly created issues with links as requested above in a new comment.

**Comment by ElenaGallo** [comment]
Hi @tdipisa,
the issue has been tested, I close it and the new issues are: #9017 #9018 #9019 #9020
