### ISSUE TITLE
Specification of Layer Geometry Types supported for editing

### ISSUE THREAD

**Issue by soconnor-ie** [geosolutions-it/MapStore2#8359]
## Description

I am currently trying to edit a feature that is stored in SQL Server, data type Geometry, storing lines.

On toggling the "Edit mode" option on the Atttribute Table for the WFS source layer via GeoServer - the following message is displayed:

![image](https://user-images.githubusercontent.com/107302163/175530830-9f924922-6114-4862-8e2b-f6bae23d85de.png)

Could a section be added to the documentation to indicate which layer geometry types are supported for feature/geometry editing.

*Documentation section involved*
- [ ] User Guide - Attribute Table (https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/)

## Other useful information
I am able to edit the attributes and successfully save these. The layer only contains lines. 
I am able to edit these geometries in QGIS using the same WFS service provided by GeoServer.

**Comment by tdipisa** [comment]
Hi @soconnor-ie thank you so much for using MS. The geometry type must be specified otherwise MS is not able to understand what drawer type need to be activated for the geometry editing. Therefore, generic Geometry is not supported. You can consult the documentation [here](https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/#manage-records). Thank you again.

**Comment by tdipisa** [comment]
@soconnor-ie I think Geometry is returned by GeoServer just because it is not able to identify the geometry type from the DB indeed. I think you have to define the Geometry type DB side.
