### ISSUE TITLE
Export of MS online doc to PDF

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8371]
## Description

Investigate if it is possible to configure Read the docs to export the [MS online documentation](https://mapstore.readthedocs.io/en/latest/) (eg. in PDF format).

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/80f2f1ba-0fb2-490e-9e96-5397ed225876)

*Documentation section involved*
- [X] User Guide
- [X] Developer Guide

## Other useful information
**Ref** https://github.com/geosolutions-it/MapStore2-C040/issues/614

**Comment by dsuren1** [comment]
@tdipisa @MV88 
### Outcome

_ReadTheDocs_ **doesn't have support** for conversion of the documentation to PDF formats for `Mkdocs` based project but only `Sphinx` based projects. Due to this we cannot make the documentation downloadable as PDF from the **download** section.
![image](https://user-images.githubusercontent.com/26929983/176908191-80f0a747-5d50-4021-8308-7d23d6cdcf41.png)


So the alternatives is use of `Mkdocs` supported plugins that help pdf conversion.
**Two possibilities**
1. With the use of the plugin `mkdocs-pdf-export-plugin`, a PDF **export** button is made available in every page of the documentation allowing users to download every **page invidually** or download **all the pages** at once
_Sample of the online Mapstore documentation with PDF support can be seen [here](https://mapstore2-temp.readthedocs.io/en/latest/)_ 
3. With the use of the plugin `print-site`, it adds an additional page that combines all pages, allowing easy exports to PDF using browser's inbuilt print functionality to the print the same.

**Comment by tdipisa** [comment]
@dsuren1 thank you. I will check your feedback and I will get back to you asap.

**Comment by dsuren1** [comment]
@tdipisa 

 `mkdocs-pdf-export-plugin` provides us with a usuable feature like download all pages at once with a dedicated export button out of the box. So we intend to move ahead with this plugin.

However there are few limitations,
- TOC in Mkdocs are not exported to the PDF. i.e Only md files are combined and exported at the moment
- Relative links in the downloaded pdf is malformed. A fix is suggested in the plugin but unfortunately it's not merged. So we might to fork and test the [fix](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/pull/64). If this fix works the same will be implemented as part of the issue else the intenal doc navigation within pdf will not be possible
