### ISSUE TITLE
Custom map thumbnail uploader

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/MapStore2#852]
The map  metadata editing should include the option to upload a custom thumbnail.

**Comment by MV88** [comment]
This is what i want to implement in order to allow the user to upload a custom thumbnail.
![mockup upload custom thumbnail](https://cloud.githubusercontent.com/assets/11991428/17177983/f7bbc5c8-5413-11e6-8853-4f8fce8a6363.png)
On the left there is the thumbnail area that is divided into two sub-area:
- topside : The preview of the old or the new thumbnail (just provided)
- bottomside : The Dropzone where the user will upload the new thumbnail.

Let me know if you have comment or doubt.

**Comment by Gnafu** [comment]
There should be an option to remove the thumbnail, falling back to the default one.
The rest is good for me.

**Comment by offtherailz** [comment]
The dropzone/selection zone should be the thumbnail itself.
And, if the thumbnail is present, an x on the top right is visible on mouse hover. Clicking on it will remove the thumbnail (from the server and as attribute of the resource).

**Comment by MV88** [comment]
Well, I have some question: 
1) After you removed the thumbnail it will also restore the default ?
2) Should we add a tooltip message "Update the thumbnail by clicking or dropping a PNG or JPEG image here" ?
3) Do you prefer the X icon in top right corner or a button in left bottom corner in order to remove the thumbnail? (see image below)
![image](https://cloud.githubusercontent.com/assets/11991428/17213053/e419f516-54d2-11e6-95ca-30e48066c734.png)

**Comment by offtherailz** [comment]
The "Click or drop an image here" label should go inside the image on mouse hover.

If the thumbnail is not present, use the normal dropzone (cyan rectangle with "Click or drop an image here") . 
When the image is present, show the image. When the user put the mouse on the thumbnail he will see the message  "Click or drop an image here" and the "x".

**Comment by MV88** [comment]
Ok thats is how it will be created with the thumbnail
![with thumbnail](https://cloud.githubusercontent.com/assets/11991428/17213821/55eb05f6-54d6-11e6-9a64-ba623a0242c9.png)

and without thumbnail
![without thumbnail](https://cloud.githubusercontent.com/assets/11991428/17213820/55d3eb00-54d6-11e6-922a-6ab40ca3f88e.png)

**Comment by offtherailz** [comment]
Yes, cool, move on

**Comment by MV88** [comment]
Just another question about the image thumbnail.
1) What are the dimensions that we will accept?
2) Are we going to stretch the image or just view what can it fit in the available space?
3) Should we accept only PNG and JPEG? I will check these formats and if the image format provided not corresponds to PNG or JPEG a message error will appear.
4) I will check also that the image weight will be < 500.000 characters visualizing a message error if it is over

**Comment by MV88** [comment]
I had some problems when i tried to update the Resource's thumbnail attribute.
See #910

**Comment by Gnafu** [comment]
WIP @ https://github.com/MV88/MapStore2/tree/iss852
