### ISSUE TITLE
Inconsistent Timeline initialization

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2#8534]
## Description

Timeline is not initializing correctly because sometimes it is disabled probably due to a race condition where epics/reducers are loaded too late. We need to ensure that the reducers/epics of timeline are initialized correctly taking into account that Timeline is using also the dimension epics that rely on MAP_CONFIG_LOADED. 

## How to reproduce

-  open a map with timeline enabled (eg. #/viewer/openlayers/33077)
- reload the page
- temporary switch to another browser tab and go back to the mapstore viewer as soon the favicon stop the loading spinner (this is needed to slow the loading and make this bug more consistent)

*Expected Result*

- the timeline is correctly initialized, this means that the inline date form is enabled, a layer selected and the cursor visible

![image](https://user-images.githubusercontent.com/19175505/187885969-ad368ddd-046e-42b9-888d-f6ff3061606d.png)

*Current Result*

- the inline date form is disabled, a layer is not selected and the cursor is not visible

![image](https://user-images.githubusercontent.com/19175505/187886108-71fd00b0-835b-450d-b2f7-6af21104e2ba.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by alexander-fedorenko** [comment]
This issue is a regression introduced by making timeline module plugin.
It's caused by the fact that timeline reducer added after MAP_CONFIG_LOADED action & epic that sets default layer for timeline.

There are two approaches to fix it:
1. Apply changes that forces app to load map configuration only after plugins are loaded (changes are already there in another branch, nothing to code: https://github.com/geosolutions-it/MapStore2/pull/8501/commits/876d6063bd0b6bb4f099112d364660a56504ea20 https://github.com/geosolutions-it/MapStore2/pull/8501/commits/aaea42b9b850f377963931a9531ab367a572877b https://github.com/geosolutions-it/MapStore2/pull/8501/commits/5a14c514426395f416388fc2b4b0f433ac628889 https://github.com/geosolutions-it/MapStore2/pull/8501/commits/dec5003cc6a2c6f570e9f949b57a5fae518a1981)
2. Add reducer of timeline into app reducers.

While second one looks preferable, it won't protect us from other plugins misbehaving because of missed MAP_CONFIG_LOADED action. @allyoucanmap

**Comment by allyoucanmap** [comment]
@alexander-fedorenko We could work with the first approach but we need to change some thing:
- rename the callback `onPluginsLoaded` with `onLoaded` or other name because the onPluginsLoaded is already used by the PluginsContainer and it has a different role
- remove the onPluginsLoadedHandler function it was needed only for the priority concept (the plugins.every check is not needed)

so please create a new commit with only needed changes, thanks
