### ISSUE TITLE
Problem opening the Attribute Table

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8570]
## Description

Maybe due to the modular plugin (to be confirmed) **sometime** when the Attribute Table is opened it will not appear immediately. This is imply in a wrong UI state.

## How to reproduce

- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)
- Select one vector layer
- Open the attribute table

*Expected Result*

The Attribue Table should appear immediately or the button to open the Attribute Table should be enabled only when the chunk of the plugin is loaded.

*Current Result*

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/6e4ff033-87f4-4df4-a5b0-f7a8c743f573)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by allyoucanmap** [comment]
@tdipisa @alexander-fedorenko this si probably due to the dynamic import done after the module import introduced here https://github.com/geosolutions-it/MapStore2/pull/8531.
The solution could be to add a simple callback component (an empty panel with the same size of the grid with a loading spinner) to the withSuspense HOC of the [FeatureEditor plugin](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/FeatureEditor.jsx#L137) (to be tested).
See the [withSuspense](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/misc/withSuspense.jsx#L22) HOC that applies a null fallback component by default.
