### ISSUE TITLE
The new widgets on the map are under the TOC

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8726]
If I add a new widget to a map, it will located below the TOC instead of being placed on the right side of the map viewer

**Current Result**
https://images.zenhubusercontent.com/39382076/b9f31027-af3c-493f-97aa-9433229b86cd/addno.mov

**Expected Result**
https://images.zenhubusercontent.com/39382076/c91a86f6-75e5-4c0b-90d3-b6adddbb6e4d/addyes.mov

**Comment by tdipisa** [comment]
@belom88 please as part of the preliminary investigation we need to understand what have introduced this regression.

**Comment by belom88** [comment]
Breaking commit: https://github.com/geosolutions-it/MapStore2/commit/70322da2630492bc419f209acf1ebaf42c716eba
Breaking change: https://github.com/geosolutions-it/MapStore2/blob/99132d457d1368470ed1b64bc8aeed65e124e2f1/web/client/plugins/Widgets.jsx#L153

**Comment by tdipisa** [comment]
Thank you @belom88. I've added the project label accordingly. Please have a quick sync with @alex-fko if needed so that then you can provide the needed fix. @allyoucanmap, you have reviewed #8621, any concern for this?

**Comment by tdipisa** [comment]
@alex-fko can you please keep track of your feedback for this here with a comment. Let's wait then the feedback of @allyoucanmap who reviewed the PRs. Then, we will manage this accordingly.

**Comment by alex-fko** [comment]
Comment with initial suggestion for the issue: https://github.com/geosolutions-it/MapStore2/pull/8622#issuecomment-1265104047

Adding offset deducts space utilized by the grid, while breakpoints are triggered by grid width.
If offset from the left side will always be active, regardless of hidden/visible TOC, then all devices having viewport width < 1100px will have single-column layout because of breakpoint hit.
To prevent layout switch 4-1-4 columns we need to think of a way of applying this offset from the left only if viewport can actually fit expanded TOC + widgets grid with 500px and more width and maybe force 1-column layout otherwise (viewport width < 1100px).
