### ISSUE TITLE
Error exporting raster data with PNG format

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#8798]
It is not possible to export the raster layer on PNG format.
Error:
> Process failed during execution Java.lang.IllegalStateException: No suitable image writer for this output.

https://user-images.githubusercontent.com/56537133/201318676-ff5fc28d-5818-40ab-a1f9-7bc610be6e35.mov

**How to Reproduce**
- Open [this map](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)
- Select `sfdem` layer on TOC
- Open the Export Data tool
- Select PNG format
- Click on Export

*Expected Result*
It is possible to export raster data with PNG format

**Comment by tdipisa** [comment]
@offtherailz can you check this please?

**Comment by tdipisa** [comment]
@offtherailz @ElenaGallo I think it is not a blocker for the release then.

**Comment by tdipisa** [comment]
@randomorder let me know how you prefer to handle this for gs-stable. Moving in Blocked for now.

**Comment by randomorder** [comment]
@tdipisa first look we need the help of a DEV to take a look at this. Maybe a shared session with an Ops guy in case needs assistance with logs access or checking the geoserver deployment..

**Comment by offtherailz** [comment]
Yes, it is a PPIO issue, so related to GeoTools. We can not exclude it is an installation issue of any kind, but to understand it we need the opinion of a gs-gt dev.

**Comment by aaime** [comment]
It's working as intended, I'm afraid: a Digital ElevationModel with float values cannot be encoded in PNG.

Let's take a step back: what you get with the DownloadProcess is not the picture you see in the browser, but the original raw data, which is a single band, float raster. This data structure can be encoded as TIFF, which supports all sorts of data types, but not in PNG nor in JPEG, because they are designed for pictures, not for data.

In terms of user experience, this is bad though, as the GUI offers an option that cannot be really used. The DownloadProcess cannot tell you in advance which formats can actually be used, because that's dataset dependent (e.g. a raster with RGB pixels can be encoded in PNG, but one with float values cannot).

The information needs to be picked somewhere else. Throwing in a couple of ideas:

1. Remove PNG (and JPEG if available) as an option. It's not a good format for raw data anyways, even if one manages to encode in it.
2. Use WCS DescribeCoverage to figure out band structure and data type and see if it makes sense to use it.
3. Modify DownloadEstimator to verify if the data and the format are compatible, or create a new process that can be used to verify compatibility.

Personally, I'd avoid 1. because the module is officially supported, someone else might already be depending on having that format. I'd also avoid 2. because WCS is not necessarily available, and moves the logic to assess compatibility, and its maintenance, in the client. The third option seems the best approach, but it will require development, and you'll get support for it only in newer versions of GeoServer.

**Comment by tdipisa** [comment]
@offtherailz considering the above I would like to update the default config by removing PNG.
