### ISSUE TITLE
3DTiles display issue

### ISSUE THREAD

**Issue by CRAIGKP63** [geosolutions-it/MapStore2#8843]
## Description

Buildings exported in 3DTiles do not display on Mapstore with cesium version while they display correctly on the Cesium Ion version. 3DTiles support remains imperfect.

## How to reproduce

- We can provide 3Dtiles formats

*Expected Result*

- 3DTiles Buildings on Cesium Ion https://cesium.com/ion/stories/viewer/?id=bf3cc7a0-85ab-4014-9765-666203531212
- we can provide mapstore solution result

*Current Result*

![cesium_ion](https://user-images.githubusercontent.com/118989591/203809817-4abfdd68-70bc-4be0-901a-75de506214c9.png)

No data is displayed on mapstore with the same 3DTile while without textures it works.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by landryb** [comment]
more details: the tileset on cesium ion is at https://assets.cesium.com/1416735/tileset.json but as is without proper CORS config it cant be loaded in mapstore due to proxy/CORS issues.

I've put a copy of the tileset in https://3d.craig.fr/datasets/Montlucon/bug_textures/tileset.json - as is it wont load in https://georchestra.geo-solutions.it/mapstore/ because it seems the cors proxy is broken on the demo site (only returns 500 codes) but you can try loading it in https://ids.craig.fr/mapstore/#/ (running 2022.01) which has CORS properly configured.

You can see a GET done on:
- https://3d.craig.fr/datasets/Montlucon/bug_textures/tileset.json
- https://3d.craig.fr/datasets/Montlucon/bug_textures/Buildings/tileset.json
- https://3d.craig.fr/datasets/Montlucon/bug_textures/Vegetation/tileset.json

you can recenter/zoom in on the dataset, but no other request is done on the b3dm files, and nothing is displayed in mapstore. The cesium ion example url manages to load that dataset fine as seen on the screenshot above.

any idea @allyoucanmap ?

**Comment by tdipisa** [comment]
@landryb @CRAIGKP63 we will do a check. Thank you for reporting.

**Comment by allyoucanmap** [comment]
@tdipisa @landryb @CRAIGKP63 This issue seems related to the missing third party draco decoder fixed with this PR https://github.com/geosolutions-it/MapStore2/pull/8204

![image](https://user-images.githubusercontent.com/19175505/208946291-6e4e9d3c-5784-4b82-96dc-741d8737f2f7.png)

This fix has been backported on the official 2022.01.xx branch with this other PR https://github.com/geosolutions-it/MapStore2/pull/8244.

We tested the same tilesets on a MapStore version 2022.01.xx and 2022.02.xx and they are working as expected:

2022.01.xx
![image](https://user-images.githubusercontent.com/19175505/208947959-41731e05-3ce1-424b-958e-102818936f38.png)

2022.02.xx
![image](https://user-images.githubusercontent.com/19175505/208949172-59cee4ad-7ad8-4b05-aa5c-12e0d0b3be15.png)


Note: I was not able to test the https://3d.craig.fr/datasets/Montlucon/bug_textures/Buildings/tileset.json endpoint because is returning a 404 error

**Comment by allyoucanmap** [comment]
Closing because has been solved with this issue #8202

**Comment by CRAIGKP63** [comment]
Thank you very much @allyoucanmap! Data works fine on the latest version of [Mapstore](https://mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/new)
