### ISSUE TITLE
Attribute filter with <> operator doesn't work as expected for Attribute Table Advanced Search

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#8993]
## Description

As per subject, the filter doesn't produce the expected result

## How to reproduce

- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/10358)
- Open the Attribute Table for the "States of US"
- Open the Advanced Search 
- Filter by attribute

![image](https://user-images.githubusercontent.com/1280027/222497614-d519a513-63c6-4e16-987f-ad319a7fdc11.png)

*Expected Result*

The list of results should not contains Alabama

*Current Result*

The list of results contains Alabama together with all the other states

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

The literal in the OGC filter sent in the request seems effectively wrong

```
<ogc:PropertyIsNotEqualTo><ogc:PropertyName>STATE_NAME</ogc:PropertyName><ogc:Literal>*Alabama*</ogc:Literal></ogc:PropertyIsNotEqualTo>
```

**Comment by allyoucanmap** [comment]
> The literal in the OGC filter sent in the request seems effectively wrong

@tdipisa this is happening because we are [wrapping the literal with the * wild card](https://github.com/geosolutions-it/MapStore2/blob/c0697db6fb454110aa3b94febded6934ffb8000c/web/client/utils/FilterUtils.js#L176) for all operators but `isNull` and `=`. This issue could be solved by including the `<>` operator alongside the [= operator check](https://github.com/geosolutions-it/MapStore2/blob/c0697db6fb454110aa3b94febded6934ffb8000c/web/client/utils/FilterUtils.js#L162) to ensure the literal does not include the `*` character, something like this:
```diff
...
- } else if (operator === "=") {
+ } else if (["=", "<>"].includes(operator)) {
...
```

**Comment by mahmoudadel54** [comment]
Hi @tdipisa 
I have tested the issue and it works me well and I always get the expected result. 

I found out this issue had been resolved here:
https://github.com/geosolutions-it/MapStore2/commit/57088f56ddebad89379bd9dd4d0d64ac38519b01 by @MV88

**Comment by tdipisa** [comment]
@ElenaGallo please double check on both DEV and QA before closing the issue. In QA it seems also working for me. If finally is the same for you we can change the milestone of this issue to 2023.02.01. Let me know.

**Comment by ElenaGallo** [comment]
@tdipisa It working for me too, on both DEV and QA.
