### ISSUE TITLE
wms legend from mapserver not available in 3d mode because of wrong empty scale parameter

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9006]
## Description

loading a layer coming from mapserver, in 2d mode this request is made and show a proper image
https://wms.dev.craig.fr/ign?service=WMS&request=GetLegendGraphic&format=image%2Fpng&height=12&width=12&layer=bdforet_v2&style=&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels%3Aon&SCALE=18056

![image](https://user-images.githubusercontent.com/3421760/146525719-05da72e5-152f-4388-a58b-70ce9a4e3b08.png)

in 3d mode, this request is made:

https://wms.dev.craig.fr/ign?service=WMS&request=GetLegendGraphic&format=image/png&height=12&width=12&layer=bdforet_v2&style=&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels:on&SCALE=

![image](https://user-images.githubusercontent.com/3421760/146526181-4945aedb-0362-40ae-9973-bde11acb9c1a.png)

and the server replies with an XML exception with ` msCalculateScale(): General error message. Invalid image extent, minx=-0.000000, miny=-0.000000, maxx=0.000000, maxy=0.000000. `, imo because mapstore sends an empty `SCALE` parameter.

can reproduce at will with this url which is freely available (wms.dev isnt, and ign service is password-protected):

https://wms.craig.fr/ortho?service=WMS&request=GetLegendGraphic&format=image/png&height=12&width=12&layer=dallage-auvergne-2009&style=&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels:on&SCALE=18056 -> if one removes 18056 then the server barfs.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
Issue coming from https://github.com/georchestra/mapstore2-georchestra/issues/444

**Comment by landryb** [comment]
i've locally tested #9024 by checking out `allyoucanmap/issue_9006` and my initial issue (reported in georchestra/mapstore2-georchestra#444) is indeed gone:
- in 2d mode, load `bdforet_v2` from https://wms.craig.fr/ign
- recenter/zoom on `mauzun` (instead of having the full extent which is slower)
- switch to 3d mode
- in the TOC, open the layer legend -> it is requested to the server with the right scale parameter (https://wms.craig.fr/ign?service=WMS&request=GetLegendGraphic&format=image/png&height=12&width=12&layer=bdforet_v2&style=&version=1.3.0&SLD_VERSION=1.1.0&LEGEND_OPTIONS=forceLabels:on&SCALE=18056)
