### ISSUE TITLE
Crash on new context when expanding search service options

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#9014]
## Description

This issue has been generated from here 

## How to reproduce

- create a new context, for example this one https://mapstore.geosolutionsgroup.com/mapstore/#/context/allplugins 
- try to enter search service config options
![image](https://user-images.githubusercontent.com/11991428/224952236-e1b2a48f-4166-48d8-a52c-b8ea6a04cb80.png)

*Expected Result*

the services panel opens

*Current Result*

crash
![image](https://user-images.githubusercontent.com/11991428/224951664-18ce55de-2a1f-45b3-bc15-c8745775f55b.png)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
**Investigation:**
The issue happens when adding loading a context with **SearchServicesConfig** plugin added

However, it doesn't happen when navigation from context manager because upon mount a reset control is dispatched which adds some default state to `searchconfig` reducer. But loading search plugin `SearchServicesConfig` enabled context by refreshing the page (_while in the context_) will result in a null state. And trying to read a property from a null state results in page crash exception.

Fix should be simple as checking null and returning a default [here](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/plugins/SearchServicesConfig.jsx#L219-L222) (best done on all props), should resolve it

**Comment by tdipisa** [comment]
@dsuren1 thank you, you can proceed with the fix.
