### ISSUE TITLE
Invalid date on Firefox

### ISSUE THREAD

**Issue by jusabatier** [geosolutions-it/MapStore2#9275]
## Description

I deployed the last "2023.02.00-RC1-geOrchestra" version of mapstore which use the "2023.01.xx" version.

When opening the attribute table of a layer with date attributes on Firefox, it display "Invalid date" instead of the date.

## How to reproduce

-  Use firefox web browser (115.0 here)
-  Add a layer with date attribute
- Open the attribute table
- All date appear as "Invalid date"

![image](https://github.com/geosolutions-it/MapStore2/assets/8310116/1ab1fdde-85c3-457d-ad9a-bacd43ad68a1)

*Expected Result*

The date should appear correctly.

*Current Result*

Date are display as "Invalid date"

- [ ] Not browser related

<details><summary> <b>Browser info</b> </summary>

| Browser Affected | Version |
|---|---|
|Firefox|Tested on 115.0 |
</details>

## Other useful information

In console we should have a related warning : 

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: 2021-03-09Z, _f: undefined, _strict: undefined, _locale: [object Object]
@https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?5f38512cef2803e9bc4a:2:2761081
30381/At/<@https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?5f38512cef2803e9bc4a:2:2780722
@https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?5f38512cef2803e9bc4a:2:2780773
At@https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?5f38512cef2803e9bc4a:2:2781067
It@https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?5f38512cef2803e9bc4a…

```

**Comment by landryb** [comment]
@tdipisa encountered by @jusabatier with https://github.com/georchestra/mapstore2-georchestra/releases/tag/2023.02.00-RC1-geOrchestra

**Comment by dsuren1** [comment]
#### Investigation outcome:
The problem is caused by how Date constructor behaves in each browser. Since [momentjs](https://stackoverflow.com/a/54552861) is not browser independent  the behavior is different for each browser. (Same is suggested in the above console warning from moment which falls back to Date constructor when format is not valid)

#### For example:
`new Date("2022-02-10Z") | moment('2022-02-10Z').format('YYYY-MM-DD[Z]')` - 2022-02-10Z (**Chrome**)
`new Date("2022-02-10Z") | moment('2022-02-10Z').format('YYYY-MM-DD[Z]')` - Invalid Date (**Firefox**)

The representation (**ex**: '2022-02-10Z') is a not a valid date string format in js. I suggest we format by removing 'Z' when field type is `date` and  [result](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/data/featuregrid/formatters/index.js#L33) is **invalid** i.e `2022-02-10Z` to `2022-02-10`. This should return the result correctly and also behavior of the field is unaffected in both the browser

Kindly let me know your thoughts @offtherailz

**Comment by offtherailz** [comment]
Yes, they look to be the same in chrome https://jsfiddle.net/begf7u1c/10/ and in firefox only the second works. LGTM

**Comment by Gaetanbrl** [comment]
> new Date("2022-02-10Z") and moment('2022-02-10Z').format('YYYY-MM-DD[Z]') - Invalid Date (Firefox)

Use moment with 2 params works for both (FF and chrome) :

`moment('2022-02-10Z','YYYY-MM-DD[Z]').format('YYYY-MM-DD[Z]')`

=> "2022-02-10Z" 

`moment('2022-02-10Z','YYYY-MM-DD[Z]').format('DD/MM/YY')`

=> "10/02/22"

IMHO It should be a good practice (if the input format is known).
