### ISSUE TITLE
Annotation not works with sideBarmenu

### ISSUE THREAD

**Issue by Gaetanbrl** [geosolutions-it/MapStore2#9310]
## Description
Annotation plugin seems only visible in Burgermenu list.
If we activate Sidebarmenu, he is not visible.

## How to reproduce
- Create context with annotation plugin and measure plugin
- Deactivate burgermenu to get sidebarmenu instead
- save context 
- open it
- You can only access to measure

*Expected Result*
Annotation still visible in sidebarmenu.

*Current Result*
Annotation is only visible in burgermenu.

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

This `SidebarMenu` code is missing for annotation :

https://github.com/geosolutions-it/MapStore2/blob/f23ae19ba6c564b9920d12b2e9a9da438a361639/web/client/plugins/Measure.jsx#L192-L206

In annotation we only have BurgerMenu :

https://github.com/geosolutions-it/MapStore2/blob/f23ae19ba6c564b9920d12b2e9a9da438a361639/web/client/plugins/Annotations.jsx#L358

**Comment by tdipisa** [comment]
Dear @Gaetanbrl that's because with the introduction of the Sidebar, the Annotation tool has been also moved in the TOC toolbar for consistency with the overall management workflow of overlays. It is still available in Burger menu but I don't remember any reason for which it should be there now, I think it is a config typo.
It is anyway true that a dependency between TOC and Annotation should be included  so that if you add the Annotation tool in the context wizard also the TOC is automatically added. That's another configuration typo you have identified. I think we can quickly fix this for the next major release. Thank you.

**Comment by Gaetanbrl** [comment]
@tdipisa thanks for response.
To complete, we can also easily override default config to use annotation into SidebarMenu.

>Docs ref : 
>https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/plugins-howto/#container-configuration
>https://groups.google.com/g/mapstore-users/c/pE84A7l4zk8/m/EaOoau68AQAJ

**Comment by offtherailz** [comment]
This can be checked during the review of annotation provided by @allyoucanmap maybe. It should be only a small change in  `pluiginsConfig.json`
