### ISSUE TITLE
Support reading/loading of raw cloud-optimized geotiff (COG)

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9320]
## Description
Requirement is support a new layer type to allow loading remote cloud-optimized geotiff (COG). The OL >v7 supports the new `GeoTIFF` source. So does MapStore as of https://github.com/geosolutions-it/MapStore2/issues/9293.

## Acceptance criteria
- [x] MapStore updated to OL that supports GeoTIFF
- [x] Support only Openlayer as of this issue
- [x] Type of the layer is `COG`
- [x] The configuration should accept url source to load the COG. Support for Catalog tool must be also included as part of this issue
- [x] Projection data should be read from tiff source by MapStore to reproject raster data. (Check during implementation) (With latest OL this is already handled by OL. [Sandbox](https://codesandbox.io/s/cog-blob-forked-2d9ftr?file=/main.js) [Example](https://openlayers.org/en/main/examples/geotiff-reprojection.html)
- [x] No further support requested as part of this issue. Therefore support Identify, Styling, Export etc are not mandatory for this implementation. **To evaluate during the implementation if something can anyway included with small effort** 
- [x] Support for cog layer to be added from catalog
- [x] Exclude COG layers when printing

## Configuration (example)
```json
{
        "type": "COG",
        "title": "Cloud optimized geotiff",
        "name": "COG exmaple",
        "source": "GeoTIFF",
        "visibility": true,
        "url": "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/Q/WD/2020/7/S2A_36QWD_20200701_0_L2A/TCI.tif" // Sample referenced from OL example
      }
```
**GeoTIFF example**
```javascript
import GeoTIFF from 'ol/source/GeoTIFF.js';
import TileLayer from 'ol/layer/WebGLTile.js';

const source = new GeoTIFF({
  sources: [
    {
      url: 'something.tif',
    },
  ],
});
const layer = new TileLayer({
      source: source,
})
```

**Catalog**:
Support for cog layer to be added from catalog. Add multiple urls via comma separated, which each url corresponds to individual layer i.e same structure above is to be maintained . 

**Layer settings**
The default layer settings to be maintained. 
**_Note_**: Check if visibility limits works.
<img width="152" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/0de17574-6fac-4b92-9e0b-43ffbc3e1702">

**Printing**
Filter COG layers and background while printing. (Should be avoided in preview as well)

## Other useful information
Ref: https://github.com/georchestra/mapstore2-georchestra/issues/338

Source for geotiff tryouts: https://geotiffjs.github.io/cog-explorer

### Questions

- Should we support multiple sources as urls? **Not mandatory for this issue**
- Should we provide configuration for color banding? **Not mandatory for this issue**
- Authentication on protected COG url? **Not mandatory for this issue**
- Thumbnail **Not mandatory for this issue**. But check if we can configure from background selector and it is simple enough to implement

**Check**
- [x] Save the map with cog layer
- [x] Permalink the map with cog layer

**Comment by landryb** [comment]
for testing you can use:
- https://cogeo.craig.fr/ign/planign/zoom_19.tif (130Gb)
- https://cogeo.craig.fr/opendata/ortho/2019_20cm_rvb.tif (190Gb)
- https://cogeo.craig.fr/opendata/ortho/2019_20cm_irc.tif (135G)

those url return an error message if you click on it (to prevent full fetching) but they open fine as rasters urls in qgis. And they should work in https://geotiffjs.github.io/cog-explorer

**Comment by dsuren1** [comment]
@landryb Kindly confirm if I can use this for testing https://cogeo.craig.fr/opendata/ortho/2018_25cm_ain+isere.tif instead. As the above ones consume lots of bandwidth when loading the layer and takes longer time to load which makes it not suitable for testing and to work with when it needs to be loaded often during implementation. 

If possible can you also provide some more urls that is considerably smaller is size with projection required for geOrchestra. Thanks!

**Comment by dsuren1** [comment]
> i've added https://cogeo.craig.fr/opendata/ortho/orthocraig3_vichy_2021.cog.tif which is a 3cm resolution image on the city of vichy, the file is less than 9Gb and loads straight away in QGIS

Thanks @landryb

**Comment by landryb** [comment]
and https://cogeo.craig.fr/opendata/ortho/ortho25_cc46_clerco_1996.cog.tif which is an EPSG:3946 1.2Gb file.

**Comment by offtherailz** [comment]
Added backport needed label because we need to add it to 2023.02.xx that is already detouched

**Comment by landryb** [comment]
Fwiw i'm testing this on the tip of 2023.02.xx (on http://localhost:8081) and no image is displayed with the vichy COG. I've seen some hits on the server when i added the COG catalog entry, the layer is added to the toc but i have no image displayed, whatever the zoom level.

there's no zoom to layer but my understanding is that #9469 isnt backported yet so that's fine, but what more is needed ? testing with the default localconfig.json btw, but i dont see errors about CORS in the browser console.

**Comment by dsuren1** [comment]
@landryb 
Kindly make sure to add needed `projectionDefs` in localConfig.json.

**Comment by landryb** [comment]
> @landryb Kindly make sure to add needed `projectionDefs` in localConfig.json and give it a try

thanks, that was the missing bit, with the definitions for EPSG:2154 & EPSG:3946 i can load the vichy and clerco cc46 COGs fine in the same viewer. I suppose that should be documented somewhere ? dunno if that should be in the user guide though (#9492 doesnt mention it)

anyway, great work on this feature, will do more testing (as backgrounds too) with the COGs i have here.

**Comment by tdipisa** [comment]
> > @landryb Kindly make sure to add needed `projectionDefs` in localConfig.json and give it a try
> 
> thanks, that was the missing bit, with the definitions for EPSG:2154 & EPSG:3946 i can load the vichy and clerco cc46 COGs fine in the same viewer. I suppose that should be documented somewhere ? dunno if that should be in the user guide though (#9492 doesnt mention it)

A reference will be included in the online documentation by @ElenaGallo 

> anyway, great work on this feature, will do more testing (as backgrounds too) with the COGs i have here.

Thank you so much

**Comment by dsuren1** [comment]
@landryb 
```javascript
{
  "type": "cog",
  "title": "Cloud optimized geotiff",
  "name": "COG exmaple",
  "visibility": false,
  "sources": [{
    "url": "https://cogeo.craig.fr/opendata/ortho/2018_25cm_ain+isere.tif"
  }],
  "group": "background"
}
```
This config is enough to visualize the COG layer as background. Please make note, that background will not zoom to extent. So I believe the background layer is added but the ones in the issues are small, when the map is zoomed to max extent, that it we may fail to notice it. Kindly check by zooming to extent that you are interested and then switching to COG background layer

**Comment by landryb** [comment]
i'll triple check as im probably doing something wrong, but with that section added to the 'layers' array in `new.json`:
![image](https://github.com/geosolutions-it/MapStore2/assets/3421760/4604ace6-e07f-49f6-9cd1-810531fe2d11)

visiting http://localhost:8081/#/viewer/new i see hits being done on the cog file in the network console, but zooming on clermont i have no data displayed, and there's no extra background in the list of backgrounds.
![image](https://github.com/geosolutions-it/MapStore2/assets/3421760/f65cb3c8-faf2-418d-bf41-db14dddc0194)

i must be doing smth wrong because i only have 6 backgrounds available when clicking on the background selector:
- osm simple dark
- osm simple light
- osm bright
- NE political
- sentinel 2 cloudless
- open street map

while i have 8 entries in the layers array - COG isnt available, nor is the empty one.

**Comment by landryb** [comment]
bah. i dont understand why, but with the EPSG:2154 ain+isere cog, testing on 2023.02.xx instead of my previous test with master, it is properly available as a background in the list, and displays fine.

![image](https://github.com/geosolutions-it/MapStore2/assets/3421760/fbab78d0-a348-43ac-8caf-bb7f6c6a6552)
