### ISSUE TITLE
Background not visible in 3D mode

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9464]
## Description

With the new default background, when 3D mode is activated, for the first time, the background is not visible.

https://github.com/geosolutions-it/MapStore2/assets/56537133/65ce1edf-60ea-4374-8926-c0621dbacb73
## How to reproduce

-  Open a new map
-  Select the 3D mode

*Expected Result*

The default background (OSM Bright) is visible in 3D mode

*Current Result*

The default background is not visible in 3D mode

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by landryb** [comment]
not 100% sure but i think it's the same bug that i had reported in georchestra/mapstore2-georchestra#601 - @ElenaGallo does the background appear if you switch it back&forth via the background selector ?

**Comment by ElenaGallo** [comment]
@landryb yes, exactly

**Comment by mahmoudadel54** [comment]
I investigated on this issue and I found out missing [visibility :false] in the empty background layer in config files. 
So what is happening when a user switches from 2D mode to 3D mode:
1- the active background layer is added first.
2- then, this empty background is added above the active background layer because of this missing.

so to resolve this bug, just add visibility by false in localConfig + new.json file.

**Comment by landryb** [comment]
thanks a lot for the analysis - i've applied the fix (eg add `visibility:false`) to each empty background layer definition (eg `localConfig.json`, `new.json` & `config.json`, ive checked that the correct json was sent for each of those, but sadly i still see the empty bg when switching to 3d mode.

my default bg (eg the one with `visibility:true` in the json) is a WMTS one but i dont think this matters.

what i've seen though is weird:
- if i load mapstore, do nothing (eg the default wmts bg is displayed) and switch to 3d mode, i get the empty bg. if i switch back to 2d mode, i get my default bg, and switching back to 3d mode i still get the empty bg.
- if i load mapstore, change the bg for osm, then change back the bg for my default wmts bg, if i switch to 3d mode the correct/expected bg is loaded (eg the default wmts one)

can someone reproduce this behaviour ?

it seems that as long as you dont change the bg, you'll get the empty bg when switching to 3d (even if the empty bg has `visibility: false`), and you get the *right* bg as long as you've changed at least once the bg.

this is with mapstore2-georchestra 2023.02.00-rc3, but i dont think there's anything specific to ms2-georchestra here.

**Comment by mahmoudadel54** [comment]
@landryb 
I investigated again and I found out a solution for this behavior. 
- The issue is the old maps, their layers includes empty layer without visibility property [not initiated with it]
- Another issue is 'getVisibilityOption' function in [**'map/cesium/Layer'** file] returns 'true' only if [visibility !== false ]---> it means if visibility property in layer object is not existing like empty layer in our case, it will be "undefined !== false" ===> true  
- So the empty layer will be added above the default one as the condition is always true.

The solution I suggested is **to edit the return condition to be [return visibility]** --> so it is truthy value will be added to the map, if false value like undefined or null for example will not be added to the map. 

Finally, I think this approach will work even if the [visibility=false] not added to empty layer object in config files.

**Comment by landryb** [comment]
your logic sounds sane and much better for compatibility with old maps, but im not comfortable enough with the code to make sure your changes covers all the possibilities and doesn't have unwanted side effects. but thanks a lot for digging further :)

**Comment by mahmoudadel54** [comment]
> your logic sounds sane and much better for compatibility with old maps, but im not comfortable enough with the code to make sure your changes covers all the possibilities and doesn't have unwanted side effects. but thanks a lot for digging further :)

If you have examples on these unexpected side effects, you can tell me about to test from my side.

**Comment by landryb** [comment]
> > your logic sounds sane and much better for compatibility with old maps, but im not comfortable enough with the code to make sure your changes covers all the possibilities and doesn't have unwanted side effects. but thanks a lot for digging further :)
> 
> If you have some examples on these unexpected side effects, you can tell me about to test from my side.

i dont have specific examples, its just that there are so many cases to test that can be overwhelming sometimes :)
