### ISSUE TITLE
GetFeatureInfo exceptions parameter format configuration

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#9466]
Hi

In MapStore we want to include webservices from "Digitaal Vlaanderen" (eg. https://geo.api.vlaanderen.be/dhmv/wms)

When MapStore sends a GetFeatureInfo request to those services, no result shows up in the identify panel. When taking a look at the response in the network tab of the browser, it is clear that an error occurred:

```xml
   <?xml version="1.0" encoding="UTF-8" standalone="no" ?>
  <!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
  <ServiceExceptionReport version="1.1.1">
  <ServiceException code="InvalidFormat">
  Parameter 'exceptions' contains unacceptable value.
  </ServiceException>
  </ServiceExceptionReport>
```

I see that MapStore adds to every GetFeatureInfo request the following parameter: "exceptions=application%2Fjson"
This parameter seems to be hardcoded in the file MapStore2\web\client\utils\mapinfo\wms.js

When taking a look at the service https://geo.api.vlaanderen.be/dhmv/wms?service=WMS&version=1.1.1&request=GetCapabilities, it is clear the exceptions parameter value that is being send by MapStore is not supported by the service:

```xml
<Exception>
  <Format>application/vnd.ogc.se_xml</Format>
  <Format>application/vnd.ogc.se_inimage</Format>
  <Format>application/vnd.ogc.se_blank</Format>
</Exception>
```

For our own MapStore GeoServers, the format application/json is supported though, so we didn't experienced this problem in the past.

We had contact with the owner of the failing services and they are not planning to add support other exceptions parameters at short term.

In order to fix the issue of malfunctioning Identify, we think it is necessary to make some changes to MapStore to support other exceptions parameter and allowing to configure them (not hardcoded), or to be able to disable the exceptions parameter. 
Or is there already a way to achieve this that I missed? 

What is your option about this? Can you give an estimation on the work needed to be done for this feature request?

**Comment by MV88** [comment]
Hi  @tdipisa @offtherailz 

me and @mahmoudadel54 had a discussion over this task and we noticed that we can simply remove the exceptions parameter but then this has to be handled here differently 
https://github.com/geosolutions-it/MapStore2/blob/600b3bc1968affba2e7859f2451ccca8ab6e9d2c/web/client/epics/identify.js#L133-L137

in particular from now on the gfi request will used the default value for exceptions when an exception happens.

Consider also that the error info is not even used and those requests that fail or have some errors are simply filtered out here

https://github.com/geosolutions-it/MapStore2/blob/600b3bc1968affba2e7859f2451ccca8ab6e9d2c/web/client/reducers/mapInfo.js#L79-L85

resulting in the feature info (given only one layer failing) to open and close, immediately

I was thinking that since we ignore the error exception we can show a notification message for each layer that fails with a message similar to this one: "The GFI request for the layer <name of the layer> has failed and will be discarded"

https://github.com/geosolutions-it/MapStore2/assets/11991428/865b020d-7d50-4c5a-8532-203e6c248d05

What do you think about it?


<hr>

there is also a weird behaviour with arcgis that if you use text/plain and you clicks where there is no data or outside layer extent, it will give 400 but using text/xml will returns valid empty body response

**Comment by tdipisa** [comment]
@MV88 

>me and @mahmoudadel54 had a discussion over this task and we noticed that we can simply remove the exceptions parameter but then this has to be handled here differently

To be clarified with @offtherailz if necessary.

>I was thinking that since we ignore the error exception we can show a notification message for each layer that fails with a message similar to this one: "The GFI request for the layer has failed and will be discarded"

Only if it does not imply big changes on the UI/UX (maybe you can clarify it better) and if we can strictly stay in the expected effort.

>there is also a weird behaviour with arcgis that if you use text/plain and you clicks where there is no data or outside layer extent, it will give 400 but using text/xml will returns valid empty body response

That's another issue, not related to the subject of this one. Therefore, nothing to do for the moment.

**Comment by offtherailz** [comment]
Please contact me @mahmoudadel54 if you are blocked or something need to be clarified, when @MV88 is ooo.

Thank you.
