### ISSUE TITLE
Geo processing tool - Advanced Settings options issue

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/MapStore2#9474]
## Description

In Advanced Settings, the option names are incorrect and are not translated correctly.

https://github.com/geosolutions-it/MapStore2/assets/56537133/2adb043a-5040-4801-bd56-132634af3767

## Other useful information

Related to https://github.com/geosolutions-it/MapStore2/pull/9351#issuecomment-1731528534

**Comment by MV88** [comment]
this is not an issue, it was intentional to define the label with the name of the parameter to be used later. 

it was requested in review, reporting the content of the comment here

![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/26d4855a-5838-46af-9730-d8d36ef287e2)

![image](https://github.com/geosolutions-it/MapStore2/assets/11991428/e9fb9301-56c6-4332-9f39-4e10866c6879)

**Comment by tdipisa** [comment]
@MV88 properties names should be reported consistently as they are intended on the WPS side and properly translated. In EN we have to use the following:

First attributes to retain
Second attributes to retain
Intersection mode
Percentages enabled
Areas enabled

each of them should be properly translated in supported languages (the description already provide the meaning).
