### ISSUE TITLE
Show creator/editor in 'Edit properties'

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2#9550]
## Description

For Admin users only, it is requested to show who created a resource as well as the last editor inside the _Edit properties_ panel.
 
## Acceptance criteria

- [x] At DB level info for both creator and last editor are persisted and the REST services return this in the requested resource metadata to the client **for admin users only**
- [ ] The information will be showed to admin users inside the Edit properties panel together with creation/modified dates

## Other useful information
Expected activities:
- Model update including two new attributes for creator /editor (_Resource_ table ?). The [migration scripts](https://github.com/geosolutions-it/geostore/tree/master/doc/sql/migration) should be created/updated accordingly
- For existing resources we know only the owner, therefore creator/editor will be the same: this should be expected by the migration script itself
- Only the user name will be used as a value for this attributes to be compliant with various possible auth strategies (eg. the user is not in MS DB)
- Update of the REST service 
- UI changes

**Comment by afabiani** [comment]
@tdipisa there's a point we need to clarify here, currently the owner does not exist in the model. The existing resources won't have one unfortunately. How to deal with it?

**Comment by tdipisa** [comment]
> @tdipisa there's a point we need to clarify here, currently the owner does not exist in the model. The existing resources won't have one unfortunately. How to deal with it?

@afabiani the owner should be retrieved by the SecurityRule table. Isn't it?

**Comment by afabiani** [comment]
@tdipisa @offtherailz backend PR available [here](https://github.com/geosolutions-it/geostore/pull/333)

**Comment by tdipisa** [comment]
@afabiani thank you so much. @offtherailz will review asap.

**Comment by tdipisa** [comment]
@Igi-ID (FYI @offtherailz)
GeoStore PR https://github.com/geosolutions-it/geostore/pull/333 has been merged, therefore we can proceed implementing the front-end part. Thank you.

**Comment by Igi-ID** [comment]
FYI @tdipisa, Given two users A and B, when user A creates a resource and then user B edits the properties of that resource, **user B is possibly not persisted in the editor column and consequently not shown in the "last modified by" field inside the modal**. Internally this would be the resource.editor field pointing to the last user that changed the resource properties. 

in [geostore\src\modules\rest\impl\src\main\java\it\geosolutions\geostore\services\rest\impl\RESTResourceServiceImpl.java](https://github.com/afabiani/geostore/blob/13847a453207133309e41e3b2eb00686b1a0ed08/src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTResourceServiceImpl.java#L177) we seem to be setting the current user of the update, so I am not sure where the issue is coming from (@afabiani). Is it possible to re-test this functionality given the scenario above?
What I get in my frontend testing is that creator and editor are set to a specific user upon creation of a resource and those values do not change after editing the properties with a different user.

**Comment by tdipisa** [comment]
@afabiani we need some of your time to review the above.

**Comment by tdipisa** [comment]
@Igi-ID 

> I can confirm I can no longer replicate the issue in my tests. 

Thanks to this from @afabiani, I suppose, right?

>however please test this patch https://github.com/geosolutions-it/geostore/pull/335

**Comment by Igi-ID** [comment]
> @Igi-ID
> 
> > I can confirm I can no longer replicate the issue in my tests.
> 
> Thanks to this from @afabiani, I suppose, right?
> 
> > however please test this patch [geosolutions-it/geostore#335](https://github.com/geosolutions-it/geostore/pull/335)

Indeed, most likely yes.
