### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by cisco974** [geosolutions-it/MapStore2#9688]
## Description
When I try to install the MapSotre back-end on a mac 

## How to reproduce
After retrieving the source code from github and building the front-end (without any problems)
Run ./build.sh
-  
 

*Current Result*
SUMMARY:
✔ 7963 tests completed
ℹ 5 tests skipped
⚠ 129 tests slow
✖ 1 test failed

FAILED TESTS:
  Test the DOMUtils
    ✖ test getOffsetBottom
      Chrome Headless 119.0.6045.123 (Mac OS 10.15.7)
    Error: Expected 11 to equal 10
        at assert (webpack://mapstore2/./node_modules/expect/lib/assert.js?:29:9)
        at Expectation.toEqual (webpack://mapstore2/./node_modules/expect/lib/Expectation.js?:85:30)
        at Context.eval (webpack://mapstore2/./web/client/utils/__tests__/DOMUtil-test.js?:44:59)

## Other useful information
Java version : openjdk version "11.0.21" 
node : v16.19.1
npm : 8.19.3
Apache Maven 3.9.5

**Comment by tdipisa** [comment]
@cisco974 thank you so much for reporting this. Can I kindly ask you to ask in ML for this problem? Doing that, one of our team member will be able to double check and the issue will be re-opened if needed.

**Comment by cisco974** [comment]
What does ML mean?

**Comment by tdipisa** [comment]
Mailing List. [Here](https://github.com/geosolutions-it/MapStore2#communication) in the readme are reported the links so that you can subscribe if you want. Thank you so much.

**Comment by fkellner** [comment]
I can reproduce that bug on my Mac. Opening the tested HTML in the browser, it becomes clear why: The `clientHeight` that is being computed is `18.5px`, which seems to be rounded up. 

<img width="690" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/28141677/3141a62f-8574-4af7-bdcf-220b20749a5f">

Because the height of the tested DOM node is not set explicitly, this test is bound to be flaky. I would suggest adding an explicit height to the content, like such:

<img width="688" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/28141677/87f1e8e8-5bf3-4807-97e3-d929fb5e67c7">

One might also want to explicitly set the `body` margin to prevent further flakyness, maybe like

```jsx
document.body.style.cssText = 'margin: 8px;';
document.body.innerHTML = `
<div id="container">
    <div id="content" style="height: 18px">
    test
    </div>
</div>`;
```
