### ISSUE TITLE
Background selector in contexts won't retain thumbnail in view mode

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#9702]
Reproduction steps

1. Open [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/COFI_ortoforo_context) in edit mode. Observe that the BG layer **thumbnail** for Ortofoto Regione Piemonte is visible on the BG selector plugin. The service was imported when the context was created.
![Image](https://github.com/geosolutions-it/MapStore2/assets/14953970/3f336820-ae5d-4cc6-8f54-bf615adab816)

2. Open the same context in view mode, observe that the thumbnail is not there, and there is the warning message `Preview Not Available`. 
![Image](https://github.com/geosolutions-it/MapStore2/assets/14953970/05857864-35f7-4771-8145-d81ad7f638a8)

3. Save the context as map, obeserve that on the created map the BG thumbnail becomes visible again
![Image](https://github.com/geosolutions-it/MapStore2/assets/14953970/398e0ca1-4909-4373-943d-a1791b330d4f)

The expected behaviour would be to see visible the BG layer thumbnail in the BG selector in the context in edit view, point 2.

**Comment by dsuren1** [comment]
### Investigation outcome
Context not showing thumbnails is due to a race condition in the loading phase of [map and context configurations](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/product/pages/Context.jsx#L114). The thumbnails are parsed and layer object is updated with an [epic](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/backgroundselector.js#L61-L82) included inside the Background plugin. But the loading of context plugin starts only after the loading of map configuration, so sometimes the epic is not ready in time to listen to `MAP_CONFIG_LOADED` action.
We can solve this by including the epic that parses thumbnail in the core config workflow of map initialization

**Comment by ale-cristofori** [comment]
@tdipisa @dsuren1 The estimation is 1.5 days including tests and PM time. Estimation has been communicated to customer and we are waiting for their approval.
