### ISSUE TITLE
Implement the option to select the Search service to use when performing a search

### ISSUE THREAD

**Issue by dsuren1** [geosolutions-it/MapStore2#9751]
## Description
MapStore supports the option to configure multiple search services and assign them a priority to sort results. However, a search is always triggered against each and every configured service. 

We want to implement the option for users to select the search to use to perform a search.
The hamburger menu should list the available services

A bonus feature would be the option to configure an icon for each service (by extending the search service configuration).

### Mock design
https://github.com/geosolutions-it/geonode-dubai/assets/1279510/dbc92901-460b-4320-ac54-759758e9d0db

[More details ](https://github.com/geosolutions-it/geonode-dubai/issues/7#issuecomment-1825408447)

## Acceptance criteria
- [x] Allow configured services to be nested under `Search by Location Name`
- [x] On selecting `Search by Location Name`, text search by default applies to all services configured
   - [x] Tooltip should say `Search on all services below`
- [x] Each search service is listed under `Search by Location Name` as shown below
        <img width="353" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/1686e60a-0eb4-420c-9f50-c8be15a43fe8">
- [x] Show sub-menu when services configured is more than one
- [x] On selecting a single search service, the text search applies only to that service. 
  - [x] Should we include default services configured in the search plugin along with the service selected i.e `Override default services` is applicable for each service? @offtherailz 
    **Feeback**
     - [x] if the user checks "Override default services" only the ones configured from the UI will be listed. Otherwise the configured from the UI will be added to the default ones.
     - [x] If only one service is present in the list, the sub-menu is redundant and so is not shown.
     - [x] If more then one service is present, so we will show the sub menu. 
  - [x] A placeholder can be configured in the wizard (By default, can we use the name of the service? @offtherailz ) - **Feeback** - `Service name|Service type`
  - [x] Is a tooltip required on each service? @offtherailz - **Feeback** - Make it configurable like placeholder
 ~~- [x]Is the `option to configure an icon for each service` applicable for this issue? Is the icon to be an image only? Or we support only the glyph icons supported in MS?~~ **Feeback** - Future enhancement, based on client's request

## Other useful information
**Ref**: https://github.com/geosolutions-it/geonode-dubai/issues/7

**Comment by offtherailz** [comment]
> ...Override default services is applicable for each service 

"Override default services" functionality is already in place. It allows to override the default service configured (typically nominatim, but if you configure something else in localConfig, it will be added) instead of adding to that list the ones configured on the map.
My mock, that is similar to the final implementation (see linked branch in the linked support ticket) showed all the current services active) takes already the correct list.
So:
- if the user checks "Override default services" only the ones configured from the UI will be listed. Otherwise the configured from the UI will be added to the default ones. 
- If only one service is present in the list, the sub-menu is redundant and so is not shown. 
- If more then one service is present, so we will show the sub menu.

> A placeholder can be configured in the wizard (By default, can we use the name of the service? @offtherailz )

Yes, ok to add the configurable placeholder in wizard.
By default "Search on "<Service Name|Service Type>", so it will show "Search on Nominatim" or "Search on US States", "Search on WFS" that looks to be good defaults.Notice that the placeholder is handled also by the nested services system, make sure to not break it. 

> Is a tooltip required on each service?
Is not "required" in sense of mandatory, but can be configured optionally (as well as the placeholder).

> Is the option to configure an icon for each service applicable for this issue? 

Because it can be problematic (allow selection of image/glyph) I'd avoid to introduce icon customization now. A future enhancement, based on client requests, can be added in the future quite easy, so we can clarify effective utility of this feature on real use cases asked by customers.
