### ISSUE TITLE
Enhance extendibility of datadir assets

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore2#9860]
## Description

We need to extend the possibilities given from the usage of a datadir in mapstore. 
Particularly for those assets that are currently not supported and might be useful

## Acceptance criteria

- [ ] Assets like CSS file needed for the header image customization
- [ ] Assets images 
- [ ] Translations files needed for some text like Footer and Header Description
- [ ] Patch files to be used to create new json files like localConfig.json and pluginsConfig.json

## Other useful information

Consider that now [MS Extensions](https://github.com/geosolutions-it/MapStoreExtension) does something similar

**Comment by tdipisa** [comment]
Waiting for further evaluations.

**Comment by offtherailz** [comment]
I have 2 possible solutions for this: 

## 1 Use Extensions System

This solution **may** do not require development on server side). 

The `extensions` folder already provides this functionality of hosting css, images and JSON (translations) files. 
So, theoretically is possible to create an extension (or more than one) called `extensions/StaticAssets` in `datadir` and configure the application to load data from the URLs based on that path.
 
See this file: 
https://dev-mapstore.geosolutionsgroup.com/mapstore/extensions/extensions.json

It already links to a translation file here https://dev-mapstore.geosolutionsgroup.com/mapstore/extensions/SampleExtension/translations/data.en-US.json loaded on startup. 
In this case translation file is declared in the `extensions.json` and automatically loaded. 

Everything in the extensions folder is already published and returned by the server with the proper mime-type. 
CSS is supported, as well as images. 

- Sample extension image:  `https://dev-mapstore.geosolutionsgroup.com/mapstor…rkers_default7211dd94387bb045fdaa700d352d44b8.png`
- Sample extension css  `https://dev-mapstore.geosolutionsgroup.com/mapstore/extensions/SampleExtension/assets/css/0.css`



### Implementation 

We can create a `fake` extension with a fake bundle js file (I don't know if an extension can exist without an `index.js` we should try), the translation file and the static files we need in the proper  folders.

```
.
├── assets
│   ├── css
│   │   └── mythemevariables.css
│   ├── img
│   │   └── Logo.png
│   └── js
│       └── extension.bb5f93c4.js
├── index.js
├── index.js.LICENSE.txt
├── index.json
└── translations
    ├── data.en-US.json
    └── data.it-IT.json
```


**note** It could be cool if the `extensions.json` index could also contain also possible links to themes or static files that can be reused, for instance in the context manager. Unfortunately the current backend implementation hardcodes a little too much the one-plugin use case. This may require a back-end development anyway.

Then we can configure the plugins to load images from the extension path.
We have to develop the system (or a convention, or in project we can hard-code the path in the index-html) to load the CSS (This have to be developed anyway on the client side. 

### Next action

I suggest to try to create this by editing `SampleExtension.zip` and test the possibilities for this. 

## 2 Static Assets

Anyway it makes sense to have a static folder called `/assets` to include possible static assets for MapStore. 
In this case we need to develop it on the back-end, that is a copy of the `/extensions`. This may require some breaking changes and updates(especially to spring-context and `web.xml` to support the new folder, as it was made for `extensions` and `configs` folders). 

# Opinion

I personally like the first approach, more "pluggable", because it improves the extensions, as I wanted initially to be the extensions.
This could enhance also mapstore product installation to be customizable with extensions, and it doesn't add any development on the server side. 
Also geonode, that relies on extensions data structure, may use this system too. 

Assets instead, even if it makes sense to have a static data folder publised, improves only MapStore product, and the user may need to manually install things on data dir.

**Comment by tdipisa** [comment]
I would like to proceed with option 1 that effectively seems more flexible and allows us to enhance the extension system directly within a downstream project.
