### ISSUE TITLE
 Disable plugin `SaveAs` for non-ADMIN role users in Contexts

### ISSUE THREAD

**Issue by ale-cristofori** [geosolutions-it/MapStore2#9919]
## Description
The `SaveAs` plugin at the moment is always visible for maps created from contexts for authenticated users if when the 'Save' plugin has been included in the context.
What we want to achieve is to disable the visibility of the  the `SaveAs` plugin in maps created from contexts for users that do NOT have the role `ADMIN`.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

## Other useful information
We should make the save as plugin configurable from plugin's configugration somehow (for example) but maintaining the current basic behaviors.

@offtherailz  edit
Due to allow to disable `SaveAs` in context via configuration, we change the current context manager configuration make saveAs plugin entry visible as child of Save plugin in the plugin selector (now it is hidden and added automatically together with save plugin), so the administrator can use `disablePluginIf` option (info provided by @Igi-ID ) to disable it.

**Comment by tdipisa** [comment]
@ale-cristofori can you please fill description using a proper template?

**Comment by offtherailz** [comment]
There is something like an old / draft version of `allowedRoles` included in the "SaveAs" plugin and not documented. Please @Igi-ID investigate and fix/update documentation properly. 
I should suggest to make this available also for "Delete" plugin. @tdipisa agree with this .

**Comment by offtherailz** [comment]
After a few check more, I suggested to proceed to `disablePluginIf`. It requires anyway to make "SaveAs" configurable in context manager, a s a child of "Save" plugin. 
Please @Igi-ID try and verify it, then provide a pr for this.

**Comment by Igi-ID** [comment]
> After a few check more, I suggested to proceed to `disablePluginIf`. It requires anyway to make "SaveAs" configurable in context manager, a s a child of "Save" plugin. Please @Igi-ID try and verify it, then provide a pr for this.

I confirm that this configuration, as suggested by @offtherailz , is indeed correctly processed and can be used to achieve the desired behavior in this issue, namely the context creator can provide a simple `cfg.disablePluginIf": "{state('userrole') !== 'ADMIN'}` in the plugin step of the context wizard.

In the PR above https://github.com/geosolutions-it/MapStore2/pull/9952, we enable the SaveAs plugin as a child of Save, rather than a dependency that's always dragged along but hidden at the same time. Being a child allows for the users to transparently include and configure the plugin in the context wizard.
